Upgrade cassandra version
scylladb/cpp-rs-driver pull request #102
Opened 2023-01-25 22:01 UTC by Gor027

## Pre-review checklist

- [x] I have split my patch into logically separate commits.
- [x] All commit messages clearly explain what they change and why.
- [x] PR description sums up the changes and reasons why they should be introduced.
- [x] I have enabled appropriate tests in `.github/workflows/build.yml` in `gtest_filter`.
- [x] I have enabled appropriate tests in `.github/workflows/cassandra.yml` in `gtest_filter`.

2023-01-26 14:47 UTC, piodul commented on scylla-rust-wrapper/src/statement.rs
> +    }
Would `b.put(&paging_state_bytes)` work here? Documentation for `BytesMut` suggests that it is possible:

https://docs.rs/bytes/latest/bytes/struct.BytesMut.html#method.with_capacity

2023-01-26 15:01 UTC, Gor027 commented on scylla-rust-wrapper/src/statement.rs
> +    }
I believe it should work, will fix it. Indeed, it will be better to put it without specifying whether it is `i8` or `u8`, as `c_char` is considered to be `u8` on some processors (e.g. ARM) and it may cause a compilation error.

2023-02-20 11:54 UTC, Lorak-mmk requested changes

2023-02-20 11:54 UTC, Lorak-mmk commented on tests/src/integration/tests/test_tracing.cpp
> +    msleep(10000);
I don't like this 10s sleep, and in general we should avoid timing-dependent tests.
If there is no way to solve this in a different way (how does Cassandra 4x solve it? Did they remove this test? Modify it somehow?), we should execute this block in a loop (and this 10s would be a time limit instead of unconditional sleep) until it succeeds or time limit is reached.

2023-02-20 15:23 UTC, Gor027 commented on scylla-rust-wrapper/src/statement.rs
> +    }
Unfortunately, `b.put(&paging_state_bytes)` is not implemented for `&[u8]` or `&[i8]`, so I think either we should add an explicit cast to `i8` and ignore the warnings or use the `cfg!` macro with some configuration flags to put `c_char` as `i8` or `u8` depending on the processor type.

2023-02-20 15:28 UTC, Gor027 commented on tests/src/integration/tests/test_tracing.cpp
> +    msleep(10000);
I have changed the unconditional sleep to a loop with a 10s limit after which it can fail. The mentioned issue in the commit message https://issues.apache.org/jira/browse/CASSANDRA-11465 is a fix for versions up to version 3.8. I think the original cpp-driver is not being tested on newer Cassandra versions 4.0 or 4.1, so perhaps we should wait for a fix to be added for those versions too.

2023-06-04 15:31 UTC, mykaul commented
By now 4.1.2 is already available. What's the plan to get this in?

2023-06-06 14:28 UTC, Gor027 commented
> By now 4.1.2 is already available. What's the plan to get this in?

Upgrading to 4.1.2 will require more changes related to the recent renaming of the parameters in `cassandra.yaml`:
https://cassandra.apache.org/doc/latest/cassandra/configuration/configuration.html
I think it is better to do that in a separate PR.

2023-06-06 21:08 UTC, Gor027 commented
This will also require some changes in `scylla-ccm` also, to generate proper configuration before starting a cluster.

2023-06-22 14:21 UTC, wprzytula commented on scylla-rust-wrapper/src/statement.rs
> +    }
@piodul WDYT?

2023-06-22 14:21 UTC, wprzytula commented on .github/workflows/cassandra.yml
>  :SslTests.Integration_Cassandra_ReconnectAfterClusterCrashAndRestart\
Ad commit message: 

> * CassandraTypes tests for Duration type, as binding duration to
  statement is not yet supported. Iterator based deserialization in the
  Rust driver will allow to add this feature.

Is this feature added in #112?

2023-06-22 14:29 UTC, piodul commented on scylla-rust-wrapper/src/statement.rs
> +    }
Let's keep the current version for simplicity and hope that the compiler optimizes it.

2023-06-22 15:03 UTC, Gor027 commented on .github/workflows/cassandra.yml
>  :SslTests.Integration_Cassandra_ReconnectAfterClusterCrashAndRestart\
Yes.

2023-06-22 15:06 UTC, wprzytula approved these changes

2023-06-22 15:19 UTC, merged