Execution profiles support
scylladb/cpp-rs-driver pull request #107
Opened 2023-03-24 19:24 UTC by wprzytula

The Rust driver has had recently added support for Execution Profiles. As that concept is present in the CPP driver, this PR implements the bridge between them (as there are, of course, some differences to be handled).
As a side effect, this PR raises the supported Rust driver version to a recent one, featuring a small UDT refactor, a major load balancing refactor and support for Serverless Cloud connections. 

This is a draft because so far only basic manual tests were done. Adding unit tests and work over enabling the existing integration tests are yet to be done.

- [x] I have split my patch into logically separate commits.
- [ ] All commit messages clearly explain what they change and why.
- [x] PR description sums up the changes and reasons why they should be introduced.
- [ ] I have enabled appropriate tests in `.github/workflows/build.yml` in `gtest_filter`.
- [ ] I have enabled appropriate tests in `.github/workflows/cassandra.yml` in `gtest_filter`.

2023-04-18 23:24 UTC, Gor027 requested changes
* Some of the commits do not compile successfully (e.g. updating the Rust driver version). * The PR description mentions that new tests are added to the `build` and `cassandra` workflows but the files are unmodified. 
* Please add a "fixes" annotation to the description that the PR will fix #38.
* Have you tried to run tests in `test_exec_profile`, can we fix and enable them in CI? I think we can also add Rust tests in CI, however, `cargo test` generated a lot of warnings that should be suppressed. 
* In the examples catalog we have the `execution_profiles` example, have you tried to run it with valgrind to check memory corruption errors?

2023-04-18 23:24 UTC, Gor027 commented on scylla-rust-wrapper/src/statement.rs
> +    query.set_consistency(Consistency::LocalOne);
> Contrary to what the commit eb6b70d138752c5e6a487eeaf69e6baa4d6652a4
says

I think the hash in the commit message is invalid, perhaps you meant to add this (?):
https://github.com/scylladb/cpp-rust-driver/commit/fcedb509

2023-04-18 23:24 UTC, Gor027 commented on scylla-rust-wrapper/src/argconv.rs
> +        concat!($str, "\0").as_ptr() as *const i8
Why not use `c_char` instead of `i8`?

2023-04-18 23:24 UTC, Gor027 commented on scylla-rust-wrapper/src/exec_profile.rs
> +}
As the Rust driver does not support the filtering policies, I think it is preferable to leave the `set_*_filtering(_n)` functions unimplemented which will cause a linkage error in the user's application noting that the feature is not supported, instead of having an empty implementation. If these functions are used in tests, they can be commented out with a message that the filtering policy is not supported.

2023-04-18 23:24 UTC, Gor027 commented on scylla-rust-wrapper/Cargo.toml
> +tracing = "0.1.37"
Why'd you need to update the `tracing` crate version?

2023-04-18 23:24 UTC, Gor027 commented on scylla-rust-wrapper/Cargo.toml
> +scylla-proxy = { git = "https://github.com/wprzytula/scylla-rust-driver.git", rev = "1abd7a27"}
Why the `scylla-proxy` version is on your fork, will there be any changes in the crate that are related to this PR?

2023-04-18 23:24 UTC, Gor027 commented on scylla-rust-wrapper/src/cluster.rs
> +}
Perhaps it is better to move these macros to the `testing.rs` file, as these are generic macros used for assertions in tests.

2023-04-18 23:24 UTC, Gor027 commented on scylla-rust-wrapper/src/exec_profile.rs
> +    max_speculative_executions: i32,
To stick to the convention let's use `cass_int32_t` instead of `i32`.

2023-04-18 23:24 UTC, Gor027 commented on scylla-rust-wrapper/src/exec_profile.rs
> +    used_hosts_per_remote_dc: u32,
`cass_uint32_t` for `u32`

2023-04-18 23:24 UTC, Gor027 commented on scylla-rust-wrapper/src/exec_profile.rs
> +}
Same as above. Please note that for functions (particularly setters) with string parameters, the API includes twin functions with `_n` suffix in the name meaning that the function signature includes lengths for string parameters.

2023-04-18 23:24 UTC, Gor027 commented on scylla-rust-wrapper/src/cluster.rs
> +}
The `assert_cass_error_eq` seems to be a generic one, so I think `assert_cass_ok` is redundant here. There is no difference to use `assert_cass_error_eq` and to pass `CassError::CASS_OK` instead of `assert_cass_ok`.

2023-04-18 23:24 UTC, Gor027 commented on scylla-rust-wrapper/src/exec_profile.rs
> +                }
Can't you use `assert_cass_error_eq` here instead of `assert_eq`?

2023-04-18 23:24 UTC, Gor027 commented on scylla-rust-wrapper/src/cluster.rs
> +                    write_str_to_c("profile1", &mut c_str, &mut c_strlen);
Why not use `argconv::str_to_c_str_n`?

2023-04-18 23:24 UTC, Gor027 commented on scylla-rust-wrapper/src/cluster.rs
> +                        .unwrap();
Wouldn't it be better to use `assert_ne!(..., None)` instead of panicking?

2023-04-18 23:24 UTC, Gor027 commented on scylla-rust-wrapper/src/cluster.rs
> +                    );
Again, why not use `assert_cass_error_eq`?

2023-04-18 23:24 UTC, Gor027 commented on scylla-rust-wrapper/src/session.rs
> +    let batch_from_raw = (); // Hardening shadow to avoid use-after-free.
I guess it is a trick to avoid using the `batch_from_raw` inside the async block. I think just the above comment is enough to prevent it.

2023-04-18 23:24 UTC, Gor027 commented on scylla-rust-wrapper/src/session.rs
> +        Arc::make_mut(&mut state)
According to the CPP driver documentation, functions that modify `CassSession` and `CassFuture` object's state should be thread-safe. Are you sure that the usage of `Arc::make_mut` does not break that?

2023-04-18 23:24 UTC, Gor027 commented on scylla-rust-wrapper/src/session.rs
> +                Arc::make_mut(prepared).set_execution_profile_handle(handle)
Same question as above.

2023-04-18 23:24 UTC, Gor027 commented on scylla-rust-wrapper/src/batch.rs
> +    pub(crate) exec_profile_handle: Option<Arc<OnceCell<ExecutionProfileHandle>>>,
I think I do not understand why `OnceCell<ExecutionProfileHandle>` should be wrapped under `Arc`.

2023-04-19 06:09 UTC, wprzytula commented on scylla-rust-wrapper/Cargo.toml
> +tracing = "0.1.37"
Without that, I was unable to compile `scylla` crate. Although I don't fully understand why it is the case, I decided to wave it aside.

2023-04-19 06:10 UTC, wprzytula commented on scylla-rust-wrapper/Cargo.toml
> +scylla-proxy = { git = "https://github.com/wprzytula/scylla-rust-driver.git", rev = "1abd7a27"}
Yes, and I'll open a PR with those changes soon.

2023-04-19 06:16 UTC, wprzytula commented on scylla-rust-wrapper/src/cluster.rs
> +                        .unwrap();
This is debatable. I don't consider `assert_ne!` option anyhow better than an `unwrap()`, which as well conveys meaning of "verify that this value is a `Some`", which is btw even more to the point than `assert_ne!`'s "verify that this value is not `None`.

2023-04-19 06:18 UTC, wprzytula commented on scylla-rust-wrapper/src/session.rs
> +    let batch_from_raw = (); // Hardening shadow to avoid use-after-free.
Rust is all about relying on compile-time errors to avoid faulty code. Why not use such a simple trick to achieve that?

2023-04-19 06:33 UTC, wprzytula commented on scylla-rust-wrapper/src/batch.rs
> +    pub(crate) exec_profile_handle: Option<Arc<OnceCell<ExecutionProfileHandle>>>,
The purpose of `exec_profile_handle` field, being a `OnceCell`, is to make it possible to resolve the profile only once after its alterations (e.g. re-setting an exec profile name) and then used straight from that field. In order to achieve that, we want the resolution's result to be saved into the `Batch` struct that is shared between calls to `cass_session_execute_batch()`.
Please note that we can't use references to that `Batch` struct inside of a `CassFuture` returned from `cass_session_execute_batch()` because of lifetime issues (possible _use-after-free_). Therefore, we have to clone `Batch`'es contents to inside the future and perform the resolution there. If the `OnceCell` wasn't shared under `Arc` and we cloned it into the future, then the resolution inside the future would never propagate into the shared `Batch` struct.
The same is true for `Arc`ed `exec_profile_handle` field in `Statement`.

Is it clear now?

2023-04-19 09:40 UTC, Gor027 commented on scylla-rust-wrapper/src/batch.rs
> +    pub(crate) exec_profile_handle: Option<Arc<OnceCell<ExecutionProfileHandle>>>,
Yes, thanks for the explanation.

2023-04-19 09:43 UTC, wprzytula commented on scylla-rust-wrapper/src/batch.rs
> +    pub(crate) exec_profile_handle: Option<Arc<OnceCell<ExecutionProfileHandle>>>,
I think I'll put this explanation into a comment.

2023-04-19 10:09 UTC, wprzytula commented on scylla-rust-wrapper/src/session.rs
> +        Arc::make_mut(&mut state)
I can't think of any way in which `Arc::make_mut()` can violate thread safety. Can you elaborate?

2023-04-19 11:01 UTC, wprzytula commented
> Some of the commits do not compile successfully (e.g. updating the Rust driver version). * The PR description mentions that new tests are added to the `build` and `cassandra` workflows but the files are unmodified.

I see no way to have both small, logically separate commits **and** commits that all compile. The bump of Rust driver version is a monolith, which changes API a lot and hence we can't expect the next commits to compile - they have to fix many issues before.

> Please add a "fixes" annotation to the description that the PR will fix [CassExecProfile #38](https://github.com/scylladb/cpp-rust-driver/issues/38).

Done.
 
> Have you tried to run tests in `test_exec_profile`, can we fix and enable them in CI? I think we can also add Rust tests in CI, however, `cargo test` generated a lot of warnings that should be suppressed.

About `cargo test` in CI: done.
About existing tests: I've described them in detail in the PR's description.
 
> In the examples catalog we have the `execution_profiles` example, have you tried to run it with valgrind to check memory corruption errors?

Yes, these are the results, so I assume everything's all right:
```
LEAK SUMMARY:
    definitely lost: 0 bytes in 0 blocks
    indirectly lost: 0 bytes in 0 blocks
    possibly lost: 123,671 bytes in 1,162 blocks
    still reachable: 548,741 bytes in 676 blocks
    suppressed: 0 bytes in 0 blocks
```

2023-04-19 11:09 UTC, piodul commented
> > Some of the commits do not compile successfully (e.g. updating the Rust driver version). * The PR description mentions that new tests are added to the `build` and `cassandra` workflows but the files are unmodified.
> 
> I see no way to have both small, logically separate commits **and** commits that all compile. The bump of Rust driver version is a monolith, which changes API a lot and hence we can't expect the next commits to compile - they have to fix many issues before.

if rust driver version bump is such a big effort then it should be done in a separate PR. If the adjustments required for the new version are straightforward and/or independent from each other (I's expect them to be), then it's fine to do it in a single commit.

2023-04-21 17:27 UTC, Lorak-mmk requested changes
Wow, really awesome PR, thanks.
I did not review tests yet. I also did not review commits that add per statement retry policy - afaik those commits will be significantly changed because this feature was re-added to Rust driver.

2023-04-21 17:27 UTC, Lorak-mmk commented on scylla-rust-wrapper/src/cluster.rs
> +    // as it results in panic due to DefaultPolicy::new() spawning a tokio task.
Did you mean `DefaultPolicyBuilder::new()`?

2023-04-21 17:27 UTC, Lorak-mmk commented on scylla-rust-wrapper/src/exec_profile.rs
> +}
If those functions are unimplemented, wouldn't it be better to actually not implement them, so that user will see the error at link time instead of runtime?

2023-04-21 17:27 UTC, Lorak-mmk commented on scylla-rust-wrapper/src/exec_profile.rs
> +    // TODO: consider CassConsistency::UNKNOWN case
How is it handled now? Will it return error from this function?

2023-04-21 17:27 UTC, Lorak-mmk commented on scylla-rust-wrapper/src/exec_profile.rs
> +    _scale_ms: cass_uint64_t, // Currently ignored, TODO: add this parameter to Rust driver
If it's not used, it would be better to return error if it's used instead of silently failing.

2023-04-21 17:27 UTC, Lorak-mmk commented on scylla-rust-wrapper/src/session.rs
>  use crate::cass_types::{get_column_type, CassDataType, UDTDataType};
Regarding commit message in commit 8b59e27a36ccff64b7764749040adf0f3babd87a: did you mean `LatencyAwarenessBuilder::new()`?

2023-04-21 17:27 UTC, Lorak-mmk commented on scylla-rust-wrapper/src/session.rs
> +    let cluster: CassCluster = ptr_to_ref(cluster_raw).clone();
This looks like an unrelated change, shouldn't it be in it's own commit?

2023-04-21 17:27 UTC, Lorak-mmk commented on scylla-rust-wrapper/src/batch.rs
>  use crate::cass_error::CassError;
This comment is regarding commit e997b77f48c9124cc0463ef679dfe2a6b07e02e6.
If I understand correctly, only one of `exec_profile_name` and `exec_profile_handle` is actually relevant - if name is set, it will be resolved to handle on next execute, `exec_profile_handle` will be set to None and `exec_profile_handle` replaced with new handle - so why are they 2 members?? Shouldn't it be an enum with 2 variants (name or a handle)?

2023-04-21 17:27 UTC, Lorak-mmk commented on scylla-rust-wrapper/src/session.rs
> +    #[allow(clippy::manual_async_fn)]
So this doesn't compile if you make it an async function? If you have some spare time you could try to open an issue in clippy repo about this

2023-04-21 17:27 UTC, Lorak-mmk commented on scylla-rust-wrapper/src/session.rs
>          cass_types::CassBatchType,
Commit 1f3819a95cc58089fdafe2e1590d07486ef001f3 needs a proper message instead of TODO

2023-04-21 17:27 UTC, Lorak-mmk commented on scylla-rust-wrapper/src/session.rs
> +            exec_profile_map.insert(name.clone(), builder.clone().build().await.into_handle());
The function already takes ownership of the hashmap - why are those clones necessary?

2023-04-24 12:58 UTC, wprzytula commented on scylla-rust-wrapper/src/session.rs
> +    let cluster: CassCluster = ptr_to_ref(cluster_raw).clone();
Do you think it actually deserves its own commit?

2023-04-24 13:15 UTC, wprzytula commented on scylla-rust-wrapper/src/cluster.rs
> +    // as it results in panic due to DefaultPolicy::new() spawning a tokio task.
Actually, I meant an action equivalent to `DefaultPolicy::new()` if such nonpublic method existed. As such does not exist, though, let's refer to `DefaultPolicyBuilder::build()`.

2023-04-24 13:25 UTC, wprzytula commented on scylla-rust-wrapper/src/batch.rs
>  use crate::cass_error::CassError;
You're right, an enum would suit the use semantics best. Will change it.

2023-04-24 13:53 UTC, wprzytula commented on scylla-rust-wrapper/src/batch.rs
>  use crate::cass_error::CassError;
On a second though, this is not feasible.

In the scenario of an enum, the transition from variant `ToResolve(ExecProfileName)` into `Resolved(Arc<OnceCell<ExecProfileHandle>>)` would have to be done inside of `cass_session_execute()`, which is a function that takes CassSession by immutable reference (in Rust terms) or that is thread-safe (in C terms). Such transition is not thread-safe, whereas the mere initialisation of a `OnceCell` indeed is: if a empty `OnceCell` is created in a non-thread-safe `cass_statement_set_execution_profile()`, then it can be safely initialised in a non-thread-safe `cass_session_execute()`.

Am I convincing?

2023-04-25 09:35 UTC, Lorak-mmk commented on scylla-rust-wrapper/src/session.rs
> +    let cluster: CassCluster = ptr_to_ref(cluster_raw).clone();
Let's leave it as is

2023-04-25 10:20 UTC, Lorak-mmk commented on scylla-rust-wrapper/src/batch.rs
>  use crate::cass_error::CassError;
Why not store `Arc<OnceCell<OurNewEnum>>`  (`OurNewEnum` wouldn't have `Arc` / `OnceCell` inside it in this scenario`)? In this case:
- New struct will have empty `OnceCell` - this means no execution profile has been set.
- `cass_statement_set_execution_profile` will set contents of `OnceCell` to enum variant with profile name.
- `cass_session_execute()` will work similarly to how it does now - clone the Arc, update the contents if the profile is not resolved.

2023-04-25 10:22 UTC, wprzytula commented on scylla-rust-wrapper/src/batch.rs
>  use crate::cass_error::CassError;
As the name explains, `OnceCell` allows for only one assignment. This means that once we set the `OnceCell`'s content to one variant of our enum, we will no longer be able to change it into another.

2023-04-25 10:24 UTC, wprzytula commented on scylla-rust-wrapper/src/batch.rs
>  use crate::cass_error::CassError;
The whole thing is about making exec profile resolution happen only once (not upon every call to `cass_session_execute()`. This is done with `OnceCell` (shared in an `Arc`), which is initialised with the profile _handle_, not name.

2023-04-25 11:18 UTC, Lorak-mmk commented on scylla-rust-wrapper/src/batch.rs
>  use crate::cass_error::CassError;
> As the name explains, `OnceCell` allows for only one assignment. This means that once we set the `OnceCell`'s content to one variant of our enum, we will no longer be able to change it into another.

This is not true, it has `take` method: https://docs.rs/tokio/latest/tokio/sync/struct.OnceCell.html#method.take
But of course a different primitive  could be used here, like `Mutex` if you feel it fits better.

2023-04-25 11:28 UTC, wprzytula commented on scylla-rust-wrapper/src/batch.rs
>  use crate::cass_error::CassError;
Why would I use Mutex when OnceCell has exactly the semantics I would like to have here? Namely, resolving and setting an exec profile handle should happen exactly once.

2023-05-04 11:49 UTC, wprzytula commented on scylla-rust-wrapper/Cargo.toml
> +scylla-proxy = { git = "https://github.com/wprzytula/scylla-rust-driver.git", rev = "1abd7a27"}
They've been already merged.

2023-05-17 12:04 UTC, wprzytula commented on scylla-rust-wrapper/src/exec_profile.rs
> +    _scale_ms: cass_uint64_t, // Currently ignored, TODO: add this parameter to Rust driver
The problem is, this function returns `void`...

2023-05-17 13:56 UTC, wprzytula commented on scylla-rust-wrapper/src/batch.rs
>  use crate::cass_error::CassError;
I've got convinced to use `RwLock` as you proposed. The new version, which I will push soon, will contain the `PerStatementExecutionProfile` holding an `RwLock` to either `Unresolved` or `Resolved` variant.

2023-05-17 14:21 UTC, wprzytula commented on scylla-rust-wrapper/src/exec_profile.rs
> +    // TODO: consider CassConsistency::UNKNOWN case
Yes. Therefore, I change this code to map `CASS_CONSISTENCY::UNKNOWN` into `None` in case of `SerialConsistency`

2023-05-17 14:35 UTC, wprzytula commented
v2:
- all commits now compile and pass tests. All changes related to Rust driver's version update are squashed in one commit, but I hope they're still readable,
- the driver used now is a rev from the main repo's `main` branch,
- retry policy emulation is no longer needed (after a change in Rust driver), so this feature was removed and replaced with the plain settings on `Statement` and `Batch`,
- `OnceCell` was replaced with `RwLock` in order to have only one field instead of two distinct (`exec_profile_name` and `exec_profile_handle`, which anyway couldn't coexist at one `Statement/Batch`).

2023-05-25 16:14 UTC, wprzytula commented
v2.1 - fixed memory leak due to an oversight during updating Rust driver's version

2023-05-30 16:20 UTC, Lorak-mmk requested changes
Finally managed to get trough it all properly. Really awesome PR, I love the tests and refactors you did. Left some minor comments.

2023-05-30 16:20 UTC, Lorak-mmk commented on scylla-rust-wrapper/src/statement.rs
> +        // Shouldn't this accept NULL ptr for unsetting retry policy on statement?
I think we discussed on Slack that it should be supported. Can you add support, or make a TODO comment?

2023-05-30 16:20 UTC, Lorak-mmk commented on scylla-rust-wrapper/src/cluster.rs
> +    _scale_ms: cass_uint64_t, // Currently ignored, TODO: add this parameter to Rust driver
Please add a warning when this is set to a value different than a "default" - where default is the value that corresponds with current rust driver behavior.

2023-05-30 16:20 UTC, Lorak-mmk commented on scylla-rust-wrapper/src/testing.rs
> +}
I think this commit is in the wrong order - you used this macro 2 commits ago.

2023-05-30 16:20 UTC, Lorak-mmk commented on scylla-rust-wrapper/src/exec_profile.rs
> +impl TryFrom<String> for ExecProfileName {
Add some empty lines maybe?

2023-05-30 16:20 UTC, Lorak-mmk commented on scylla-rust-wrapper/src/exec_profile.rs
> +    // TODO: consider CassConsistency::UNKNOWN case
So I guess that the TODO comment can be removed now?

2023-05-30 16:20 UTC, Lorak-mmk commented on scylla-rust-wrapper/src/cluster.rs
> +    exec_profile_builder_modify(&mut cluster.default_execution_profile_builder, |builder| {
I thought there was a method on exec profile for that (which called `exec_profile_builder_modify` underneath).

2023-05-30 16:20 UTC, Lorak-mmk commented on scylla-rust-wrapper/src/statement.rs
> +        // Shouldn't this accept NULL ptr for unsetting retry policy on statement?
I see that support is added later, nvm.

2023-05-31 09:07 UTC, wprzytula commented on scylla-rust-wrapper/src/cluster.rs
> +    _scale_ms: cass_uint64_t, // Currently ignored, TODO: add this parameter to Rust driver
I've opened a PR to Rust driver which introduces the missing `scale` parameter. This should fix the problem.

2023-05-31 09:26 UTC, wprzytula commented on scylla-rust-wrapper/src/cluster.rs
> +    exec_profile_builder_modify(&mut cluster.default_execution_profile_builder, |builder| {
`CassExecProfile::modify_in_place()` works, unsurprisingly, only for `CassExecProfile`, which is not involved here.

2023-06-01 13:01 UTC, Gor027 commented on scylla-rust-wrapper/src/exec_profile.rs
> +                    );
You can use `aseert_cass_error_eq` here as well.

2023-06-01 13:33 UTC, Gor027 commented on scylla-rust-wrapper/src/session.rs
> +            exec_profile_map.insert(name.clone(), builder.clone().build().await.into_handle());
Unresolving as it is not fixed(?).

2023-06-01 13:49 UTC, Gor027 commented on scylla-rust-wrapper/src/session.rs
Nit: typo in the commit message: "Default or Fallthrough".

2023-06-01 13:51 UTC, wprzytula commented on scylla-rust-wrapper/src/session.rs
> +            exec_profile_map.insert(name.clone(), builder.clone().build().await.into_handle());
As I can see, it is resolved. Before `0bf96b5 CassSession: Elide CassCluster clone in connect()`, the clone is needed, and beginning with that commit `clone()` is removed.

2023-06-01 13:54 UTC, Gor027 commented on scylla-rust-wrapper/src/session.rs
> +    }
Thanks for this commit, it helped a lot to implement serverless support without memory corruption errors.

2023-06-01 14:06 UTC, Gor027 approved these changes
LGTM. Minor comments are left in some commits as their fixes were added in further commits. Overall, thanks for this PR as besides adding support for execution profiles it also increases the quality of the driver with "all-inclusive" tests.

2023-06-07 10:14 UTC, avelanarius commented on scylla-rust-wrapper/src/cluster.rs
> +    _scale_ms: cass_uint64_t, // Currently ignored, TODO: add this parameter to Rust driver
This won't be addressed in this PR, created an issue to not forget about it later: https://github.com/scylladb/cpp-rust-driver/issues/114

2023-06-07 10:15 UTC, merged