Add serverless support
scylladb/cpp-rs-driver pull request #108
Opened 2023-04-12 17:55 UTC by Gor027

## Pre-review checklist

- [x] I have split my patch into logically separate commits.
- [x] All commit messages clearly explain what they change and why.
- [x] PR description sums up the changes and reasons why they should be introduced.
- [ ] I have enabled appropriate tests in `.github/workflows/build.yml` in `gtest_filter`.
- [ ] I have enabled appropriate tests in `.github/workflows/cassandra.yml` in `gtest_filter`.

This PR is dependent upon #107, so it is in draft until the latter is merged.
Unit tests and integration tests in CI are yet to be added.

Fixes #105

2023-06-15 14:05 UTC, wprzytula commented on scylla-rust-wrapper/Cargo.toml
>  tokio = { version = "1.1.0", features = ["full"] }
We should rather mimic the Rust driver's behaviour (not to put unnecessary burden on non-cloud users of the driver) and provide cloud functionalities only if they request it explicitly (use features).

2023-06-15 14:05 UTC, wprzytula commented on scylla-rust-wrapper/src/cloud.rs
> +    }
What is this mysterious hardcoded `"invalid_filename"` ?

2023-06-15 14:05 UTC, wprzytula commented on scylla-rust-wrapper/extern/cassandra.h
>    CASS_ERROR_SOURCE_SSL,
Oh, so we have duplicated `cassandra.h` in our repo? Perhaps we could somehow avoid this, e.g. by use of soft links.

2023-06-15 14:05 UTC, wprzytula commented on scylla-rust-wrapper/src/cluster.rs
> +pub type SessionConfigError = CloudConfigError;
Why such name?

2023-06-20 16:18 UTC, Gor027 commented on scylla-rust-wrapper/extern/cassandra.h
>    CASS_ERROR_SOURCE_SSL,
Yes, but better to do that in a separate PR. Will create an issue to not forget about it.

2023-06-20 16:20 UTC, Gor027 commented on scylla-rust-wrapper/src/cluster.rs
> +pub type SessionConfigError = CloudConfigError;
What would you suggest instead? Currently, there may be errors when a cloud session is created, but that may change in the future.

2023-06-20 16:21 UTC, Gor027 commented on scylla-rust-wrapper/src/cloud.rs
> +    }
I just kept the previous implementation of the function. Will fix it, tnx.

2023-06-20 16:22 UTC, Gor027 commented on scylla-rust-wrapper/Cargo.toml
>  tokio = { version = "1.1.0", features = ["full"] }
I will see if it is possible to dynamically enable features of a certain dependency.

2023-06-22 10:49 UTC, wprzytula commented on scylla-rust-wrapper/Cargo.toml
>  tokio = { version = "1.1.0", features = ["full"] }
This is definitely possible, as we do this in Rust driver itself. Excerpt from Rust driver's `Cargo.toml`:
```toml
[features]
default = []
ssl = ["dep:tokio-openssl", "dep:openssl"]
cloud = ["ssl", "scylla-cql/serde", "dep:serde_yaml", "dep:serde", "dep:url", "dep:base64"]
secret = ["scylla-cql/secret"] # <- this is the most suitable for your situation
```

2023-06-22 11:42 UTC, wprzytula commented on scylla-rust-wrapper/src/cluster.rs
> +pub type SessionConfigError = CloudConfigError;
Then wouldn't an enum convey the intention better?
```rust
pub enum SessionConfigError {
  Cloud(CloudConfigError),
  // here new variants can be added in the future
}
```

2023-06-22 13:18 UTC, Gor027 commented on scylla-rust-wrapper/src/cluster.rs
> +pub type SessionConfigError = CloudConfigError;
Done.

2023-06-22 13:29 UTC, Gor027 commented on scylla-rust-wrapper/Cargo.toml
>  tokio = { version = "1.1.0", features = ["full"] }
Fixed it in a separate commit: [4ad0ede](https://github.com/scylladb/cpp-rust-driver/pull/108/commits/4ad0ededc8de73b81344abbeaaf31f5db6d33f3c)

2023-06-22 14:08 UTC, wprzytula commented on CMakeLists.txt
>      INSTALL_COMMAND ""
Are we going to allow building bindings without `cloud` or `ssl` feature?

2023-06-22 15:19 UTC, Gor027 commented on scylla-rust-wrapper/Cargo.toml
>  tokio = { version = "1.1.0", features = ["full"] }
After discussing it with @Lorak-mmk, decided to enable SSL and cloud features.

2023-06-27 14:12 UTC, wprzytula requested changes
As I've found some serious errors, it is clear to me that specific tests in bindings for cloud mode are a must. Please add them to this PR.

2023-06-27 14:12 UTC, wprzytula commented on src/driver_config.hpp
>  #define HAVE_OPENSSL
Please explain this change.

2023-06-27 14:12 UTC, wprzytula commented on scylla-rust-wrapper/src/external.rs
> +        CassError::CASS_ERROR_CLOUD_CONFIG_UNKNOWN_ERROR => "Unknown error\0",
Please make sure to mention "cloud" in each of these messages.

2023-06-27 14:12 UTC, wprzytula commented on scylla-rust-wrapper/src/cloud.rs
> +    CassError::CASS_ERROR_LIB_BAD_PARAMS
Please don't put error-case returns on the default path and ok-case returns inside an `if`. This is counterintuitive.
My suggestion:
```suggestion
    if let Some(config_path) = config_path {
        if !Path::new(config_path).exists() {
            return CassError::CASS_ERROR_LIB_BAD_PARAMS;
        }

        cluster.connection_bundle_path = Some(config_path.to_string());
        CassError::CASS_OK
    } else {
        CassError::CASS_ERROR_LIB_BAD_PARAMS
    }
```

2023-06-27 14:12 UTC, wprzytula commented on scylla-rust-wrapper/src/cloud.rs
> +    CassError::CASS_ERROR_LIB_BAD_PARAMS
Another way, to keep the ok-case linear:
```suggestion
    let config_path = if let Some(path) = config_path {
        if !Path::new(config_path).exists() {
            return CassError::CASS_ERROR_LIB_BAD_PARAMS;
        }
        path
    } else {
       return CassError::CASS_ERROR_LIB_BAD_PARAMS;
    };
    
    cluster.connection_bundle_path = Some(config_path.to_string());
    CassError::CASS_OK
```

2023-06-27 14:12 UTC, wprzytula commented on scylla-rust-wrapper/src/cluster.rs
> +        execution_profile_builder = execution_profile_builder.load_balancing_policy(load_balancing);
This `load_balancing_config.clone()` seems redundant.

2023-06-27 14:12 UTC, wprzytula commented on scylla-rust-wrapper/src/cluster.rs
> +                        execution_profile_builder.build().into_handle(),
Let's extract `handle`:
```rust
let handle = execution_profile_builder.build().into_handle();
```
and then use it instead of repeating the code that creates the handle.

2023-06-27 14:12 UTC, wprzytula commented on scylla-rust-wrapper/src/cluster.rs
> +                .collect();
I had extended `known_nodes()` in Rust driver specially for this case to avoid collecting, and then got rid of it. I'm unhappy that you revert this `collect()` back.

2023-06-27 14:12 UTC, wprzytula commented on scylla-rust-wrapper/src/cluster.rs
> +            }
In the cloud case, cloud-agnostic settings are not preserved. Consider a sequence of calls:
```C
cass_cluster_set_cloud_secure_connection_bundle(/*...*/);
cass_cluster_set_tcp_nodelay(/*...*/); // This is not respected
cass_session_connect(/*...*/);
// The resulting session has TCP nodelay set to default, not respecting the setting above 
```

The problem is that Rust sees different instantiations of `GenericSessionBuilder` as distinct types, even though they share the same underlying `SessionConfig` and most of API. One possible solution is to only hold `SessionConfig` in `CassCluster` (instead of `SessionBuilder`) and:
- either construct appropriate instantiation of `GenericSessionBuilder` on-demand (upon call to `cass_session_connect()`, in `build_session_builder()`),
- or skip `GenericSessionBuilder` API at all and use bare `SessionConfig` together with `Session::connect()`.

2023-06-27 17:00 UTC, Gor027 commented on src/driver_config.hpp
>  #define HAVE_OPENSSL
I did not notice that perhaps this was auto-modified after a build.

2023-06-27 17:26 UTC, Gor027 commented on scylla-rust-wrapper/src/cluster.rs
> +                .collect();
Sorry, applying stashed changes reverted this, will fix it.

2023-06-27 23:56 UTC, Gor027 commented on scylla-rust-wrapper/src/cluster.rs
> +            }
* Using bare `SessionConfig` *maybe* would require huge refactoring to get rid of building the default execution profile and other configurations in `build_session_builder`. But if it is possible, I believe we should follow this direction. 
* It is easy with `SessionBuilder` to just set a previously created session config and then set up other configurations before building a session object. However, the same cannot be done with `CloudSessionBuilder` as its constructor sets some configs which we should not override. 

I think the easiest way is to keep all common config params in the `CassCluster` object (e.g. tcp_nodelay, connect_tmeout, etc.) and after constructing an appropriate instantiation of `GenericSessionBuilder`, manually set these parameters.

2023-06-28 05:21 UTC, wprzytula commented on scylla-rust-wrapper/src/cluster.rs
> +            }
On the other hand, _the easiest way_ that you mention involves duplication of many config params and is prone to accidentally forgetting about some of them. Using bare `SessionConfig` lets us have all those params already set in the proper place.

2023-06-28 13:04 UTC, Gor027 commented on scylla-rust-wrapper/src/cluster.rs
> +            }
I agree, but having bare `SessionConfig` implies having duplication of some `SessionBuilder` setters' code, e.g. `user()`, and remembering to apply changes to these codes in both drivers.

2023-06-29 16:01 UTC, wprzytula commented on scylla-rust-wrapper/src/cluster.rs
> +            }
What is the solution that you decide to settle on?

2023-06-29 16:10 UTC, Gor027 commented on scylla-rust-wrapper/src/cluster.rs
> +            }
To replace `SessionBuilder` with `SessionConfig`. I have added some necessary changes to the Rust driver to achieve this. https://github.com/scylladb/scylla-rust-driver/pull/750

2023-06-29 16:18 UTC, wprzytula commented on scylla-rust-wrapper/src/cluster.rs
> +            }
Bear in mind disadvantages that you yourself pointed out: 
> having bare SessionConfig implies having duplication of some SessionBuilder setters' code, e.g. `user()`

to avoid code duplication, i suggest moving logic from `SessionBuilder` to correspoding `SessionConfig` setters. This way, the logic for creating `CloudConfig`, as well as e.g. `user()`'s logic would be accessible for us even if bypassing `SessionBuilder` as you prefer.

2024-04-29 12:56 UTC, Lorak-mmk commented
I think we can close this as serverless is no longer a thing

2024-04-29 12:56 UTC, closed without merging