New deserialization api
scylladb/cpp-rs-driver pull request #112
Opened 2023-05-26 11:07 UTC by Gor027

## Pre-review checklist

Fixes #94 

This PR Integrates the new deserialization API from the Rust driver which is a [WIP](https://github.com/scylladb/scylla-rust-driver/pull/665).
It is dependent upon the execution profiles' PR and can be merged only after the latter is already done.
The lazy deserialization allows to also implement binder makers for decimal and duration types. The `test_cassandra_types` tests for these types are also enabled.

- [x] I have split my patch into logically separate commits.
- [x] All commit messages clearly explain what they change and why.
- [x] PR description sums up the changes and reasons why they should be introduced.
- [x] I have enabled appropriate tests in `.github/workflows/build.yml` in `gtest_filter`.
- [x] I have enabled appropriate tests in `.github/workflows/cassandra.yml` in `gtest_filter`.

2023-06-01 13:23 UTC, wprzytula requested changes

2023-06-01 13:23 UTC, wprzytula commented on scylla-rust-wrapper/src/cass_error.rs
> +    fn from(error: &ParseError) -> Self {
What is the reason behind this change? Do you want to avoid consuming the error somewhere?

2023-06-01 13:23 UTC, wprzytula commented on scylla-rust-wrapper/src/cass_error.rs
>          self.to_string()
I'm wondering why do we even need this `msg()` method. Isn't it virtually equivalent to `ToString::to_string()` functionality? And `ToString::to_string()` is blanket implemented for every `T: Display`, which means that we only have to make `CassErrorMessage` require `Display` and we will be able to remove `msg()` alltogether.

2023-06-01 13:23 UTC, wprzytula commented on scylla-rust-wrapper/src/future.rs
> +        Ok(CassResultValue::QueryResult(result)) => match result.result.tracing_id() {
Consider renaming the outer `result` into `cass_result`.

2023-06-01 13:23 UTC, wprzytula commented on scylla-rust-wrapper/src/query_result.rs
> +                Some(rs) => (new_pos + 1 < rs) as cass_bool_t, // TODO: add next row decoding
Why is this `+1` added? Isn't new `rs` (result of `rows_num()`) equivalent to old `rs.len()` ?

2023-06-01 13:23 UTC, wprzytula commented on scylla-rust-wrapper/src/query_result.rs
> +    let result = row_from_raw.result.upgrade().unwrap();
Why is this `unwrap()` safe? Please write in a comment.

2023-06-01 13:23 UTC, wprzytula commented on scylla-rust-wrapper/src/query_result.rs
>          .find(|(_, spec)| {
Can we drop this explicit `return` in the last expression of the function?

2023-06-01 13:23 UTC, wprzytula commented on scylla-rust-wrapper/src/query_result.rs
>          .find(|(_, spec)| {
Also, please make this more Rusty: instead of excluding the `None` case by returning early and later calling  `unwrap()`, use pattern matching. In case of this particular piece of code, I'd recommend such a refactor:
```rust
col_specs
    .and_then(|col_specs| col_specs
        .iter()
        .enumerate()
        .find(|(_, spec)| {
            is_case_sensitive && spec.name == name_str
                || !is_case_sensitive && spec.name.eq_ignore_ascii_case(name_str)
        })
        .map(|(index, _)| {
            if let Some(value) = row_from_raw.columns.get(index) {
                value as *const CassValue
            } else {
                std::ptr::null()
            }
        }))
    .unwrap_or(std::ptr::null())
```

2023-06-01 13:23 UTC, wprzytula commented on scylla-rust-wrapper/src/query_result.rs
>      }
Is the error relevant for the case of `None` `col_specs`? What does it mean that `col_specs` are `None`?

2023-06-01 13:23 UTC, wprzytula commented on scylla-rust-wrapper/src/query_result.rs
> +    let column_spec: &ColumnSpec = col_specs.unwrap().get(index_usize).unwrap();
Please harden this by avoiding `unwrap()`ping:
```rust
let col_specs = if let Some(specs) = result_from_raw.result.column_specs() {
    specs
} else {
    return CassError::SOME_ERROR;
};
// use `col_specs` without need to `unwrap()`
```

2023-06-01 13:23 UTC, wprzytula commented on scylla-rust-wrapper/src/query_result.rs
> +        None => 0,
Or, more consisely:
```rust
result.result.rows_num().as_ref().copied().unwrap_or(0) as size_t
```

2023-06-01 13:23 UTC, wprzytula commented on scylla-rust-wrapper/src/argconv.rs
Ad 72e8da9a931cd29952472c3b37d5a351e47a6385:
in commit message: `means to stores` -> `means to store`

2023-06-01 13:23 UTC, wprzytula commented on scylla-rust-wrapper/src/argconv.rs
> +}
Naming: either rename this macro to `unwrap_or_return_false`, or make it accept the return value in the second parameter (i.e. make its parameter list look like this: `( $e:expr, $retval:expr )`

2023-06-01 13:23 UTC, wprzytula commented on scylla-rust-wrapper/src/query_result.rs
> +        // Errors are ignored, but logging them may come handy in the future.
come handy -> come in handy

2023-06-01 13:23 UTC, wprzytula commented on scylla-rust-wrapper/src/query_result.rs
> +            let is_null = frame_slice.is_none() || raw_col.slice.unwrap().is_empty();
You can avoid `unwrap()` with:
```rust
let is_null = frame_slice.map_or(true, |f| f.is_empty());
```

2023-06-01 13:23 UTC, wprzytula commented on scylla-rust-wrapper/src/query_result.rs
> +    match iter {
This change seems to be a logical no-op (which is good, because otherwise it would be suspicious): the type inferred in the previous version was `&mut CassIterator` anyway, so the `mut` and `match &mut` were simply redundant.

2023-06-01 13:23 UTC, wprzytula commented on scylla-rust-wrapper/src/query_result.rs
> +    match iter {
(this is just for other reviewers to clarify)

2023-06-01 13:23 UTC, wprzytula commented on scylla-rust-wrapper/src/query_result.rs
> +                _ => false as cass_bool_t,
The `+ 1` has been removed in this commit, so I believe its addition in a previous commit was a bug.

2023-06-01 13:23 UTC, wprzytula commented on scylla-rust-wrapper/src/session.rs
> +    decode_first_row(Arc::as_ptr(&cass_result) as *mut CassResult);
Using `get_mut()` here would be arguably safer, and it would convey the intention better:
```rust
decode_first_row(Arc::get_mut(&mut cass_result).unwrap());
```

2023-06-01 13:23 UTC, wprzytula commented on scylla-rust-wrapper/src/session.rs
> +        let is_null = frame_slice.is_none() || raw_col.slice.unwrap().is_empty();
ditto: use `map_or()`

2023-06-01 13:23 UTC, wprzytula commented on scylla-rust-wrapper/src/query_result.rs
> +    ColumnType::BigInt // or `Counter` types can be deserialized as i64 in Rust driver
Can you elaborate on this comment?
Do you mean that both `BigInt` and `Counter` can be deserialized as `i64`?
If so, you could probably mention `Timestamp` and `Time` as well, as I can see them above in the pattern.

2023-06-01 13:23 UTC, wprzytula commented on scylla-rust-wrapper/src/query_result.rs
> +    }
Shorter:
```rust
value.as_ref().map_or(true, |val| val.is_null) as cass_bool_t
```

2023-06-01 13:23 UTC, wprzytula commented on scylla-rust-wrapper/src/future.rs
> +                let _ = &wrapped_cass_fut;
Interesting change! @Lorak-mmk @piodul @havaker @cvybhu

2023-06-01 13:23 UTC, wprzytula commented on scylla-rust-wrapper/src/query_result.rs
> +            }
Unnecessary `mut`. You can take advantage of Rust's amazing block evaluation:
```rust
  let count = if let (Some(frame), true) = (frame_slice, value_type.is_collection()) {
      let mut mem = frame.as_slice();
      unwrap_or_return!(types::read_int_length(&mut mem))
  } else {
      0
  };
```

2023-06-01 13:23 UTC, wprzytula commented on scylla-rust-wrapper/src/query_result.rs
> +        _ => std::ptr::null(), // null is returned if value in iterator is not set
Please avoid `unwrap()`s:
```rust
match iter {
    CassIterator::CassCollectionIterator(CassCollectionIterator { value: Some(value), .. }) => value,
    CassIterator::CassTupleIterator(CassTupleIterator { value: Some(value), .. }) => value,
    _ => std::ptr::null(), // null is returned if value in iterator is not set
}
```

2023-06-01 13:23 UTC, wprzytula commented on scylla-rust-wrapper/src/query_result.rs
> +            map_iterator.key.as_ref().unwrap()
Why is this `unwrap()` safe? Write in a comment.

2023-06-01 13:23 UTC, wprzytula commented on scylla-rust-wrapper/src/query_result.rs
> +            map_iterator.value.as_ref().unwrap()
ditto: justify `unwrap()`.

2023-06-01 13:23 UTC, wprzytula commented on scylla-rust-wrapper/src/query_result.rs
> +                udt_iterator.field_name.as_ref().unwrap().as_str(),
ditto: justify `unwrap()`.

2023-06-01 13:23 UTC, wprzytula commented on scylla-rust-wrapper/src/query_result.rs
> +                udt_iterator.field_name.as_ref().unwrap().as_str(),
Cleaner:
```rust
match iter {
    CassIterator::CassUdtIterator(CassUdtIterator { field_name: Some(field_name), count, position, ..}) => {
        assert!(position
            .map(|pos| pos < *count)
            .is_some()); // assertion copied from c++ driver
        write_str_to_c(
            field_name.as_str(),
            name,
            name_length,
        );
        CassError::CASS_OK
    }
    _ => CassError::CASS_ERROR_LIB_BAD_PARAMS,
}
```

2023-06-01 13:23 UTC, wprzytula commented on scylla-rust-wrapper/src/query_result.rs
> +            udt_iterator.field_value.as_ref().unwrap()
Please refactor this analogously to my suggestion for `cass_iterator_get_user_type_field_name()` (avoiding `unwrap()`s).

2023-06-01 13:23 UTC, wprzytula commented on scylla-rust-wrapper/src/session.rs
> +        }
Unnecessary `mut`.

2023-06-01 13:23 UTC, wprzytula commented on scylla-rust-wrapper/src/cass_types.rs
> +
This panic may unwind into caller C code, which means UB. What is our policy in this regard? @Lorak-mmk @piodul

2023-06-01 13:23 UTC, wprzytula commented on scylla-rust-wrapper/src/query_result.rs
> +                    // first [decode_first_row] call already initialized the columns vec
panic as, first -> panic, as first

2023-06-01 13:23 UTC, wprzytula commented on scylla-rust-wrapper/src/query_result.rs
> +    let is_null = frame_slice.is_none() || raw_value.slice.unwrap().is_empty();
Please avoid `unwrap()` here.

2023-06-01 13:23 UTC, wprzytula commented on scylla-rust-wrapper/src/query_result.rs
> +            false as cass_bool_t
`false` being after an `if` suggests that this is the default path.
Instead, I suggest:
```rust
if new_pos < map_iterator.count {
    let raw_value = map_iterator.map_iterator.next().unwrap();
    if let Ok((raw_key, raw_value)) = raw_value {
        let key_type = raw_key.spec;
        let key = decode_value(raw_key, key_type);
        let value_type = raw_value.spec;
        let value = decode_value(raw_value, value_type);
        map_iterator.key = key;
        map_iterator.value = value;

        true
    }
} else {
  false
}  as cass_bool_t
```

2023-06-01 13:23 UTC, wprzytula commented on scylla-rust-wrapper/src/query_result.rs
> +            false as cass_bool_t
ditto (`false` after `if`)

2023-06-01 13:23 UTC, wprzytula commented on scylla-rust-wrapper/src/query_result.rs
> +            SequenceIterator::new(column_type, item_count, tuple.frame_slice.unwrap()); // safe to unwrap as is_null is false
I'm unhappy with all these `unwrap()`s. Perhaps we can do that another way?

2023-06-01 13:23 UTC, wprzytula commented on scylla-rust-wrapper/src/query_result.rs
>          let iterator = CassUdtIterator {
ditto

2023-06-01 13:23 UTC, wprzytula commented on scylla-rust-wrapper/src/session.rs
>      }
This is a great use case for `if let`:
```
if let Some(value) = cass_value {
    result.first_row.as_mut().unwrap().columns.push(value);
} else {
    return false;
}
```

2023-06-01 13:23 UTC, wprzytula commented on scylla-rust-wrapper/src/query_result.rs
> +                }
It's unclear to me why `pos` is taken modulo 2.

2023-06-01 13:23 UTC, wprzytula commented on scylla-rust-wrapper/src/binding.rs
> -
What about `custom`? The TODO was removed but this case is probably not solved.

2023-06-01 13:44 UTC, wprzytula requested changes
A general idea to make the logic more type-safe (which Rust promotes):
replace groups of `Option`s with custom types that encode the logic inside themselves (their names, variants, etc.). E.g. in case of `CassResultIterator`, `position` is `None` iff `row` is `None`. This dependency could be represented as an enum:

```rust
pub struct CassResultIterator {
    result: Arc<CassResult>,
    curr_row_info: CassResultIteratorCurrentRowInfo,
}

enum CassResultIteratorCurrentRowInfo {
    NoRows,
    Rows {
        current_row: CassRow,
        position: usize,
    }
}

```

2023-06-01 13:44 UTC, wprzytula commented on scylla-rust-wrapper/src/query_result.rs
>          }
Alternatively:
```rust
match result_iterator.result.result.rows_num() {
  Some(rs) if new_pos < rs => {
      decode_next_row(result_iterator.result.as_ref(), &mut result_iterator.row)
  }
  _ => false ,
} as cass_bool_t

2023-06-06 12:47 UTC, Gor027 commented on scylla-rust-wrapper/src/cass_error.rs
> +    fn from(error: &ParseError) -> Self {
Yes. See `From` impl for `RowsError` and `FirstRowError`.

2023-06-06 12:47 UTC, Gor027 commented on scylla-rust-wrapper/src/cass_error.rs
>          self.to_string()
The mapping of the Rust driver errors to the `CassError` enum values is not so obvious, and some of the mappings are not even correct (e.g. `TimeoutError => CassError::CASS_ERROR_LAST_ENTRY`). Having said that the msg trait may be helpful in the future for modifying certain error messages. I guess the trait was introduced with that intuition, too. I would not change it in this PR, maybe better to leave it for now.

2023-06-06 12:47 UTC, Gor027 commented on scylla-rust-wrapper/src/future.rs
> +        Ok(CassResultValue::QueryResult(result)) => match result.result.tracing_id() {
Done.

2023-06-06 12:47 UTC, Gor027 commented on scylla-rust-wrapper/src/query_result.rs
> +                Some(rs) => (new_pos + 1 < rs) as cass_bool_t, // TODO: add next row decoding
You are right, fixed it.

2023-06-06 12:47 UTC, Gor027 commented on scylla-rust-wrapper/src/query_result.rs
> +    let result = row_from_raw.result.upgrade().unwrap();
The lifetime of `CassRow` is bound to `CassResult`, so it will be freed only when the `CassResult` is freed. I will add a short comment about that.

2023-06-06 12:47 UTC, Gor027 commented on scylla-rust-wrapper/src/query_result.rs
>      }
The `column_specs()` function may return `None` if "raw" rows of a single query are empty.

2023-06-06 12:47 UTC, Gor027 commented on scylla-rust-wrapper/src/query_result.rs
>          }
I think you will need to wrap the whole match block in `()` to make it work.

2023-06-06 12:47 UTC, Gor027 commented on scylla-rust-wrapper/src/session.rs
> +    decode_first_row(Arc::as_ptr(&cass_result) as *mut CassResult);
Thanks for the hint, fixed it.

2023-06-06 12:47 UTC, Gor027 commented on scylla-rust-wrapper/src/query_result.rs
> +    ColumnType::BigInt // or `Counter` types can be deserialized as i64 in Rust driver
Yes, both can be deserialized as `i64` in the Rust driver, but `Timestamp` and `Time` deserialization as `i64` is not implemented.

2023-06-06 12:47 UTC, Gor027 commented on scylla-rust-wrapper/src/query_result.rs
> +            map_iterator.key.as_ref().unwrap()
If `cass_iterator_next` succeeded it is safe to unwrap, it is wrapped in an `Option` for safe initialization purposes.

2023-06-06 12:47 UTC, Gor027 commented on scylla-rust-wrapper/src/query_result.rs
> +            map_iterator.value.as_ref().unwrap()
If `cass_iterator_next` succeeded it is safe to unwrap, it is wrapped in an `Option` for safe initialization purposes.

2023-06-06 12:47 UTC, Gor027 commented on scylla-rust-wrapper/src/query_result.rs
> +                udt_iterator.field_name.as_ref().unwrap().as_str(),
Done.

2023-06-06 12:47 UTC, Gor027 commented on scylla-rust-wrapper/src/query_result.rs
> +            udt_iterator.field_value.as_ref().unwrap()
Done.

2023-06-06 12:47 UTC, Gor027 commented on scylla-rust-wrapper/src/query_result.rs
> +            false as cass_bool_t
I think the whole if-else block should be wrapped in `()` in order to make the casting work.

2023-06-06 12:47 UTC, Gor027 commented on scylla-rust-wrapper/src/query_result.rs
> +                }
I did not notice I check the same condition in the else branch. It is fixed now. If you iterate sequentially over a map, an even position means you will get a key and an odd position means you will get a value:
```
0   | 1     | 2   |....
key | value | key | ....
```

2023-06-06 12:47 UTC, Gor027 commented on scylla-rust-wrapper/src/binding.rs
> -
As it is not implemented in the Rust driver (not even in ScyllaDB?), I have reverted the TODO comment.

2023-06-06 13:15 UTC, Gor027 commented on scylla-rust-wrapper/src/session.rs
> +    decode_first_row(Arc::as_ptr(&cass_result) as *mut CassResult);
I did not carefully read the documentation of `get_mut` which returns `None` in case there are `Weak` pointers to the same allocation which is the case here. Reverted back to `Arc::as_ptr()`.

2023-06-12 05:41 UTC, wprzytula commented on scylla-rust-wrapper/src/query_result.rs
> +            }
Or even (which can be a bit surprising):
```rust
 let count;
if let (Some(frame), true) = (frame_slice, value_type.is_collection()) {
      let mut mem = frame.as_slice();
      count = unwrap_or_return!(types::read_int_length(&mut mem));
  } else {
      count = 0;
  };
```

2023-06-12 05:42 UTC, wprzytula commented on scylla-rust-wrapper/src/query_result.rs
> +            }
I prefer the first option, though.

2023-06-12 05:44 UTC, wprzytula commented on scylla-rust-wrapper/src/query_result.rs
>          }
What do you mean? What is an error that you get?

2023-06-12 09:47 UTC, Gor027 commented on scylla-rust-wrapper/src/query_result.rs
>          }
The alternative that you suggested is not a valid expression until you wrap it into parenthesis or add an explicit `return`:

```
(match result_iterator.result.result.rows_num() {
  Some(rs) if new_pos < rs => {
      decode_next_row(result_iterator.result.as_ref(), &mut result_iterator.row)
  }
  _ => false ,
}) as cass_bool_t
```
or,
```
return match result_iterator.result.result.rows_num() {
  Some(rs) if new_pos < rs => {
      decode_next_row(result_iterator.result.as_ref(), &mut result_iterator.row)
  }
  _ => false ,
} as cass_bool_t;
```

2023-06-20 16:12 UTC, Gor027 commented
@wprzytula @Lorak-mmk Ping for review.

2023-06-22 11:30 UTC, wprzytula commented on scylla-rust-wrapper/src/cass_types.rs
> +
ping @Lorak-mmk @piodul

2023-06-22 11:30 UTC, wprzytula commented on scylla-rust-wrapper/src/query_result.rs
> +            };
This would be tidier if both returns were on the same level:
```rust
return match &result_iterator.row {
    Some(row) if iter_position < rows_count => row,
    _ => std::ptr::null(),
};
```

2023-06-22 11:30 UTC, wprzytula commented on scylla-rust-wrapper/src/cass_types.rs
> +
Isn't it the case that we should use `panic='abort'` ?

2023-06-22 13:56 UTC, Gor027 commented
> A general idea to make the logic more type-safe (which Rust promotes): replace groups of `Option`s with custom types that encode the logic inside themselves (their names, variants, etc.). E.g. in case of `CassResultIterator`, `position` is `None` iff `row` is `None`. This dependency could be represented as an enum:
> 
> ```rust
> pub struct CassResultIterator {
>     result: Arc<CassResult>,
>     curr_row_info: CassResultIteratorCurrentRowInfo,
> }
> 
> enum CassResultIteratorCurrentRowInfo {
>     NoRows,
>     Rows {
>         current_row: CassRow,
>         position: usize,
>     }
> }
> ```

I like the idea to express the state of the fields of iterators through enums, but that will make this PR a lot more complicated. Do you mind doing this refactor in another PR? I will open an issue to not forget it.

2023-06-22 14:10 UTC, wprzytula commented
> > A general idea to make the logic more type-safe (which Rust promotes): replace groups of `Option`s with custom types that encode the logic inside themselves (their names, variants, etc.). E.g. in case of `CassResultIterator`, `position` is `None` iff `row` is `None`. This dependency could be represented as an enum:
> > ```rust
> > pub struct CassResultIterator {
> >     result: Arc<CassResult>,
> >     curr_row_info: CassResultIteratorCurrentRowInfo,
> > }
> > 
> > enum CassResultIteratorCurrentRowInfo {
> >     NoRows,
> >     Rows {
> >         current_row: CassRow,
> >         position: usize,
> >     }
> > }
> > ```
> 
> I like the idea to express the state of the fields of iterators through enums, but that will make this PR a lot more complicated. Do you mind doing this refactor in another PR? I will open an issue to not forget it.

I'd prefer to have the refactor done in this PR. You can put it in a separate commit.

2023-06-25 22:31 UTC, Gor027 commented on scylla-rust-wrapper/src/query_result.rs
> +            };
Done.

2023-06-25 22:37 UTC, Gor027 commented
> A general idea to make the logic more type-safe (which Rust promotes): replace groups of `Option`s with custom types that encode the logic inside themselves (their names, variants, etc.). E.g. in case of `CassResultIterator`, `position` is `None` iff `row` is `None`. This dependency could be represented as an enum:
> 
> ```rust
> pub struct CassResultIterator {
>     result: Arc<CassResult>,
>     curr_row_info: CassResultIteratorCurrentRowInfo,
> }
> 
> enum CassResultIteratorCurrentRowInfo {
>     NoRows,
>     Rows {
>         current_row: CassRow,
>         position: usize,
>     }
> }
> ```

I have applied the idea in separate commits. Perhaps this approach is more expressive and makes it easy to understand the iterator's state, although it looks overhead to me.

2023-06-27 11:31 UTC, wprzytula reviewed
I'm very happy to see the enum-based iterator states. This is much more readable than combinations of `Option`s.

2023-06-27 11:31 UTC, wprzytula commented on scylla-rust-wrapper/src/query_result.rs
> +}
The semantics is unclear: Neither do names of the variants describe the semantics, nor are there any comments with such explanation.

2023-06-27 11:31 UTC, wprzytula commented on scylla-rust-wrapper/src/query_result.rs
> +
What about making this a method and simply mutate instead of returning?

2023-06-27 11:31 UTC, wprzytula commented on scylla-rust-wrapper/src/query_result.rs
> +
```suggestion
impl<T> CassIteratorStateInfo<T> {
    /// Update iterator's state and return new state info.
    /// Increments an existing position, otherwise sets it to 0.
    fn advance(
        &mut self,
    ) {
        // Store a dummy NoValue temporarily as we cannot move out StateInfo fields.
        let old_state_info = std::mem::replace(self, CassIteratorStateInfo::NoValue);
        *self = match old_state_info {
            CassIteratorStateInfo::Value { value, position } => CassIteratorStateInfo::Value {
                value,
                position: position + 1,
            },
            CassIteratorStateInfo::PositionNoValue { position } => {
                CassIteratorStateInfo::PositionNoValue {
                    position: position + 1,
                }
            }
            CassIteratorStateInfo::ValueNoPosition { value } => {
                CassIteratorStateInfo::Value { value, position: 0 }
            }
            CassIteratorStateInfo::NoValue => CassIteratorStateInfo::PositionNoValue { position: 0 },
        };
    }
}


```

2023-06-27 11:31 UTC, wprzytula commented on scylla-rust-wrapper/src/query_result.rs
> +
Then using it is as simple as
```rust
result_iterator.state_info.advance();
```

2023-06-27 11:31 UTC, wprzytula commented on scylla-rust-wrapper/src/query_result.rs
> +}
The question is: what behaviour do these states represent? What properties are represented by such?

2023-06-27 11:57 UTC, Gor027 commented on scylla-rust-wrapper/src/query_result.rs
> +
Applied the suggestion.

2023-06-27 12:02 UTC, wprzytula commented on scylla-rust-wrapper/src/query_result.rs
> +}
Perhaps this is obvious provided one knows the inner working of Cpp driver. I believe, however, that we should strive towards having bindings' code documented well enough so that this becomes unnecessary. After all, nobody really wants to peruse its code.

2023-06-27 12:11 UTC, Gor027 commented on scylla-rust-wrapper/src/query_result.rs
> +}
The enum is supposed to represent the state of two optional variables: position and value. Let me explain the details and feel free to suggest better naming for the variants.
{NoValue, ValueNoPosition}: The iterator may be created empty (without a value and a position) or with an initial value, e.g. `RowIterator`.
{PositionNoValue, Value}: A call to `cass_iterator_next` will first increment the position or initialize it to 0 while the value may not be present yet. The first call to `cass_iterator_next` is supposed to make the state "complete", with present value and position.

2023-06-27 12:15 UTC, Gor027 commented on scylla-rust-wrapper/src/query_result.rs
> +}
Maybe it is better to distinguish the case when the position exists and the value is not and in that case `advance()` should fail (maybe panic as the value cannot be retrieved from the iterator on a certain position).

2023-06-27 16:54 UTC, Gor027 commented on scylla-rust-wrapper/src/query_result.rs
> +}
Fixed it.

2023-06-27 17:09 UTC, wprzytula commented on scylla-rust-wrapper/src/query_result.rs
> +                panic!("Cannot advance the iterator. Value is empty!")
Are we even allowed to panic in bindings? I still haven't got any answer from @piodul and @Lorak-mmk, and I believe that letting an unwinding panic cross the C/Rust boundary is awful UB. IIUC, we are only allowed to panic if we call `catch_unwind()` on any path from bindings' entrypoint to any panic.

2023-06-27 17:11 UTC, wprzytula commented on scylla-rust-wrapper/src/query_result.rs
> +                        return true as cass_bool_t;
Isn't the first `return` redundant?

2023-06-27 17:20 UTC, Gor027 commented on scylla-rust-wrapper/src/query_result.rs
> +                        return true as cass_bool_t;
Good catch! When `if let` evaluates to false, we still return true which is wrong.

2023-06-27 17:30 UTC, wprzytula commented on scylla-rust-wrapper/src/query_result.rs
>                  false as cass_bool_t
As there are a lot of nested `if let`s, please take use of `else` for each.

2023-06-27 17:31 UTC, wprzytula commented on scylla-rust-wrapper/src/query_result.rs
>              false as cass_bool_t
ditto

2023-06-27 17:31 UTC, Gor027 commented on scylla-rust-wrapper/src/query_result.rs
> +                panic!("Cannot advance the iterator. Value is empty!")
Basically, we use aborting panics in bindings, those are not unwinding panics and hence cannot be even caught by `catch_unwind` if I am not mistaken.

2023-06-27 17:34 UTC, wprzytula commented on scylla-rust-wrapper/src/query_result.rs
> +                panic!("Cannot advance the iterator. Value is empty!")
I can't find any code that would turn panics into aborting. Can you?

2023-06-27 17:37 UTC, Gor027 commented on scylla-rust-wrapper/src/query_result.rs
>                  false as cass_bool_t
I think that will add a lot of redundant true/false. The current version is simpler. WDYT?

2023-06-27 17:41 UTC, Gor027 commented on scylla-rust-wrapper/src/query_result.rs
> +                panic!("Cannot advance the iterator. Value is empty!")
For example, `cass_types:244` where for a wrong match arm Rust will stop the execution and refuse to continue.

2023-06-27 17:42 UTC, wprzytula commented on .github/workflows/cassandra.yml
>  :SslTests.Integration_Cassandra_ReconnectAfterClusterCrashAndRestart\
Why are these enabled now? (IIUC)

2023-06-27 17:45 UTC, wprzytula commented on scylla-rust-wrapper/src/query_result.rs
> +                panic!("Cannot advance the iterator. Value is empty!")
Hmm, how can I know that such behaviour occur?
Moreover, aborting on unrecognized pattern is something completely different that aborting on explicit panic. Isn't it?

2023-06-27 17:47 UTC, Gor027 commented on .github/workflows/cassandra.yml
>  :SslTests.Integration_Cassandra_ReconnectAfterClusterCrashAndRestart\
Cause lazy deserialization allows to append, bind and get decimal, duration and raw bytes from the value. These tests were disabled cause appropriate functions were not implemented (and could not have been properly implemented before lazy deserialization).

2023-06-27 17:48 UTC, wprzytula commented on scylla-rust-wrapper/src/query_result.rs
> +                        return true as cass_bool_t;
So the `if let` at `336` should return `true` if `raw_value` is `Err` ? I really can't grasp it. Perhaps more comments could explain these `if`s better.

2023-06-27 17:55 UTC, Gor027 commented on scylla-rust-wrapper/src/query_result.rs
> +                        return true as cass_bool_t;
No, you are right it should not return true.

2023-06-27 17:56 UTC, wprzytula commented on scylla-rust-wrapper/src/query_result.rs
> +                        return true as cass_bool_t;
Then please, add explicit `else`s, even if they seen redundant. And comments explaining why so.

2023-06-27 17:58 UTC, Gor027 commented on scylla-rust-wrapper/src/query_result.rs
> +                        return true as cass_bool_t;
Sequential iteration over a map was a tricky case, as the Rust driver deserializes in pairs and while iterating only on even positions (key, value) should be deserialized. Fixed it.

2023-06-27 18:00 UTC, wprzytula requested changes
Looking at the maze of `if`s, I'm convinced that a set of unit tests for deserialization is absolutely required.

2023-06-27 18:10 UTC, wprzytula commented on scylla-rust-wrapper/src/query_result.rs
> +                false as cass_bool_t
Last idea to make it clearer for the future readers, and I won't push this anymore: for every return (either true or false), explain shortly why it is that value.

2023-06-27 19:46 UTC, Gor027 commented on scylla-rust-wrapper/src/query_result.rs
> +                false as cass_bool_t
I applied this suggestion. Hope it is clearer now.

2023-06-28 05:17 UTC, wprzytula commented on scylla-rust-wrapper/src/query_result.rs
> +            }
This looks good now!

2023-06-29 15:27 UTC, Gor027 commented
> Looking at the maze of `if`s, I'm convinced that a set of unit tests for deserialization is absolutely required.

I added some relevant tests for collection iterators as Cassandra tests may not cover everything.

2023-06-29 15:43 UTC, wprzytula commented on scylla-rust-wrapper/src/query_result.rs
> +            );
This code shows the problem we discussed before: as `CassSequenceIterator` requires `'static` lifetime out the held references, the lifetime of the `&Bytes` reference must by extended to `'static` in a hacky way (by casting it to pointer and back again).
The solution is to make the iterators parametrised by a lifetime.

2023-06-29 15:43 UTC, wprzytula commented on scylla-rust-wrapper/src/query_result.rs
> +            assert!(has_next.is_zero());
Wouldn't `assert_eq!(has_next, 0)` fit better here?

2023-06-29 15:43 UTC, wprzytula commented on scylla-rust-wrapper/src/query_result.rs
> +            bytes_mut.put(true_bytes);
Is such by-hand crafting necessary? Couldn't we use our serialisation framework to create deserialisation tests by asserting identity of the types fed and got back?

2023-06-29 15:43 UTC, wprzytula commented on scylla-rust-wrapper/src/query_result.rs
> +            }
Is this `if let` condition going to ever not be satisfied? If not, please add `else` branch with explicit `unreachable!()`.

2023-06-29 15:54 UTC, Gor027 commented on scylla-rust-wrapper/src/query_result.rs
> +            }
Done.

2023-06-29 15:55 UTC, Gor027 commented on scylla-rust-wrapper/src/query_result.rs
> +            bytes_mut.put(true_bytes);
It would require adding `scylla-cql` in dependencies, I do not want to add it for a couple of serialization purposes.

2023-06-29 15:55 UTC, Gor027 commented on scylla-rust-wrapper/src/query_result.rs
> +            assert!(has_next.is_zero());
Done.

2023-06-29 15:56 UTC, Gor027 commented on scylla-rust-wrapper/src/query_result.rs
> +            );
Let's create an issue out of it to not forget #119

2023-06-29 15:58 UTC, wprzytula commented on scylla-rust-wrapper/src/query_result.rs
> +            bytes_mut.put(true_bytes);
Rust driver already has `scylla-cql` as dependency, so I believe this shouldn't hurt us. @piodul Can you confirm that? Will Cargo be intelligent enough to compile `scylla-cql ` only once?

2023-06-29 16:03 UTC, piodul commented on scylla-rust-wrapper/src/query_result.rs
> +            bytes_mut.put(true_bytes);
Yes, provided that we use the same version of `scylla-cql` as the driver uses.

2023-06-29 16:08 UTC, wprzytula commented on scylla-rust-wrapper/src/query_result.rs
> +            bytes_mut.put(true_bytes);
Then I insist on using scylla-cql for aid here.

2023-06-30 09:18 UTC, Gor027 commented on scylla-rust-wrapper/src/query_result.rs
> +            bytes_mut.put(true_bytes);
@piodul Are we sure that the following way of serializing and deserializing should always work for all types:
```rust
// Serialize
let mut bytes = Vec::new();
let mut map = HashMap::new()
map.insert("key", "value");
map.serialize(&mut bytes);
let frame_slice = FrameSlice::new(bytes);
// Deserialize
let column_type = ColumnType::Map(Box::new(ColumnType::Text), Box::new(ColumnType::Text));
let (key, value) = MapIterator::deserialize(column_type, frame_slice).unwrap().next().unwrap();

assert_eq!(key, "key");
assert_eq!(value, "value");
```
This is a pseudocode example so it may not compile.

2023-06-30 09:52 UTC, piodul commented on scylla-rust-wrapper/src/query_result.rs
> +            bytes_mut.put(true_bytes);
Yes, I think it should work. By the way, the impls for the `Value` trait are in `scylla-cql/src/frame/value.rs`, looks like they do the same thing.

2023-06-30 10:24 UTC, Gor027 commented on scylla-rust-wrapper/src/query_result.rs
> +            bytes_mut.put(true_bytes);
Ok, what was missing is that before the serialized value the buffer contains also the number of bytes of it, but the deserialization API expects a frame slice without the number of bytes in the beginning.

2024-01-02 23:33 UTC, Lorak-mmk commented
I think we can safely close this.

2024-01-12 15:53 UTC, Lorak-mmk commented
Oops, wrong PR

2024-04-29 13:06 UTC, Lorak-mmk commented
After all I think we can close this - applying new deserialization to cpp-rust-driver will require at least some changes to this PR, so it will have to be done by someone else.

2024-04-29 13:06 UTC, closed without merging