Improved error handling
scylladb/cpp-rs-driver pull request #12
Opened 2021-10-22 19:12 UTC by Lorak-mmk

Changed CassError to be enum
Implemented some error-checking instead of unwrapping.
Template implementation of error conversion - now we need to actually create correct mappings.
Implemented functions related to CassErrorResult

2021-10-22 22:20 UTC, constantfold commented on scylla-rust-wrapper/src/cass_error.rs
> +pub enum CassError {
Shouldn't we specify the size of CassError explicitly (that it's `c_uint`)?

2021-10-22 23:21 UTC, constantfold commented on scylla-rust-wrapper/src/cass_error.rs
> +pub enum CassError {
Something like this? `#[repr(C, c_uint)]`

2021-10-23 10:10 UTC, Lorak-mmk commented on scylla-rust-wrapper/src/cass_error.rs
> +pub enum CassError {
I dont't think you can set 2 reprs on one enum. I can change it to `#[repr(u32)]`, but I think that `#[repr(C)]` is better - it will use best-guess representation of the same enum in C.

2021-10-23 11:21 UTC, constantfold commented on scylla-rust-wrapper/src/cass_error.rs
> +pub enum CassError {
That’s correct - I was under false assumption that CassError was not an enum in the C header file.

2021-10-23 11:35 UTC, constantfold commented on scylla-rust-wrapper/src/future.rs
> +            *message = s.as_str().as_ptr() as *const i8;
What’s the guarantee that s won’t be deallocated after this function returns?

2021-10-23 11:41 UTC, Lorak-mmk commented on scylla-rust-wrapper/src/future.rs
> +            *message = s.as_str().as_ptr() as *const i8;
As far as I can see, the same as in original cpp-driver: `s` lives as long as the future.
```C
void cass_future_error_message(CassFuture* future, const char** message, size_t* message_length) {
  const Future::Error* error = future->error();
  if (error != NULL) {
    const String& m = error->message;
    *message = m.data();
    *message_length = m.length();
  } else {
    *message = "";
    *message_length = 0;
  }
}
```

2021-10-25 13:26 UTC, piodul requested changes

2021-10-25 13:26 UTC, piodul commented on scylla-rust-wrapper/src/cass_error.rs
> +            } => CassError::SERVER_UNAVAILABLE,
You don't have to specify all those fields, the following should suffice:

```rust
DbError::Unavailable { .. } => CassError::SERVER_UNAVAILABLE,
```

2021-10-25 13:26 UTC, piodul commented on scylla-rust-wrapper/src/cass_error.rs
> +            DbError::Other(num) => unsafe { mem::transmute(*num) },
I know we are generally using unsafe, but I think that using transmute here is too much. I think that we should either:

1. drop precise information about the error and use an existing variant in its place (e.g. `SERVER_SERVER_ERROR`),
1. or introduce corresponding `Other(i32)` variant in the `CassError` enum - and maybe implement `Into<c_int>` etc. and use it every time we return the error.

2021-10-25 13:26 UTC, piodul commented on scylla-rust-wrapper/src/argconv.rs
> +}
A tiny nitpick: I think it would be better if you specify a lifetime explicitly here, like this:

```rust
pub unsafe fn write_str_to_c<'a>(s: &'a str, c_str: *mut *const c_char, c_strlen: *mut size_t) {
    *c_str = s.as_ptr() as *const i8;
    *c_strlen = s.len() as u64;
}
```

It will allow using this function with string slices with temporary lifetime (which is what we do, but we also give them `'static` lifetime, which is something that we might try to fix in the future)

2021-10-25 15:36 UTC, piodul approved these changes

2021-10-25 15:37 UTC, merged