types: Implement API functions for `duration` type
scylladb/cpp-rs-driver pull request #135
Opened 2024-07-02 18:51 UTC by muzarski

This PR implements following set of API functions related to `duration` type:
- cass_statement_bind_duration_*
- cass_user_type_set_duration_*
- cass_tuple_set_duration
- cass_value_get_duration
- cass_value_is_duration
- cass_collection_append_duration

## Pre-review checklist

- [x] I have split my patch into logically separate commits.
- [x] All commit messages clearly explain what they change and why.
- [x] PR description sums up the changes and reasons why they should be introduced.
- [ ] I have enabled appropriate tests in `.github/workflows/build.yml` in `gtest_filter`.
- [ ] I have enabled appropriate tests in `.github/workflows/cassandra.yml` in `gtest_filter`.

2024-07-02 18:53 UTC, muzarski commented
@Lorak-mmk @wprzytula Do you know how to enable the tests for the duration type? I see there is a `tests/src/integration/values/duration.hpp` file but I'm not sure how to enable it in CI.

2024-07-02 19:08 UTC, muzarski commented
> @Lorak-mmk @wprzytula Do you know how to enable the tests for the duration type? I see there is a `tests/src/integration/values/duration.hpp` file but I'm not sure how to enable it in CI.

I see that the duration tests were run in CI: `12 tests from CassandraTypes/CassandraTypesTests/7, where TypeParam = test::driver::NullableValue<test::driver::values::Duration>`. I'm curious why `Decimal` tests are not being run (decimal is unimplemented type).

2024-07-02 19:51 UTC, Lorak-mmk approved these changes

2024-07-02 20:16 UTC, Lorak-mmk commented
> @Lorak-mmk @wprzytula Do you know how to enable the tests for the duration type? I see there is a `tests/src/integration/values/duration.hpp` file but I'm not sure how to enable it in CI.

To be honest I'm not sure how those tests work. I can see that both duration and decimal have some special handling.
Those tests are defined in `tests/src/integration/tests/test_cassandra_types.cpp`
I can see that there is some specialization for Duration: https://github.com/scylladb/cpp-rust-driver/blob/805ef4c3a3f35e35d9e0736a86e47b2c600c3c4e/tests/src/integration/tests/test_cassandra_types.cpp#L98
And later some registration for types excluding duration: https://github.com/scylladb/cpp-rust-driver/blob/805ef4c3a3f35e35d9e0736a86e47b2c600c3c4e/tests/src/integration/tests/test_cassandra_types.cpp#L884-L891
There is also some instantiation that includes decimal: https://github.com/scylladb/cpp-rust-driver/blob/805ef4c3a3f35e35d9e0736a86e47b2c600c3c4e/tests/src/integration/tests/test_cassandra_types.cpp#L925-L930

2024-07-02 20:18 UTC, Lorak-mmk commented
> > @Lorak-mmk @wprzytula Do you know how to enable the tests for the duration type? I see there is a `tests/src/integration/values/duration.hpp` file but I'm not sure how to enable it in CI.
> 
> I see that the duration tests were run in CI: `12 tests from CassandraTypes/CassandraTypesTests/7, where TypeParam = test::driver::NullableValue<test::driver::values::Duration>`. I'm curious why `Decimal` tests are not being run (decimal is unimplemented type).

Where do you see that? I don't see any occurence of decimal or duration in CI logs.

2024-07-02 22:22 UTC, muzarski commented
> > > @Lorak-mmk @wprzytula Do you know how to enable the tests for the duration type? I see there is a `tests/src/integration/values/duration.hpp` file but I'm not sure how to enable it in CI.
> > 
> > 
> > I see that the duration tests were run in CI: `12 tests from CassandraTypes/CassandraTypesTests/7, where TypeParam = test::driver::NullableValue<test::driver::values::Duration>`. I'm curious why `Decimal` tests are not being run (decimal is unimplemented type).
> 
> Where do you see that? I don't see any occurence of decimal or duration in CI logs.

build job, step `Run integration tests on Scylla 5.0.0`, line 577

2024-07-02 22:33 UTC, Lorak-mmk commented
I see. Ctrl + f seems to be quite unreliable in those logs...

2024-07-25 13:20 UTC, muzarski commented
v2: rebased on master

2024-07-31 09:01 UTC, wprzytula commented on README.md
> +            <td rowspan="2">Binding is not implemented for custom types in the Rust driver. <br> Binding Decimal type requires encoding raw bytes into BigDecimal type in the Rust driver. <br> <b>Note
> The driver does not validate the types of the values passed to queries.

Is this still true after the driver version was bumped to include the serialization refactor?

2024-07-31 09:01 UTC, wprzytula commented on README.md
> +            <td rowspan="2">Unimplemented because of the same reasons as binding for statements.<br> <b>Note</b>: The driver does not check whether the type of the appended value is compatible with t
Why can we decrement the span?

2024-07-31 09:01 UTC, wprzytula commented on scylla-rust-wrapper/src/binding.rs
>  // decimal
Let's remove the question mark. Custom types are not supported in Rust driver, and are not planned to be supported in the future.

2024-07-31 09:01 UTC, wprzytula commented on scylla-rust-wrapper/src/query_result.rs
> +
`cass_value_get_bytes()` additionally checks if the pointer is NULL, and returns an error in such case. Please double check that cpp-driver does it not for `cass_value_get_duration`, too, and gain insight why it does so for `bytes`.

2024-07-31 09:01 UTC, wprzytula commented on scylla-rust-wrapper/src/query_result.rs
> +}
Shouldn't we rather use a consise `matches!` macro? I recall that clippy tends to complain about writing the fully-fledged `match` statement in such cases. Probably it's the cast to `cass_bool_t` that keeps it silent here.

2024-07-31 09:01 UTC, wprzytula commented on scylla-rust-wrapper/src/value.rs
> +}
Definitely, let's not copy them!
Let's make `vint_encode` and `vint_decode` public in `scylla_cql`. `cpp-rust-driver` can depend on `scylla-cql` directly, too, and then we don't even have to expose them in `scylla` crate.

2024-07-31 09:01 UTC, wprzytula commented on scylla-rust-wrapper/src/value.rs
> +    let mut buf = Vec::with_capacity(27); // worst case size is 27
Wait, why? This 27 seems like magic to me.

2024-07-31 09:13 UTC, muzarski commented on README.md
> +            <td rowspan="2">Binding is not implemented for custom types in the Rust driver. <br> Binding Decimal type requires encoding raw bytes into BigDecimal type in the Rust driver. <br> <b>Note
It won't be true once we merge: https://github.com/scylladb/cpp-rust-driver/pull/143.

The PR that bumped driver's version implemented a naive serialization (with no typechecks). In cpp-driver, the typechecks are performed during binding, so I decided to implement it in separate PR.

2024-07-31 09:16 UTC, muzarski commented on README.md
> +            <td rowspan="2">Unimplemented because of the same reasons as binding for statements.<br> <b>Note</b>: The driver does not check whether the type of the appended value is compatible with t
Because we removed `cass_collection_append_duration` row:
```
        <tr>
            <td>cass_collection_append_duration</td>
        </tr>
```

This leaves us with just `cass_collection_apend_custom` and `cass_collection_append_decimal` rows.

2024-07-31 09:34 UTC, muzarski commented on scylla-rust-wrapper/src/query_result.rs
> +
The cpp-driver actually does that for all of `cass_value_get_[...]` functions. I'll adjust it in cpp-rust-driver in this PR. To be quite honest, I'm not sure when `CassValue` pointer can be null, but it's better to verify that it's non-null anyway.

2024-07-31 09:44 UTC, wprzytula commented on scylla-rust-wrapper/src/query_result.rs
> +
That's yet another spot in cpp-rust-driver where we are hazardously close to triggering UB. For the next releases, we undoubtedly have to focus on stability and memory safety. Let's start with refactoring the binding framework, as discussed, and then we should probably proceed with thorough and meticulous code inspection to detect potential trouble before it arises in production.

2024-07-31 09:46 UTC, muzarski commented on scylla-rust-wrapper/src/query_result.rs
> +
What's interesting is that other `cass_value_*` functions in cpp-driver do not have that check - e.g. `cass_value_is_null` does not check whether the pointer itself is null.

2024-07-31 09:54 UTC, muzarski commented on scylla-rust-wrapper/src/query_result.rs
> +}
Good thing that you mentioned that! Thanks to that, I realized that the logic itself is not correct. Even if the value is `None`, it can be a duration value (null). We need to check the type, not the value.

The bug is a result of me basing on implementation of `cass_value_is_collection`, which has this bug as well...

2024-07-31 10:05 UTC, muzarski commented on scylla-rust-wrapper/src/value.rs
> +    let mut buf = Vec::with_capacity(27); // worst case size is 27
This is rust driver's code. I'll try to investigate it.

2024-07-31 10:17 UTC, muzarski commented on scylla-rust-wrapper/src/value.rs
> +}
Opened a PR: https://github.com/scylladb/scylla-rust-driver/pull/1047

2024-07-31 10:48 UTC, muzarski commented on scylla-rust-wrapper/src/value.rs
> +    let mut buf = Vec::with_capacity(27); // worst case size is 27
I think I found an explanation. A fragment of `unsigned_vint_encode`:
```rust
    let mut number_of_bytes = (639 - 9 * v.leading_zeros()) >> 6;
```

The maximum value of `number_of_bytes` is 9. (The value is `mut`, but it is only decreased in some cases). We have 3 values (months, days, nanos), 3 x 9 = 27.

2024-07-31 10:54 UTC, wprzytula commented on scylla-rust-wrapper/src/value.rs
> +    let mut buf = Vec::with_capacity(27); // worst case size is 27
Let's put the explanation in the code. It should land in Rust driver's code, too.

2024-07-31 11:14 UTC, piodul commented on scylla-rust-wrapper/src/value.rs
> +    let mut buf = Vec::with_capacity(27); // worst case size is 27
Can't we just invoke `<CqlDuration as SerializeValue>::serialize()` here? Is this necessary to reimplement this in such low level way?

2024-07-31 11:18 UTC, muzarski commented on scylla-rust-wrapper/src/value.rs
> +    let mut buf = Vec::with_capacity(27); // worst case size is 27
We unfortunately can't, since rust-driver does the typechecks in builtin `SerializeValue` implementations. cpp-driver handles typechecks in a very specific way. We should not do the typechecks for elements of an untyped collection (yes, there is such thing in cpp-driver) - users are allowed to bind a value of any type to such collection (thus, the typecheck should not be performed).

2024-07-31 11:30 UTC, piodul commented on scylla-rust-wrapper/src/value.rs
> +    let mut buf = Vec::with_capacity(27); // worst case size is 27
The implementation in scylla-rust-driver indeed performs type checking, but can't we just pass the expected type when serializing? i.e. `my_cql_duration_value.serialize(&CqlType::Duration, writer)`?

2024-07-31 11:37 UTC, muzarski commented on scylla-rust-wrapper/src/value.rs
> +    let mut buf = Vec::with_capacity(27); // worst case size is 27
Hmmm, I like this idea. We could do it for other types excluding udts/collections/tuples as well.

@Lorak-mmk @wprzytula WDYT?

2024-07-31 13:05 UTC, muzarski commented
v3:
- rebased on master
- addressed minor issues
- fixed `cass_value_is_duration` and `cass_value_is_collection`
- making use of rust-driver's builtin serialization for simple types (first commit).

2024-07-31 13:33 UTC, wprzytula requested changes

2024-07-31 13:33 UTC, wprzytula commented on scylla-rust-wrapper/src/value.rs
> +            CassCqlValue::BigInt(v) => {
I'd prefer to have these changes in a separate PR. Refactors should be separate from new features (duration support).

2024-07-31 13:37 UTC, muzarski commented on scylla-rust-wrapper/src/value.rs
> +            CassCqlValue::BigInt(v) => {
Ok, I'll move it. This PR will base on the PR introducing these changes.

2024-07-31 13:46 UTC, muzarski commented on scylla-rust-wrapper/src/value.rs
> +            CassCqlValue::BigInt(v) => {
https://github.com/scylladb/cpp-rust-driver/pull/152

2024-07-31 14:09 UTC, muzarski commented
v3.1: rebased on master

2024-07-31 14:27 UTC, wprzytula approved these changes

2024-08-02 21:01 UTC, Lorak-mmk approved these changes

2024-08-02 21:01 UTC, Lorak-mmk commented on scylla-rust-wrapper/src/value.rs
> +}
Those are no longer required, so I'm marking as resolved

2024-08-02 21:57 UTC, Lorak-mmk commented
One more question: before you mentioned some tests that were incorrectly skipped. Is that fixed now?

2024-08-04 20:28 UTC, muzarski commented
> One more question: before you mentioned some tests that were incorrectly skipped. Is that fixed now?

Yes, there is an issue for that: https://github.com/scylladb/cpp-rust-driver/issues/144. Do you want me to fix it before merging this PR?

2024-08-04 23:17 UTC, Lorak-mmk commented
It can be a separate PR - but I don't want to postpone it too long.

2024-08-04 23:21 UTC, merged