cass_result: implement missing functions
scylladb/cpp-rs-driver pull request #136
Opened 2024-07-03 09:26 UTC by muzarski

Fix: https://github.com/scylladb/cpp-rust-driver/issues/35

Implemented two missing CassResult functions:
- cass_result_column_type
- cass_result_column_data_type

## Pre-review checklist

- [x] I have split my patch into logically separate commits.
- [x] All commit messages clearly explain what they change and why.
- [x] PR description sums up the changes and reasons why they should be introduced.
- ~[ ] I have enabled appropriate tests in `.github/workflows/build.yml` in `gtest_filter`.~
- ~[ ] I have enabled appropriate tests in `.github/workflows/cassandra.yml` in `gtest_filter`.~

2024-07-03 09:31 UTC, mykaul commented
Do we have tests to validate this?

2024-07-03 22:23 UTC, muzarski commented
> Do we have tests to validate this?

At first, I wasn't sure if there are integration tests checking this - unfortunately, the answer is no (previous implementation of `cass_result_first_row` would panic in some cases - this bug was never detected). Tomorrow I'll try to implement some cpp integration tests for the `cass_result_*` API.

2024-07-03 22:28 UTC, muzarski commented
v2: Fixed `cass_result_first_row`

2024-07-04 04:07 UTC, wprzytula commented
> > Do we have tests to validate this?
> 
> At first, I wasn't sure if there are integration tests checking this - unfortunately, the answer is no (previous implementation of `cass_result_first_row` would panic in some cases - this bug was never detected). Tomorrow I'll try to implement some cpp integration tests for the `cass_result_*` API.

WDYT about adding Rust unit tests first? They should be the first layer to detect errors, they have smaller overhead and, probably the most important for convenience of us maintainers, they are written in Rust, not in Datastax C++ test framework.

2024-07-05 16:01 UTC, muzarski commented
v3: implemented unit tests for basic `cass_result_*` API.

2024-07-08 16:43 UTC, wprzytula commented on scylla-rust-wrapper/src/query_result.rs
> +            std::ptr::addr_of_mut!(name_length),
As this is going to be prevalent in cpp-rust-driver code, let's `use std::ptr::addr_of[_mut]`.

2024-07-09 10:15 UTC, wprzytula approved these changes

2024-07-09 10:16 UTC, wprzytula commented
In this PR, you should instantly enable related integration tests and/or examples.

2024-07-10 18:14 UTC, Lorak-mmk requested changes

2024-07-10 18:14 UTC, Lorak-mmk commented on scylla-rust-wrapper/src/session.rs
> +                ));
Allocating this on each execute seems very wasteful.
Can we store it in prepared statement and share an Arc?
What is cpp-driver doing? Does it allocate on each execute or does it share with prepared?

2024-07-10 18:14 UTC, Lorak-mmk commented on scylla-rust-wrapper/src/query_result.rs
> +        .unwrap_or(CassValueType::CASS_VALUE_TYPE_UNKNOWN)
This could call `cass_result_column_data_type` and map non-null using `cass_data_type_type`.
Not sure if it would be better in any way (but it would avoid repetition of argument conversion and accessing col_data_types.

2024-07-10 19:07 UTC, muzarski commented on scylla-rust-wrapper/src/session.rs
> +                ));
Current definition of `Statement` is:
```rust
#[derive(Clone)]
pub enum Statement {
    Simple(SimpleQuery),
    // Arc is needed, because PreparedStatement is passed by reference to session.execute
    Prepared(Arc<PreparedStatement>),
}
```

So it can be either a simple query or prepared statement. In case of simple query, we don't have information about the result column specs.

When it comes to prepared statement, we could use columns specs (but why, when they are provided in `QueryResult`). What about `paging_state` and `tracing_id`? They are not part of prepared statement, but rather a part of result.

The only optimization I can think of is to extend the `Statement::Prepared` variant by an additional field of type `Arc<Vec<Arc<CassDataType>>>` (`CassDataType` wrapped with Arc since it needs to be shared with `CassRow`). It could be then computed during preparation, and passed to `CassResult::col_data_types` upon exeuction (simply copy an `Arc`).

2024-07-11 08:18 UTC, Lorak-mmk commented on scylla-rust-wrapper/src/session.rs
> +                ));
> The only optimization I can think of is to extend the `Statement::Prepared` variant by an additional field of type `Arc<Vec<Arc<CassDataType>>>` (`CassDataType` wrapped with Arc since it needs to be shared with `CassValue`, which resides in `CassRow`). It could be then computed during preparation, and passed to `CassResult::col_data_types` upon exeuction (simply clone an `Arc`).

This is what I had in mind by storing it in prepared statement and sharing an Arc.
Nit: I think it makes more sense to make `CassPrepared` a struct instead of an alias and add the data type there.

I looked briefly at cpp-driver code and I'm pretty sure that this is what it does too.

2024-09-05 11:11 UTC, muzarski commented
This PR is waiting for: https://github.com/scylladb/cpp-rust-driver/pull/143

2024-10-07 13:52 UTC, dkropachev commented
> This PR is waiting for: #143

#143 is in, can you continue working on it ?

2024-10-07 14:09 UTC, muzarski commented
> > This PR is waiting for: #143
> 
> 
> 
> #143 is in, can you continue working on it ? 

Yes

2024-10-07 14:40 UTC, muzarski commented
Rebased on master

2024-10-07 15:33 UTC, muzarski commented
v4:
Now, the result metadata (`Vec<Arc<CassDataType>>`) is stored in `CassPrepared`. It allows us to omit the allocations each time we execute the prepared statement. We don't have to construct each `CassDataType` from scratch (it can be a really costly operation) based on the column specs.

Now, `CassResultData::from_result_payload` accepts an additional argument, which is an optional vector of result column data types. 
- For simple queries, we provide `None` - then `CassDataTypes` are created based on column specs received from the server. 
- For prepared statements, we provide a `Some(<metadata cached in CassPrepared>)` to avoid additional allocations

2024-10-07 15:43 UTC, muzarski commented on scylla-rust-wrapper/src/session.rs
> +                ));
Done

2024-10-08 09:59 UTC, Lorak-mmk commented on scylla-rust-wrapper/src/prepared.rs
>  }
Do I understand correctly: first field is for types of bind variables, second for types of columns returned from query?

2024-10-08 09:59 UTC, Lorak-mmk commented on scylla-rust-wrapper/src/session.rs
> +                let maybe_result_col_data_types = Some(prepared.result_col_data_types.clone());
Why do you store `Vec<Arc<...>>` and clone the vector (which needs an allocation) instead of putting Vec in another Arc?

2024-10-08 10:08 UTC, muzarski commented on scylla-rust-wrapper/src/prepared.rs
>  }
Yes

2024-10-08 10:09 UTC, muzarski commented on scylla-rust-wrapper/src/session.rs
> +                let maybe_result_col_data_types = Some(prepared.result_col_data_types.clone());
True, I'll do it

2024-10-08 10:13 UTC, Lorak-mmk commented on scylla-rust-wrapper/src/session.rs
> +                let maybe_result_col_data_types = Some(prepared.result_col_data_types.clone());
And if you put Vec in Arc, is there a need to have individual data types in Arcs too?

2024-10-08 10:15 UTC, muzarski commented on scylla-rust-wrapper/src/session.rs
> +                let maybe_result_col_data_types = Some(prepared.result_col_data_types.clone());
Yes, I even decided to put a comment in the code to justify both Arcs.

- `Vec<Arc<...>>` -> to share vector with `CassResultData`
- `Arc<CassDataType>` - to share each data type with other structs. such as `CassValue`.

2024-10-08 10:18 UTC, muzarski commented on scylla-rust-wrapper/src/session.rs
> +                let maybe_result_col_data_types = Some(prepared.result_col_data_types.clone());
BTW, wrapping this vector with `Arc` implies additional needless allocation for simple queries (for an `Arc`), but I think performance for prepared statements is more important

2024-10-08 10:22 UTC, Lorak-mmk commented on scylla-rust-wrapper/src/session.rs
> +                let maybe_result_col_data_types = Some(prepared.result_col_data_types.clone());
There will already be 1 allocation for Vec and at least 1 for each element. Another one for this new Arc doesn't seem like much.

2024-10-08 10:26 UTC, muzarski commented
v4.1: wrapped the result data type metadata vector with an `Arc`.

The reason for this is that `CassPrepared` and `CassResultData` should share this vector, and this way we can omit an additional allocation each execution.

Note: Each individual `CassDataType` in the vector still needs to be wrapped with an `Arc`. This is because each `CassValue` (contained in `CassResult` in each `CassRow`) needs to hold information about the type.

2024-10-08 11:30 UTC, Lorak-mmk approved these changes

2024-10-10 13:48 UTC, wprzytula requested changes

2024-10-10 13:48 UTC, wprzytula commented on scylla-rust-wrapper/src/prepared.rs
> +    // Arc<Vec<...>> -> to share the whole vector with `CassResultData``.
typo: repeated ``

2024-10-10 13:48 UTC, wprzytula commented on scylla-rust-wrapper/src/session.rs
> +                // Since `query.qery` is consumed, we cannot match the statement
typo: `qery`

2024-10-10 13:48 UTC, wprzytula commented on scylla-rust-wrapper/src/session.rs
> +                // We don't store result metadta for Queries - return None.
typo: `metadta`

2024-10-10 13:48 UTC, wprzytula commented on scylla-rust-wrapper/src/query_result.rs
> +            // This allocation is unfortunately necessary, because of the type of CassResultData::col_data_types.
Could you add a comment that `maybe_col_data_types` is going to be `Some` for prepared statement execution and `None` for unprepared?

2024-10-10 13:48 UTC, wprzytula commented on scylla-rust-wrapper/src/query_result.rs
> +    let index_usize: usize = index.try_into().unwrap();
Justify `unwrap`.

2024-10-10 13:48 UTC, wprzytula commented on scylla-rust-wrapper/src/query_result.rs
> +        .unwrap_or(std::ptr::null())
Thank Ferris, the monster is gone...

2024-10-10 13:48 UTC, wprzytula commented on scylla-rust-wrapper/src/query_result.rs
> +    }
nit: I would prefer to use `to_owned()` than `to_string()` for `&str` -> `String` conversion, because `to_string()` is very generic (over anything implementing `Display`), whereas `to_owned()` hints that the struct is some borrowed form of string.

2024-10-10 13:48 UTC, wprzytula commented on scylla-rust-wrapper/src/session.rs
>  ) -> Option<Vec<CassRow>> {
This function unnecessarily accepts and returns `Option`. Let's remove it from signature altogether, to decrease complexity.

2024-10-10 14:00 UTC, muzarski commented
Rebased on master

2024-10-10 14:14 UTC, muzarski commented on scylla-rust-wrapper/src/query_result.rs
> +    let index_usize: usize = index.try_into().unwrap();
Actually, I have a question. Here is the definition of `size_t` in `types.rs`:
```rust
pub type size_t = cass_uint64_t;
pub type cass_uint64_t = u64;
```
Why? There is a `libc::size_t` which is an alias for `usize`. Couldn't we make use of it? Then, we wouldn't need to do a possibly lossy conversion each time (from `u64` to `usize`).

cc: @Lorak-mmk

2024-10-10 14:16 UTC, muzarski commented on scylla-rust-wrapper/src/query_result.rs
> +    let index_usize: usize = index.try_into().unwrap();
I believe that sizes of both `size_t` and `usize` depend on the architecture. I don't understand why we assume that `size_t` is always `u64` (8 bytes long)

2024-10-10 15:34 UTC, Lorak-mmk commented on scylla-rust-wrapper/src/query_result.rs
> +    let index_usize: usize = index.try_into().unwrap();
You are right of course. This alias was added probably by accident by @wprzytula in https://github.com/scylladb/cpp-rust-driver/commit/de6143af54e9140f6c33715653472bbe7b3d2644#diff-fffb385b3ac71791e0a2ddee4b04afa8c2d889e2713f4b1e4f29d216ec6045fd
Before that we already had definition for size_t generated by bindgen in build.rs:
https://github.com/scylladb/cpp-rust-driver/blob/4d056edf7b2180f06c7b4162efa805da14255cd7/scylla-rust-wrapper/build.rs#L24-L37

This generated header is included in types.rs, so it should be safe to remove this wrong alias - even more, they should crash and not compile. However for some reason I can't remove it, it causes errors. This needs investigation and proper fix.

2024-10-10 15:36 UTC, Lorak-mmk commented on scylla-rust-wrapper/src/query_result.rs
> +    let index_usize: usize = index.try_into().unwrap();
Generated `basic_types.rs` file is empty for some reason...

2024-10-10 15:44 UTC, Lorak-mmk commented on scylla-rust-wrapper/src/query_result.rs
> +    let index_usize: usize = index.try_into().unwrap();
Adding `.size_t_is_usize(false)` call to the builder makes the definition generate again:
```
───────┬─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
       │ File: ./target/debug/build/scylla-cpp-driver-rust-e897748878d67d0e/out/basic_types.rs
───────┼─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
   1   │ /* automatically generated by rust-bindgen 0.65.1 */
   2   │ 
   3   │ pub type size_t = ::std::os::raw::c_ulong;
───────┴─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
```

2024-10-10 15:50 UTC, muzarski commented on scylla-rust-wrapper/src/query_result.rs
> +    let index_usize: usize = index.try_into().unwrap();
> Generated `basic_types.rs` file is empty for some reason...

Same happened for me when I was playing with `build.rs` and `types.rs`

2024-10-10 15:55 UTC, wprzytula commented on scylla-rust-wrapper/src/query_result.rs
> +            // This allocation is unfortunately necessary, because of the type of CassResultData::col_data_types.
Have you done that? I can't see it.

2024-10-10 16:05 UTC, muzarski commented on scylla-rust-wrapper/src/query_result.rs
> +            // This allocation is unfortunately necessary, because of the type of CassResultData::col_data_types.
Sorry, I addressed it locally.

2024-10-10 16:07 UTC, muzarski commented
v4.2: addressed @wprzytula comments

I'd like to introduce the `size_t` fix (maybe next to other binding fixes) in other PRs. I'm currently investigating it.

2024-10-10 16:09 UTC, muzarski commented
v4.2.1: fixed clippy lint

2024-10-10 18:25 UTC, muzarski commented
v4.2.2: replaced `unwrap()` with `expect()` for `u64` to `usize` conversion.

2024-10-10 18:27 UTC, wprzytula approved these changes

2024-10-10 18:27 UTC, Lorak-mmk commented on scylla-rust-wrapper/src/query_result.rs
> +    let index_usize: usize = index.try_into().unwrap();
Could you apply this fix and remove the redundant `size_t` alias?

2024-10-10 19:08 UTC, muzarski commented on scylla-rust-wrapper/src/query_result.rs
> +    let index_usize: usize = index.try_into().unwrap();
I opened a separate PR that solves issues regarding bindings in `basic_types.rs`: https://github.com/scylladb/cpp-rust-driver/pull/188

2024-10-11 11:28 UTC, Lorak-mmk approved these changes

2024-10-11 11:29 UTC, merged