binding: typechecks
scylladb/cpp-rs-driver pull request #143
Opened 2024-07-18 13:54 UTC by muzarski

Fix: https://github.com/scylladb/cpp-rust-driver/issues/142

## Pre-review checklist

- [x] I have split my patch into logically separate commits.
- [ ] All commit messages clearly explain what they change and why.
- [ ] PR description sums up the changes and reasons why they should be introduced.
- [ ] I have implemented Rust unit tests for the features/changes introduced.
- ~[ ] I have enabled appropriate tests in `.github/workflows/build.yml` in `gtest_filter`.~
- ~[ ] I have enabled appropriate tests in `.github/workflows/cassandra.yml` in `gtest_filter`~

2024-07-29 16:00 UTC, muzarski commented
v1.1: Added a link to cpp-driver's UDT typecheck logic in a comment.

2024-07-31 12:56 UTC, roydahan approved these changes

2024-07-31 15:43 UTC, Lorak-mmk requested changes

2024-07-31 15:43 UTC, Lorak-mmk commented on scylla-rust-wrapper/src/value.rs
> +            }
cpp-driver also includes `CASS_VALUE_TYPE_CUSTOM`. I assume we are skipping support for this. Plase not this in the commit message here and in the commit about blobs.

2024-07-31 15:43 UTC, Lorak-mmk commented on scylla-rust-wrapper/src/cass_types.rs
> +            },
Here I see that there is some handling for custom types, so my previous comment may be incorrect.
Do we want to support them?

2024-07-31 15:43 UTC, Lorak-mmk commented on scylla-rust-wrapper/src/cass_types.rs
> +            },
It will probably become clear in the next commit, but this one in isolation is not clear to me. Could you explain in comment or commit message (or both) why do we need `typecheck_equals`? Previous commits already implemented type checking, so it's not clear to me as a reviewer where this is going to be used.

2024-07-31 15:43 UTC, Lorak-mmk commented on scylla-rust-wrapper/src/cass_types.rs
> +    // Empty vector stands for untyped tuple.
I know that this PR didn't introduce this, but I wonder if this is correct.
Is it possible to have an empty tuple in Scylla? If so, it could be a problem because this code won't differentiate between those 2 cases.

2024-07-31 15:43 UTC, Lorak-mmk commented on README.md
Regarding commit `collection: include info about data type `: there is typo in the message.
`cass_collection_new_from_datat_type` should be `cass_collection_new_from_data_type`

2024-07-31 15:43 UTC, Lorak-mmk commented on scylla-rust-wrapper/src/collection.rs
> +                        }
This condition looks wrong. If `index % 2 == 0` and `value` is compatible with `k_typ` then we move to second if and require that it is also compatible with `v_typ`.

Didn't tests catch this? Please make sure they do.

2024-07-31 16:02 UTC, muzarski commented on scylla-rust-wrapper/src/cass_types.rs
> +            },
I was surprised that there is a CassDataType::Custom variant as well. If we don't plan on supporting it, we should remove it I think. AFAIR, custom types are not planned to be supported in the Rust driver.

2024-07-31 16:04 UTC, muzarski commented on scylla-rust-wrapper/src/collection.rs
> +                        }
Good catch, I'll make sure to implement the corresponding test case.

2024-07-31 16:06 UTC, muzarski commented on scylla-rust-wrapper/src/cass_types.rs
> +            },
This is used for complex types (udts, tuples, collections) in `value::is_type_compatible`. I'll include this information in the commit message.

2024-08-01 10:51 UTC, muzarski commented
v1.2: rebased on master

2024-08-01 10:58 UTC, muzarski commented on scylla-rust-wrapper/src/cass_types.rs
> +    // Empty vector stands for untyped tuple.
> Is it possible to have an empty tuple in Scylla?

It doesn't seem like it:
![image](https://github.com/user-attachments/assets/94c291cd-cb5a-442a-821b-e5ff5ef068dc)

I also checked creating an empty tuple type (`tuple<>`) using cqlsh. Scylla rejects such type.

2024-08-01 13:18 UTC, muzarski commented
v2: addressed some review comments

What should we do with the custom types? @Lorak-mmk

2024-08-01 13:23 UTC, Lorak-mmk commented
I think we should either support them fully (which would require some changes in Rust Driver, probably not big ones) or not support them at all - remove them from enums, return errors as early as possible when encountering them somewhere. WDYT @wprzytula ?

2024-08-05 07:23 UTC, muzarski commented
Rebased on master

2024-08-06 18:24 UTC, muzarski commented
Rebased on master (decimal)

2024-08-07 13:49 UTC, muzarski commented on scylla-rust-wrapper/src/cass_types.rs
> +            },
I opened an issue: https://github.com/scylladb/cpp-rust-driver/issues/158

2024-08-07 13:50 UTC, muzarski commented on scylla-rust-wrapper/src/cass_types.rs
> +            },
I'll remove mentions of custom types in a separate PR.

2024-08-07 13:52 UTC, muzarski commented on scylla-rust-wrapper/src/value.rs
> +            }
Done

2024-08-07 13:52 UTC, muzarski commented
v1.3: added mention about not supporting custom types in Text and Blob commits.

2024-08-08 05:58 UTC, Lorak-mmk approved these changes

2024-08-08 08:38 UTC, wprzytula requested changes

2024-08-08 08:38 UTC, wprzytula commented on scylla-rust-wrapper/src/value.rs
> +        }
`pub` fields in non-`pub` struct make no sense.

2024-08-08 08:38 UTC, wprzytula commented on scylla-rust-wrapper/src/cass_types.rs
>  }
Typo in commit message of "types: introduce typecheck_equals method":
`value::is_type_compatbile` -> `value::is_type_compatible`

2024-08-08 08:38 UTC, wprzytula commented on scylla-rust-wrapper/src/cass_types.rs
>  }
The name is counterintuitive. Maybe `any_string_empty_or_both_equal`?

2024-08-08 08:38 UTC, wprzytula commented on scylla-rust-wrapper/src/cass_types.rs
>          val_type: Option<Arc<CassDataType>>,
What about `None, Some` ? Is it valid state for a Map? If not, perhaps we should make it irrepresentable in our Map type?

2024-08-08 08:38 UTC, wprzytula commented on scylla-rust-wrapper/src/cass_types.rs
> +                    _ => false,
It seems that we indeed treat `(None, Some)` state as invalid. I suggest storing the key and value types in a specific enum:

```rust
enum MapType {
  Untyped,
  Key(CqlDataType),
  KeyAndValue(CqlDataType),
}
```

2024-08-08 08:38 UTC, wprzytula commented on scylla-rust-wrapper/src/value.rs
> +        }
Again, `pub` fields of non-`pub` struct.

2024-08-08 08:38 UTC, wprzytula commented on scylla-rust-wrapper/src/tuple.rs
>  }
Not related to this PR:
Is it customary to implement `From` on references? Especially if this involves cloning.
What I mean is that `From` is the opposite side of `Into`, and `Into` is for _owned -> owned_ conversions. See [Rust naming conventions](https://rust-lang.github.io/api-guidelines/naming.html#ad-hoc-conversions-follow-as_-to_-into_-conventions-c-conv).

2024-08-08 08:38 UTC, wprzytula commented on scylla-rust-wrapper/src/value.rs
>          }
This should belong to the previous commit.

2024-08-08 08:38 UTC, wprzytula commented on scylla-rust-wrapper/src/value.rs
> +            for case in test_cases {
Nit: you can use statically allocated slices instead of `Vec` for storing test cases.

2024-08-08 08:38 UTC, wprzytula commented on scylla-rust-wrapper/src/collection.rs
> +        // the number of CassCqlValue will be stored.
I think the previous formulation was correct. If `CqlValue::Map` has capacity `n`, then `CassCollection` functioning as a Map has capacity `2n`.

2024-08-08 08:38 UTC, wprzytula commented on scylla-rust-wrapper/src/collection.rs
> +            _ => unreachable!(),
User can provide a value out of range, but then it's going to be their fault. That's how C contract on UB works...

2024-08-08 08:38 UTC, wprzytula commented on scylla-rust-wrapper/src/collection.rs
> +};
Great idea! Love it!

2024-08-08 08:38 UTC, wprzytula commented on scylla-rust-wrapper/src/collection.rs
> +};
Nit: this probably shouldn't be a docstring, because it would only document the first of the constants.

2024-08-08 08:38 UTC, wprzytula commented on scylla-rust-wrapper/src/collection.rs
> +        _ => return std::ptr::null_mut(),
Does cpp driver silently return a NULL pointer on bad data type passed? If so, that's sad...

2024-08-08 08:38 UTC, wprzytula commented on scylla-rust-wrapper/src/collection.rs
> +                },
`if let` ?

2024-09-13 02:09 UTC, muzarski commented
Rebased on master

2024-09-13 02:36 UTC, muzarski commented on scylla-rust-wrapper/src/collection.rs
> +        // the number of CassCqlValue will be stored.
I only changed `CqlValue` -> `CassCqlValue`.

2024-09-13 02:38 UTC, muzarski commented on scylla-rust-wrapper/src/collection.rs
> +            _ => unreachable!(),
I think we should panic here then (with some insightful error message). I wouldn't silently return a null pointer.

2024-09-13 02:41 UTC, muzarski commented on scylla-rust-wrapper/src/tuple.rs
>  }
Sure, I can change it to `to_cass_cql_value` method. But I'd do it in a follow-up PR since such `From` implementation appears in multiple places AFAIR.

2024-09-13 03:20 UTC, muzarski commented on scylla-rust-wrapper/src/cass_types.rs
> +                    _ => false,
Introduced `MapDataType` enum (last commit) which represents valid states of map data type.

2024-09-13 03:20 UTC, muzarski commented
v3: addressed review comments.

2024-09-20 14:42 UTC, Lorak-mmk requested changes
One small comment, otherwise looks good to me

2024-09-20 14:42 UTC, Lorak-mmk commented on scylla-rust-wrapper/src/cass_types.rs
> +            },
If we are not going to support Custom types then I see no point in introducing code related to it. Please replace this check with some panic.

2024-09-20 14:42 UTC, Lorak-mmk commented on scylla-rust-wrapper/src/tuple.rs
>  }
And of course this implementation is my fault :( https://github.com/scylladb/cpp-rust-driver/commit/db1a9a7f610f070ad60a3175cec4a9b11f579542

2024-09-20 15:02 UTC, muzarski commented on scylla-rust-wrapper/src/tuple.rs
>  }
I opened an issue to remember about it: https://github.com/scylladb/cpp-rust-driver/issues/177

2024-09-20 15:03 UTC, muzarski commented on scylla-rust-wrapper/src/cass_types.rs
> +            },
Done

2024-09-20 15:50 UTC, Lorak-mmk approved these changes

2024-10-01 14:57 UTC, wprzytula requested changes

2024-10-01 14:57 UTC, wprzytula commented on scylla-rust-wrapper/src/user_type.rs
> +        if !value::is_type_compatible(&value, &self.data_type.get_udt_type().field_types[index].1) {
Why did you decide to swap the parameters?

2024-10-01 14:57 UTC, wprzytula commented on scylla-rust-wrapper/src/value.rs
> +        }
Let's enrich the assertion so that it includes info whether the value was deemed type compatible when it should not or the opposite.

2024-10-01 14:57 UTC, wprzytula commented on scylla-rust-wrapper/src/cass_types.rs
> +                    }
IIUC, tuples are untyped iff their type is empty?

2024-10-01 14:57 UTC, wprzytula commented on scylla-rust-wrapper/src/cass_types.rs
> +            CassDataType::Custom(_) => panic!("Cpp-rust-driver does not support custom types!"),
Maybe let's use `unimplemented!` instead of general `panic!`? This conveys our idea specifically.

2024-10-01 14:57 UTC, wprzytula commented on scylla-rust-wrapper/src/cass_types.rs
> +        //// mutual fields they should share.
So it resembles Rust driver `SerializeValue` derive macro's logic with `force_exact_match=false`, correct? @Lorak-mmk

2024-10-01 14:57 UTC, wprzytula commented on scylla-rust-wrapper/src/value.rs
> +                }
`Typecheck for failed` ?

2024-10-01 14:57 UTC, wprzytula commented on scylla-rust-wrapper/src/value.rs
> +        data_type: Arc<CassDataType>,
Why do we store a `CassDataType` inside a `UserDefinedType`? Isn't that enum too broad for just a UDT?

2024-10-01 14:57 UTC, wprzytula commented on scylla-rust-wrapper/src/collection.rs
>              }
Oh, you've fixed a bug here, correct? Map collections were made `CassCqlValue::Set` ...

2024-10-01 14:57 UTC, wprzytula commented on scylla-rust-wrapper/src/value.rs
> +                typ.get_value_type() == CassValueType::CASS_VALUE_TYPE_SET
I'd strongly prefer to see this without such imperative `return`s, because such `return`s usually signify an abnormal return (an error, or a shortcut) and here that's no the case. Let's use functional patterns.

2024-10-01 14:57 UTC, wprzytula commented on scylla-rust-wrapper/src/value.rs
> +                typ.get_value_type() == CassValueType::CASS_VALUE_TYPE_SET
```suggestion
            CassCqlValue::List { data_type, .. } => {
                if let Some(dt) = data_type {
                    dt.typecheck_equals(typ)
                } else {
                    // Untyped list.
                    typ.get_value_type() == CassValueType::CASS_VALUE_TYPE_LIST
                }
            }
            CassCqlValue::Map { data_type, .. } => {
                if let Some(dt) = data_type {
                    dt.typecheck_equals(typ)
                } else {
                    // Untyped map.
                    typ.get_value_type() == CassValueType::CASS_VALUE_TYPE_MAP
                }
            }
            CassCqlValue::Set { data_type, .. } => {
                if let Some(dt) = data_type {
                    dt.typecheck_equals(typ)
                } else {
                    // Untyped set.
                    typ.get_value_type() == CassValueType::CASS_VALUE_TYPE_SET
                }
```

2024-10-01 14:57 UTC, wprzytula commented on scylla-rust-wrapper/src/value.rs
> +                },
Let's add an incompatible list type, e.g. `data_type_int_list`.

2024-10-01 14:57 UTC, wprzytula commented on scylla-rust-wrapper/src/value.rs
> +        }
Tests for untyped map and fully typed map are missing. Similarly, tests for set are missing.

2024-10-01 14:57 UTC, wprzytula commented on scylla-rust-wrapper/src/collection.rs
> +                }
So you say that we shouldn't check key type compatibility in case of a key-only-typed map?

2024-10-01 14:57 UTC, wprzytula commented on scylla-rust-wrapper/src/collection.rs
> +            {
What about a half-typed (key-only-typed) map?

2024-10-01 14:57 UTC, wprzytula commented on scylla-rust-wrapper/src/statement.rs
> +        CassError::CASS_OK
I dislike that we perform indexing, which may panic. Let's try to refactor this so that we match use `get()` method on slice and pattern match on its result. The pattern matching should involve both `self.bound_values` and `p.variable_col_data_types`, because we index both.

2024-10-01 14:57 UTC, wprzytula commented on scylla-rust-wrapper/src/cass_types.rs
> +            } if index == 0 => Some(k),
To save the readers from reasoning about remaining, non-exhausted patterns, let's do it this way:

2024-10-01 14:57 UTC, wprzytula commented on scylla-rust-wrapper/src/cass_types.rs
> +            } if index == 0 => Some(k),
```suggestion
            CassDataType::Map {
                typ: MapDataType::Key(k),
                ..
            } => (index == 0).then_some(k),
```

2024-10-01 14:57 UTC, wprzytula commented on scylla-rust-wrapper/src/collection.rs
>                  _ => return CassError::CASS_ERROR_LIB_INVALID_VALUE_TYPE,
Bug spotted! Before this commit, untyped and half-typed map would be accepted, and now they are rejected (they don't match `MapDataType::KeyAndValue`).

2024-10-01 15:28 UTC, muzarski commented on scylla-rust-wrapper/src/collection.rs
>                  _ => return CassError::CASS_ERROR_LIB_INVALID_VALUE_TYPE,
They wouldn't be accepted - previous version included a check for this:
```rust
// Only do the typecheck if both map types are present.
if let (Some(k_typ), Some(v_typ)) = (k_typ, v_typ) {
```

2024-10-01 15:30 UTC, muzarski commented on scylla-rust-wrapper/src/collection.rs
> +                }
I know that this is confusing (since we allow users to define such map types), but this is the cpp-driver's logic:
https://github.com/scylladb/cpp-driver/blob/master/src/collection.hpp#L100-L110

2024-10-01 15:31 UTC, muzarski commented on scylla-rust-wrapper/src/collection.rs
> +                }
The `if (data_type_->types().size() == 2` part implies that both types need to be present to bind value to map collection.

2024-10-01 15:37 UTC, muzarski commented on scylla-rust-wrapper/src/collection.rs
>                  _ => return CassError::CASS_ERROR_LIB_INVALID_VALUE_TYPE,
Sorry, I misunderstood.

2024-10-01 15:40 UTC, muzarski commented on scylla-rust-wrapper/src/collection.rs
>                  _ => return CassError::CASS_ERROR_LIB_INVALID_VALUE_TYPE,
I'll fix it and introduce additional test cases. Good catch!

2024-10-01 15:46 UTC, muzarski commented
Rebased on master

2024-10-01 16:15 UTC, muzarski commented on scylla-rust-wrapper/src/user_type.rs
> +        if !value::is_type_compatible(&value, &self.data_type.get_udt_type().field_types[index].1) {
Since I moved it to `value` module, I thought that it makes more sense to have a value as first parameter.

2024-10-01 16:27 UTC, muzarski commented on scylla-rust-wrapper/src/value.rs
> +        data_type: Arc<CassDataType>,
That's true - `UDTDataType` would be sufficient. However, this way it's much easier to call `CassDataType::typecheck_equals`. In addition, we would need to clone whole `UDTDataType` since it's owned by a shared reference to `CassDataType` (see `From<&CassUserType> for CassCqlValue` implementation). As of now, we only need to clone an Arc<CassDataType>, which is much cheaper operation.

2024-10-01 16:32 UTC, muzarski commented on scylla-rust-wrapper/src/collection.rs
>              }
Noo, I think it's just a confusing diff generated by git.

2024-10-01 16:46 UTC, muzarski commented on scylla-rust-wrapper/src/value.rs
> +        }
Typed maps and sets are included in `[in]compatible_types` for some other types. But I'll introduce separate test cases for them as well.

2024-10-01 17:15 UTC, wprzytula commented on scylla-rust-wrapper/src/collection.rs
> +                }
Do we prefer to be mimic cpp-driver as tight as possible in this case, or maybe let's be more eager and do the type check of the key, if present, to save the user from errors?

2024-10-01 17:31 UTC, muzarski commented on scylla-rust-wrapper/src/collection.rs
> +                }
To be honest, I think this is a bug in a cpp-driver. We should not mimic this behaviour

2024-10-01 18:22 UTC, muzarski commented on scylla-rust-wrapper/src/statement.rs
> +        CassError::CASS_OK
I refactored the code

2024-10-01 18:24 UTC, muzarski commented
v4: addressed @wprzytula comments. Thanks for spotting the bug! I introduced a lot of additional test cases which consider more combinations during typechecks

2024-10-02 09:21 UTC, wprzytula approved these changes

2024-10-02 09:41 UTC, merged