cluster: global request client timeout
scylladb/cpp-rs-driver pull request #151
Opened 2024-07-31 09:03 UTC by muzarski

This PR implements `cass_cluster_set_request_timeout`.

In addition, it adjusts the default request client timeout, according to documentation in `cassandra.h`.

## Pre-review checklist

- [x] I have split my patch into logically separate commits.
- [x] All commit messages clearly explain what they change and why.
- [x] PR description sums up the changes and reasons why they should be introduced.
- ~[ ] I have enabled appropriate tests in `.github/workflows/build.yml` in `gtest_filter`.~
- ~[ ] I have enabled appropriate tests in `.github/workflows/cassandra.yml` in `gtest_filter`.~

2024-07-31 15:08 UTC, wprzytula approved these changes

2024-08-01 11:54 UTC, Lorak-mmk approved these changes

2024-08-01 11:56 UTC, Lorak-mmk requested changes

2024-08-01 11:56 UTC, Lorak-mmk commented on scylla-rust-wrapper/src/cluster.rs
> +        .request_timeout(Some(Duration::from_millis(12000)));
Can we have this as constant somewhere?

2024-08-01 12:04 UTC, muzarski commented on scylla-rust-wrapper/src/cluster.rs
> +        .request_timeout(Some(Duration::from_millis(12000)));
Done. Created a constant for default consistency level as well.

2024-08-01 12:14 UTC, Lorak-mmk approved these changes

2024-08-01 12:15 UTC, Lorak-mmk commented
@wprzytula I'll let you merge so that you can read the newest changes

2024-08-01 13:23 UTC, wprzytula approved these changes

2024-08-01 13:23 UTC, merged