ci: fix skipped tests
scylladb/cpp-rs-driver pull request #155
Opened 2024-08-05 09:11 UTC by muzarski

Fix: https://github.com/scylladb/cpp-rust-driver/issues/144

## Pre-review checklist

- [ ] I have split my patch into logically separate commits.
- [ ] All commit messages clearly explain what they change and why.
- [ ] PR description sums up the changes and reasons why they should be introduced.
- [ ] I have enabled appropriate tests in `.github/workflows/build.yml` in `gtest_filter`.
- [ ] I have enabled appropriate tests in `.github/workflows/cassandra.yml` in `gtest_filter`.

2024-08-05 15:57 UTC, muzarski commented
Rebased on master

2024-08-05 18:06 UTC, Lorak-mmk requested changes

2024-08-05 18:06 UTC, Lorak-mmk commented on tests/src/integration/ccm/bridge.cpp
> +  }
Why not switch the condition around to avoid unnecessary negation?

2024-08-05 18:06 UTC, Lorak-mmk commented on tests/src/integration/tests/test_basics.cpp
>      }
Aren't we going to run into this ` if (!Options::is_cassandra()) {
    if (server_version_ >= "6.0.0") {` branch when we update Scylla to 6.0?
If so, can you fix this in this PR?

2024-08-05 18:25 UTC, muzarski commented on tests/src/integration/tests/test_basics.cpp
>      }
No, `Options::is_cassandra()` actually returns `true` for Scylla as well. It's because Scylla identifies as `Apache Cassandra` server.

There are 3 possible `CCM:ServerType` enum values:
```cpp

bool Options::is_cassandra() { return server_type_ == CCM::ServerType::CASSANDRA; }

bool Options::is_dse() { return server_type_ == CCM::ServerType::DSE; }

bool Options::is_ddac() { return server_type_ == CCM::ServerType::DDAC; }
```

I'm not sure about the difference between the types, but in Scylla's case, the server type is `CASSANDRA`. `Options::is_scylla_` is a flag responsible for distinguishing between scylla and cassandra.

2024-08-05 19:00 UTC, Lorak-mmk commented on tests/src/integration/tests/test_basics.cpp
>      }
wth is ddac?! Never heard about it before.

2024-08-07 07:50 UTC, muzarski commented
v1.1: addressed review comment

2024-08-08 05:05 UTC, Lorak-mmk approved these changes

2024-08-08 11:04 UTC, wprzytula commented on tests/src/integration/tests/test_basics.cpp
>      }
https://www.datastax.com/press-release/datastax-announces-datastax-distribution-apache-cassandratm

2024-08-12 08:10 UTC, wprzytula requested changes

2024-08-12 08:10 UTC, wprzytula commented on tests/src/integration/ccm/bridge.cpp
>    }
Inconsistent indentation? `throw` should probably be indented less.

2024-08-12 08:10 UTC, wprzytula commented on tests/src/integration/ccm/bridge.cpp
> +  return CassVersion(ccm_output);
For readability, please make the `if` and `if-else` statement, with this in `if (is_scylla)` branch, and the other code in `else` branch.

2024-08-12 08:10 UTC, wprzytula commented on tests/src/integration/ccm/cass_version.hpp
>      std::replace(version.begin(), version.end(), '.', ' ');
How this new code actually retrieves the Scylla version? Or, if it's already retrieved, what variable stores it?

2024-08-12 08:10 UTC, wprzytula commented on tests/src/integration/integration.hpp
> +    if (!Options::is_scylla() && cass_version < #version) {                                                  \
Please add a comment mentioning why only Cassandra version is checked now and maybe a `TODO: Scylla version checks (when needed)`.

2024-08-12 08:10 UTC, wprzytula commented on .github/workflows/build.yml
> +:*NoCompactEnabledConnection"
IIUC, this commit makes the CI pass again, after the previous commit makes if fail due to disabling version filtering for Scylla.
We shouldn't have any commits that do not pass tests, because those break bisectability. A quick fix is to swap this commit with the previous one.

2024-08-12 08:10 UTC, wprzytula commented on tests/src/integration/objects/collection.hpp
> +      is_null_ = false;
While this is an unpleasant peculiarity, empty collections seem to be identical to NULL values for the DB. See https://github.com/scylladb/scylla-rust-driver/pull/1007 for reference.

2024-08-12 08:10 UTC, wprzytula commented on tests/src/integration/objects/collection.hpp
> +      is_null_ = false;
Have you considered making `position` field a non-`Option`?

2024-08-12 08:10 UTC, wprzytula commented on tests/src/integration/objects/collection.hpp
> +      is_null_ = false;
I don't want to dive too deep into the code (because I have other tasks to do), but I think we should do our best to make the cpp-rust-driver's behaviour consistent with what the official cpp-driver's tests expect.

2024-08-12 17:46 UTC, Lorak-mmk commented on tests/src/integration/objects/collection.hpp
> +      is_null_ = false;
> I don't want to dive too deep into the code (because I have other tasks to do), but I think we should do our best to make the cpp-rust-driver's behaviour consistent with what the official cpp-driver's tests expect.

It was my understanding that this is what this PR does. Is that not the case?

2024-09-04 10:19 UTC, muzarski commented on tests/src/integration/ccm/cass_version.hpp
>      std::replace(version.begin(), version.end(), '.', ' ');
> Or, if it's already retrieved, what variable stores it?

The `version` variable.

2024-09-04 12:55 UTC, muzarski commented on tests/src/integration/objects/collection.hpp
> +      is_null_ = false;
> While this is an unpleasant peculiarity, empty collections seem to be identical to NULL values for the DB. See [scylladb/scylla-rust-driver#1007](https://github.com/scylladb/scylla-rust-driver/pull/1007) for reference.

Good catch. I'll add the `is_null_` initialization here. However, I still think that iterator should not be used for checking if collection is empty. The iterator, when created, is UNINITIALIZED - to retrieve the first value, we should firstly advance the iterator via `cass_iterator_next`. I don't want to advance the iterator just to check if it's empty. I'll adjust the code so we make use of `cass_value_item_count` function, which can be used to see if collection is empty.

2024-09-04 13:59 UTC, muzarski commented
v2: addressed review comments

2024-09-05 05:48 UTC, dkropachev requested changes

2024-09-05 05:48 UTC, dkropachev commented on tests/src/integration/ccm/bridge.cpp
> +  else {
can you please drop this `else`

2024-09-05 05:48 UTC, dkropachev commented on tests/src/integration/integration.hpp
> +#define CHECK_OPTIONS_CASSANDRA_VERSION(version)                                 \
I don't see it is ever used, can we drop it ?

2024-09-05 05:48 UTC, dkropachev commented on tests/src/integration/integration.hpp
> +#define CHECK_CASSANDRA_VERSION(version)                                                      \
Since we are renaming it, can we rename it to somehting more telling, like `SKIP_IF_CASSANDRA_VERSION_LE`

2024-09-05 05:48 UTC, dkropachev commented on tests/src/integration/objects/collection.hpp
>        iterator_ = cass_iterator_from_collection(value);
Can you drop this line then ?

2024-09-05 07:27 UTC, muzarski commented on tests/src/integration/objects/collection.hpp
>        iterator_ = cass_iterator_from_collection(value);
No. `iterator_` is a field. This code is called when constructor is called, and so this line initializes a field of a new object.

2024-09-05 07:37 UTC, muzarski commented
v2.1: Addressed @dkropachev 's review comments.

2024-09-05 11:01 UTC, merged