ci: redo cicd
scylladb/cpp-rs-driver pull request #159
Opened 2024-09-05 15:06 UTC by dkropachev

## Pre-review checklist

- [ ] I have split my patch into logically separate commits.
- [ ] All commit messages clearly explain what they change and why.
- [ ] PR description sums up the changes and reasons why they should be introduced.
- [ ] I have enabled appropriate tests in `.github/workflows/build.yml` in `gtest_filter`.
- [ ] I have enabled appropriate tests in `.github/workflows/cassandra.yml` in `gtest_filter`.

2024-09-08 01:14 UTC, dkropachev commented
CICD Speedup results:
`Build + Scylla IT`: takes `5` minutes instead of `18`.
`Build + Cassandra IT`: takes `6` minutes instead of `18`.

2024-09-09 12:23 UTC, muzarski commented
I see two main issues here:
1. The test binary cache is not working as intended - the binary is not found in the cache in `Scylla ITs` job.
2. Something is messed up with the test filter. Notice that we only ran 9 test cases - This is probably the reason why CI sped up so much. When it comes to the filter, I see some unnecessary whitespaces that probably mess things up:
`Note: Google Test filter = ClusterTests.* :BasicsTests.* :PreparedTests.* :CassandraTypes/CassandraTypesTests/*.Integration_Cassandra_* :BatchSingleNodeClusterTests*:BatchCounterSingleNodeClusterTests*:BatchCounterThreeNodeClusterTests* :ErrorTests.* :SslNoClusterTests*:SslNoSslOnClusterTests* :SchemaMetadataTest.*KeyspaceMetadata:SchemaMetadataTest.*MetadataIterator:SchemaMetadataTest.*View* :TracingTests.* :ByNameTests.* :CompressionTests.* :LoggingTests.* :PreparedMetadataTests.* :UseKeyspaceCaseSensitiveTests.* :-PreparedTests.Integration_Cassandra_PreparedIDUnchangedDuringReprepare :ExecutionProfileTest.InvalidName :*NoCompactEnabledConnection :PreparedMetadataTests.Integration_Cassandra_AlterDoesntUpdateColumnCount :UseKeyspaceCaseSensitiveTests.Integration_Cassandra_ConnectWithKeyspace:*_DSE_*`

2024-09-09 17:20 UTC, dkropachev commented
> I see two main issues here:
> 
> 1. The test binary cache is not working as intended - the binary is not found in the cache in `Scylla ITs` job, and then, it is built again.
> 2. Something is messed up with the test filter. Notice that we only ran 9 test cases - This is probably the reason why CI sped up so much. When it comes to the filter, I see some unnecessary whitespaces that probably mess things up:
>    `Note: Google Test filter = ClusterTests.* :BasicsTests.* :PreparedTests.* :CassandraTypes/CassandraTypesTests/*.Integration_Cassandra_* :BatchSingleNodeClusterTests*:BatchCounterSingleNodeClusterTests*:BatchCounterThreeNodeClusterTests* :ErrorTests.* :SslNoClusterTests*:SslNoSslOnClusterTests* :SchemaMetadataTest.*KeyspaceMetadata:SchemaMetadataTest.*MetadataIterator:SchemaMetadataTest.*View* :TracingTests.* :ByNameTests.* :CompressionTests.* :LoggingTests.* :PreparedMetadataTests.* :UseKeyspaceCaseSensitiveTests.* :-PreparedTests.Integration_Cassandra_PreparedIDUnchangedDuringReprepare :ExecutionProfileTest.InvalidName :*NoCompactEnabledConnection :PreparedMetadataTests.Integration_Cassandra_AlterDoesntUpdateColumnCount :UseKeyspaceCaseSensitiveTests.Integration_Cassandra_ConnectWithKeyspace:*_DSE_*`

Thanks, now it looks good, please take a look.

2024-09-09 17:23 UTC, dkropachev commented
CICD Speedup results:
Build + Scylla IT: takes `15` minutes instead of `19`.
Build + Cassandra IT: takes `15` minutes instead of `19`.

2024-09-10 06:58 UTC, muzarski requested changes
Mostly some nits. Other than that, really nice job!

2024-09-10 06:58 UTC, muzarski commented on .github/workflows/build-lint-and-test.yml
> +      - name: Check
I would decouple this step into 3 separate steps. Let's say, only a clippy check fails - then the logs from other checks introduce unnecessary noise, making it harder to see which check actually failed.

2024-09-10 06:58 UTC, muzarski commented on .github/workflows/build-lint-and-test.yml
> +    steps:
I would reorder the steps in this job. It does not make much sense to build an integration test binary, if checks or unit tests for rust wrapper fail. The order I'd recommend:
- checkout
- install dependencies
- rust wrapper checks (3 separate steps - format, cargo, clippy)
- unit and proxy tests
- build IT binary
- save IT binary

2024-09-10 06:58 UTC, muzarski commented on .github/workflows/build-lint-and-test.yml
> +        if: success()
Nit: AFAIU, `success()` is used by default. See: https://docs.github.com/en/actions/writing-workflows/choosing-what-your-workflow-does/evaluate-expressions-in-workflows-and-actions#status-check-functions.

2024-09-10 06:58 UTC, muzarski commented on .github/workflows/build-lint-and-test.yml
> +          path: /tmp/ccm*/ccm*/node*/logs/*
Question: Where does this path come from? Is it some default path that ccm uses to export logs? The question also applies to the `./log/*` path used in the previous step.

2024-09-10 06:58 UTC, muzarski commented on .github/workflows/build-lint-and-test.yml
> +          path: /tmp/ccm*/ccm*/node*/logs/*
Maybe add some constant variables for these paths? They are reused for cassandra integration tests as well.

2024-09-10 06:58 UTC, muzarski commented on Makefile
> +SCYLLA_TEST_FILTER := $(subst ${SPACE},${EMPTY},ClusterTests.*\
I was looking for alternatives to getting rid of these annoying whitespaces. The only thing I found is last paragraph in https://www.gnu.org/software/make/manual/html_node/Splitting-Lines.html. Basically, replace `\` with `$\` at the end of each line. This is still kinda annoying and tedious to do, but then we don't need to introduce `EMPTY` and `SPACE` definitions. I'm not sure which approach is better. WDYT?

2024-09-10 06:58 UTC, muzarski commented on Makefile
> +endif
Why do we have this `ifndef` clause for `run-test-integration-cassandra`, but not for `run-integration-scylla`? I believe that the purpose of `DONT_REBUILD_INTEGRATION_BIN` is to distinguish the use case between a CI and a local development - during CI, we don't want to rebuild a binary, while as a developer, I usually want to rebuild it after introducing some changes. I think that we should do the same for scylla ITs.

2024-09-10 06:58 UTC, muzarski commented on Makefile
> +endif
Small nitpick: I'd change `ifndef` to `ifdef` (and swap the branches) just to improve readability. Double negation is always tricky :)

2024-09-10 06:58 UTC, muzarski commented on .github/workflows/build-lint-and-test.yml
> +            echo "value=$(python3 ci/version_fetch.py --version-index 1 scylla-enterprise-stable:1 | tr -d '\"')" >> $GITHUB_OUTPUT
Maybe `>> $GITHUB_OUTPUT` -> `| tee -a $GITHUB_OUTPUT` so we can quickly check the chosen version in CI logs?

2024-09-10 06:58 UTC, muzarski commented on ci/version_fetch.py
> +#!/usr/bin/python3
From what I've checked, we use a very similar script in java-driver's CI. Out of curiosity - are any other drivers/repos making use of similar script?

2024-09-10 11:20 UTC, dkropachev commented on .github/workflows/build-lint-and-test.yml
> +      - name: Check
Then there is a problem that you have to keep `Makefile` and `build-lint-and-test.yml` in sync.

2024-09-10 11:24 UTC, dkropachev commented on .github/workflows/build-lint-and-test.yml
> +    steps:
Done, but I realy don't want to break `make check` because of https://github.com/scylladb/cpp-rust-driver/pull/159#discussion_r1751762641

2024-09-10 11:30 UTC, dkropachev commented on .github/workflows/build-lint-and-test.yml
> +        if: success()
removed

2024-09-10 11:45 UTC, dkropachev commented on Makefile
> +SCYLLA_TEST_FILTER := $(subst ${SPACE},${EMPTY},ClusterTests.*\
I don't see any big difference between these two.

2024-09-10 11:46 UTC, dkropachev commented on Makefile
> +endif
Yeah, it does not work, swapped it to `ifeq`

2024-09-10 11:48 UTC, dkropachev commented on .github/workflows/build-lint-and-test.yml
> +            echo "value=$(python3 ci/version_fetch.py --version-index 1 scylla-enterprise-stable:1 | tr -d '\"')" >> $GITHUB_OUTPUT
done

2024-09-10 11:49 UTC, dkropachev commented on ci/version_fetch.py
> +#!/usr/bin/python3
We are going to have in all the drivers, later on i will make a github action for it.

2024-09-10 11:51 UTC, muzarski commented on Makefile
> +SCYLLA_TEST_FILTER := $(subst ${SPACE},${EMPTY},ClusterTests.*\
Let's leave it as is then

2024-09-10 11:52 UTC, dkropachev commented on .github/workflows/build-lint-and-test.yml
> +          path: /tmp/ccm*/ccm*/node*/logs/*
done

2024-09-10 11:55 UTC, muzarski approved these changes

2024-09-10 13:32 UTC, merged