Implement CassDataType, CassValueType and CassUserType
scylladb/cpp-rs-driver pull request #18
Opened 2021-10-22 23:36 UTC by avelanarius

The first commit implements `CassDataType`, `CassValueType` and a portion of related `cass_data_type*` functions.

The second commit implements `CassUserType` and a portion of related `cass_user_type*` functions.

The third commit implements `cass_statement_bind_user_type` and adds an example UDT insert to `main.c`.

2021-10-25 11:03 UTC, piodul requested changes

2021-10-25 11:03 UTC, piodul commented on scylla-rust-wrapper/src/cass_types.rs
> +pub unsafe extern "C" fn cass_data_type_new(value_type: CassValueType) -> *mut CassDataType {
The `CassValueType` used here looks a bit scary. I don't know if it is defined behavior if e.g. the user passes `123456` here, which does not correspond to any valid variant of the enum. I would recommend explicitly checking if the integral value passed to Rust corresponds to a valid `CassValueType`. You can use the [`num_enum`](https://crates.io/crates/num_enum) crate to generate the boilerplate for you.

2021-10-25 11:03 UTC, piodul commented on scylla-rust-wrapper/src/cass_types.rs
> +    CASS_VALUE_TYPE_LAST_ENTRY = 50,
I don't think we need this variant - it's not a real value type.

2021-10-25 11:03 UTC, piodul commented on scylla-rust-wrapper/src/statement.rs
> +            fields: user_type.field_values.clone().into_iter().collect(),
With the master version of scylla-rust-driver, just cloning should be sufficient (`fields` has the same type as `user_type.field_values`).

2021-10-25 11:03 UTC, piodul commented on scylla-rust-wrapper/src/cass_types.rs
> +pub unsafe extern "C" fn cass_data_type_new(value_type: CassValueType) -> *mut CassDataType {
Besides, I think that the original cpp driver returns a null pointer in case `value_type` is not a valid type (in case of UNKNOWN it does it, too).

2021-10-25 11:03 UTC, piodul commented on scylla-rust-wrapper/src/user_type.rs
> +unsafe fn cass_user_type_set_cql_value_by_name(
I think we could reduce the boilerplate of the `cass_user_type_set_xyz` functions with the help of macros, but it can be done in a followup.

2021-10-25 11:35 UTC, havaker commented on scylla-rust-wrapper/src/cass_types.rs
> +    CASS_VALUE_TYPE_LAST_ENTRY = 50,
I think it's safer to leave it. This enum has a `repr(C)`, it assumes that enum on a C side has same variants, and chooses enum's representation based on it.

2021-10-25 12:39 UTC, constantfold commented on scylla-rust-wrapper/src/statement.rs
> +            fields: user_type.field_values.clone().into_iter().collect(),
Yes, this is remnant of my older version...

2021-10-26 07:21 UTC, piodul commented on scylla-rust-wrapper/src/cass_types.rs
> +    CASS_VALUE_TYPE_LAST_ENTRY = 50,
Removing this field won't affect the enum's representation because it's not the variant with the biggest value (the biggest is `CASS_VALUE_TYPE_UNKNOWN`). The enum size is chosen based on the biggest variant.

That said, I'm not sure if we should put rust enums on a FFI boundary directly because somebody could pass an invalid enum variant and it would be undefined behavior in rust:

> Fieldless enums with repr(C) or repr(u*) still may not be set to an integer value without a corresponding variant, even though this is permitted behavior in C or C++. It is undefined behavior to (unsafely) construct an instance of an enum that does not match one of its variants. (This allows exhaustive matches to continue to be written and compiled as normal.)

Source: https://doc.rust-lang.org/nomicon/other-reprs.html#reprc

I suggested using `num_enum` crate in a previous comment in order to avoid this issue.

2021-11-19 14:03 UTC, Lorak-mmk commented on scylla-rust-wrapper/src/cass_types.rs
> +pub unsafe extern "C" fn cass_data_type_new(value_type: CassValueType) -> *mut CassDataType {
I opened a PR that generates enum at compile time - and those enums are implemented as wrappers for integer types, with associated constants - then we can then accept such enum as argument, and any match on it simply won't be exhaustive until we handle case of invalid value. So I suggest merging my PR, then rebasing this one to use the same approach.

2021-11-20 14:50 UTC, Lorak-mmk commented on scylla-rust-wrapper/src/cass_types.rs
> +    CASS_VALUE_TYPE_LAST_ENTRY = 50,
This variant will remain, as enum is now auto generated. Also, even if it was copied, it is actually used in cpp driver, so we probably would to also use it at some point:
```
    default:
      if (type < CASS_VALUE_TYPE_LAST_ENTRY) {
        data_type = new DataType(type);
        data_type->inc_ref();
      }
      break;
```

2021-12-10 13:21 UTC, Lorak-mmk commented
Closing in favour of https://github.com/hackathon-rust-cpp/cpp-rust-driver/pull/60

2021-12-10 13:21 UTC, closed without merging