binding: fix by-name parameter binding and enable corresponding IT
scylladb/cpp-rs-driver pull request #187
Opened 2024-10-09 09:54 UTC by muzarski

## Motivation
Before this PR, binding values by name to unprepared queries was buggy:
- Main issue was that we were not even reading name-to-index mapping (`SimpleQuery::name_to_bound_index`) - only writing to it. In result, we were not really binding by name, but rather by position, in the same order as `cass_statement_bind_*` calls appeared. The `bound_values` vector was directly passed to `Session::query_*` calls.
- `CassStatement::bind_cql_value` would return `CASS_OK` when size of `SimpleQuery::name_to_bound_index` map exceeded the declared size of parameters (`CassStatement::bound_values.len()`)
- We wouldn't unquote the parameter names for unprepared queries in `CassStatement::bind_cql_value`

This PR solves this issue, and enables another integration test suite - `NamedParametersTests`.

## Changes
Apart from the fixes to `CassStatement::bind_cql_value`, I also introduced a custom implementation of `SerializeRow` for unprepared queries execution. I created a `SimpleQueryRowSerializer` struct which holds necessary information to perform serialization. Now, with following context:
- `bound_values` vector - directly taken from `CassStatement::bound_values`
- an optional name-to-index mapping (from `SimpleQuery::name_to_bound_index`) - if it's non-empty, it means that we bind by names, otherwise we preserve the original order of `bound_values`.
- column specs from `RowSerializationContext`

we are able to serialize values in correct order for unprepared queries.

## Pre-review checklist

- [x] I have split my patch into logically separate commits.
- [x] All commit messages clearly explain what they change and why.
- [x] PR description sums up the changes and reasons why they should be introduced.
- ~[ ] I have implemented Rust unit tests for the features/changes introduced.~
- [x] I have enabled appropriate tests in `.github/workflows/build.yml` in `gtest_filter`.
- [x] I have enabled appropriate tests in `.github/workflows/cassandra.yml` in `gtest_filter`.

2024-10-09 10:24 UTC, Lorak-mmk commented
> 4 out of 6 tests from this suite are passing. We can enable them.
> 
> When it comes to SimpleStatementAnyOrder and SimpleStatementInvalidName, I don't think we will ever enable them. The reason is that rust-driver no longer supports 'WITH_NAMES_FOR_VALUES' flag (https://github.com/apache/cassandra/blob/trunk/doc/native_protocol_v4.spec#L379) since serialization refactor, thus does not support "by name" value binding.
> 

I don't get it. Rust Driver prepares the statements underneath and should be able to handle named bind markers in queries.

> The reason that analogous tests for prepared statements pass is because "name-to-indexes" mapping can be retrieved from the prepared statement's metadata received from the server upon preparation. Thanks to that, we can bind the values by name in correct order (in cpp-rust-driver layer).

2024-10-09 10:31 UTC, muzarski commented
> I don't get it. Rust Driver prepares the statements underneath and should be able to handle named bind markers in queries.

You are right. Probably, the custom `SerializeRow` implementation will do the job. I'll try it out

2024-10-09 16:40 UTC, muzarski commented
I updated the description.

2024-10-10 14:48 UTC, wprzytula requested changes

2024-10-10 14:48 UTC, wprzytula commented on scylla-rust-wrapper/src/statement.rs
> +        } else {
The `unwrap`s can be avoided.

2024-10-10 14:48 UTC, wprzytula commented on scylla-rust-wrapper/src/statement.rs
> +        } else {
```suggestion
        // If the name was quoted, then we should treat it as case sensitive.
        let (name_unquoted, is_case_sensitive) = match name.strip_prefix('\"').and_then(|s| s.strip_suffix('\"')) {
            Some(stripped) => (stripped, true),
            None => (name, false),
        }
```

2024-10-10 14:48 UTC, wprzytula commented on scylla-rust-wrapper/src/statement.rs
>      fn bind_cql_value_by_name(&mut self, name: &str, value: Option<CassCqlValue>) -> CassError {
My suggested rewrite of this function for more readability, fewer `unwrap`s and more FP control flow:
(see how I tamed the borrow checker :sunglasses: )
```rust
fn bind_cql_value_by_name(&mut self, name: &str, value: Option<CassCqlValue>) -> CassError {
    // If the name was quoted, then we should treat it as case sensitive.
    let (name_unquoted, is_case_sensitive) =
        match name.strip_prefix('\"').and_then(|s| s.strip_suffix('\"')) {
            Some(name_unquoted) => (name_unquoted, true),
            None => (name, false),
        };

    match &self.statement {
        Statement::Prepared(prepared) => {
            let indices: Vec<usize> = prepared
                .statement
                .get_variable_col_specs()
                .iter()
                .enumerate()
                .filter(|(_, col)| {
                    is_case_sensitive && col.name == name_unquoted
                        || !is_case_sensitive && col.name.eq_ignore_ascii_case(name_unquoted)
                })
                .map(|(i, _)| i)
                .collect();

            if indices.is_empty() {
                CassError::CASS_ERROR_LIB_NAME_DOES_NOT_EXIST
            } else {
                self.bind_multiple_values_by_name(&indices, value)
            }
        }
        Statement::Simple(query) => {
            let index = query.name_to_bound_index.get(name_unquoted);

            if let Some(idx) = index {
                self.bind_cql_value(*idx, value)
            } else {
                // Find first free index, i.e. index where value at this index is Unset.
                let free_index = self.bound_values.iter().position(|v| matches!(v, Unset));
                if let Some(index) = free_index {
                    if let Statement::Simple(query) = &mut self.statement {
                        query
                            .name_to_bound_index
                            .insert(name_unquoted.to_string(), index);
                    }
                    self.bind_cql_value(index, value)
                } else {
                    CassError::CASS_ERROR_LIB_NAME_DOES_NOT_EXIST
                }
            }
        }
    }
}
```

2024-10-10 14:48 UTC, wprzytula commented on scylla-rust-wrapper/src/statement.rs
> +    }
I'm moderately worried about overhead introduced by `by_name` binding. Can we at least perform some optimisations, such as using `VecMap` instead of `HashMap`, and `SmallVec` instead of `Vec`?
(It doesn't have to be in this PR, ofc)

2024-10-10 14:48 UTC, wprzytula commented on scylla-rust-wrapper/src/cass_error.rs
> +                // There is no other way to check the actual error.
I encourage you to make a PR to Rust driver that publicises the field of all of: `SerializationError`, `DeserializationError`, `TypeCheckError`. I'd prefer not to merge this as-is, with string textual matching.

2024-10-10 14:48 UTC, wprzytula commented on scylla-rust-wrapper/src/cass_error.rs
> +                    // It means that our custom `UnknownNamedParameterError` was returned.
Oh, allocations upon error conversion, noooo...

2024-10-10 14:48 UTC, wprzytula commented on tests/src/integration/tests/test_named_parameters.cpp
>  }
Is this a change wrt cpp-driver, or rather a revert to cpp-driver's original test?

2024-10-10 15:01 UTC, muzarski commented on tests/src/integration/tests/test_named_parameters.cpp
>  }
Cpp-driver supports this flag: https://github.com/apache/cassandra/blob/trunk/doc/native_protocol_v4.spec#L379.

So what it does for unprepared queries (when binding by name), is it just simply sends the request with bad names - server performs name validation and returns an error. In our case, we do the validation on driver's side (because rust-driver prepares simple queries under the hood, to receive the metadata). We need to adjust the test to this logic - i.e. expect a validation error from the driver (`ERROR_LIB...`), and not server error (`ERROR_SERVER...`).

2024-10-10 15:10 UTC, muzarski commented on scylla-rust-wrapper/src/cass_error.rs
> +                // There is no other way to check the actual error.
Opened PR: https://github.com/scylladb/scylla-rust-driver/pull/1087

2024-10-30 12:35 UTC, muzarski commented
v2: rebased on https://github.com/scylladb/cpp-rust-driver/pull/200. We don't match the specific `SerializationError` by stringification anymore - `downcast_ref()` method is used.

2024-10-30 12:57 UTC, muzarski commented
v3: rewritten the `bind_cql_value_by_name` method according to @wprzytula suggestions - thank you! Now, the method logic is much clearer since we got rid of early returns.

2024-10-30 13:04 UTC, muzarski commented on scylla-rust-wrapper/src/statement.rs
> +    }
Opened an issue not to forget about it: https://github.com/scylladb/cpp-rust-driver/issues/201

2024-10-30 18:06 UTC, muzarski commented
Rebased on master

2024-12-01 21:26 UTC, wprzytula approved these changes

2024-12-01 21:27 UTC, wprzytula commented
The PR's name is a bit misleading. It sounds like it changes only tests and enables them; instead, it fixes **bugs** in the driver! This should definitely be indicated in the name, and also prioritised higher.

2024-12-02 15:45 UTC, muzarski commented
> The PR's name is a bit misleading. It sounds like it changes only tests and enables them; instead, it fixes **bugs** in the driver! This should definitely be indicated in the name, and also prioritised higher.

Good point. Adjusted the title

2024-12-02 15:45 UTC, muzarski commented
Rebased on master

2024-12-02 17:38 UTC, wprzytula approved these changes

2024-12-03 10:05 UTC, Lorak-mmk requested changes

2024-12-03 10:05 UTC, Lorak-mmk commented on scylla-rust-wrapper/src/statement.rs
>                      .collect();
📌 Can we make `bind_multiple_values_by_name` get impl Iterator or something like this, and avoid allocating a vector here? We should make prepared statements fast.

2024-12-03 10:05 UTC, Lorak-mmk commented on scylla-rust-wrapper/src/statement.rs
> +                    free_index = self.bound_values.iter().position(|v| matches!(v, Unset));
❓ For unprepared statements the names are always case sensitive with the current implementation. Is that also the case for cpp-driver?

2024-12-03 10:05 UTC, Lorak-mmk commented on scylla-rust-wrapper/src/statement.rs
> +                        }
🔧 This is all under a `Statement::Simple(query) => {` match clause already. 
Why do you match the same thing again? The presence of "if" suggests that this may not be a Simple variant, which I don't think is possible.

2024-12-03 10:05 UTC, Lorak-mmk commented on scylla-rust-wrapper/src/statement.rs
> +}
❓ In Rust Driver we generate those impls using "thiserror" crate, right? Do you think it is worth it to use it here too or is there not enough such impls to warrant adding a dependency?

2024-12-03 10:05 UTC, Lorak-mmk commented on scylla-rust-wrapper/src/statement.rs
> +    }
🔧 In the named variant, instead of collecting to a new vector, can you iterator over the values and serialize them?
This would avoid vector allocation, possible the `.clone()` in `self.bound_values[*bound_values_idx].clone()`.
`.try_for_each()` iterator method would probably be the best fit for this.

2024-12-03 18:56 UTC, muzarski commented on scylla-rust-wrapper/src/statement.rs
> +                        }
The first time, we match the `&self.statement` (non-mutable reference). If you tried matching `&mut self.statement`, we get a compiler error, because inside the match statement we access `& mut self` (e.g. in `self.bind_cql_value`). This `if let ... = &mut self.statement` is a smart trick by @wprzytula. It allows us to handle everything inside the `match` statement in a way so compiler does not complain anymore - we reduce the mutability scope of `&mut self.statement`.

2024-12-03 19:00 UTC, muzarski commented on scylla-rust-wrapper/src/statement.rs
> +}
At the time I was writing this code, we did not have a `thiserror` dependency in cpp-rust-driver. I thought that it was not worth introducing it for this use-case. However, https://github.com/scylladb/cpp-rust-driver/pull/206 introduced `thiserror` dependency.

This is a good observation. I'll adjust it, so we use `thiserror` here.

2024-12-03 19:19 UTC, Lorak-mmk commented on scylla-rust-wrapper/src/statement.rs
> +                        }
In that case you could use use `let ... = ... { something} else {panic...}` to show the intent better.
1. This removes the confusion of "if"
2. Its better to panic than silently do the wrong thing

cc: @wprzytula

2024-12-03 23:32 UTC, muzarski commented on scylla-rust-wrapper/src/statement.rs
> +    }
I really like this suggestion. Applied it locally.

2024-12-03 23:34 UTC, muzarski commented on scylla-rust-wrapper/src/statement.rs
>                      .collect();
That's what I tried to do in the first place. However, I stumbled upon the following issue: the iterator borrows from `&self`, and then we try to pass it to the function that accepts `&mut self`. The compiler obviously complains. I wonder if there is any (clean) workaround solution.

2024-12-04 00:40 UTC, muzarski commented on scylla-rust-wrapper/src/statement.rs
> +                    free_index = self.bound_values.iter().position(|v| matches!(v, Unset));
I remember investigating this. A short answer is no.

If you are interested, here is a thorough explanation:
There is an integration test that checks case insensitivity for prepared statements. Table and statement definitions:
```c
#define TABLE_FORMAT           \
  "CREATE TABLE %s ("          \
  "key timeuuid PRIMARY KEY, " \
  "a int, "                    \
  "b boolean, "                \
  "c text, "                   \
  "abc float, "                \
  "\"ABC\" float, "            \
  "\"aBc\" float"              \
  ")"

#define INSERT_CASE_SENSITIVE_FORMAT \
  "INSERT INTO %s "                  \
  "(key, abc, \"ABC\", \"aBc\") "    \
  "VALUES (?, ?, ?, ?)"
```

It means that non-pk bind markers will have following names: `abc`, `ABC` and `aBc`. 

Then there is a snippet from the test case (`ByNameTests` suite, `MultipleBinds` test case):
```c
Prepared prepared =
      session_.prepare(format_string(INSERT_CASE_SENSITIVE_FORMAT, table_name_.c_str()));
Statement statement = prepared.bind();

...

statement.bind<TimeUuid>("key", key);
statement.bind<Float>("abc", Float(1.23f)); // This should bind to columns `abc`, `ABC`, and `aBc`

...

ASSERT_EQ(Float(1.23f), row.column_by_name<Float>("\"abc\""));
ASSERT_EQ(Float(1.23f), row.column_by_name<Float>("\"ABC\""));
ASSERT_EQ(Float(1.23f), row.column_by_name<Float>("\"aBc\""));
```

There is no such test case for simple (unprepared) statements. I defined such test case, but it fails with following error:
```
Invalid query: Invalid amount of bind variables: expected 4 received 2
```

2024-12-04 00:42 UTC, muzarski commented on scylla-rust-wrapper/src/statement.rs
> +                    free_index = self.bound_values.iter().position(|v| matches!(v, Unset));
And the behaviour is the same in current (from this PR) cpp-rust-driver implementation - we get an `UnknownNamedParameterError`.

2024-12-04 00:47 UTC, muzarski commented on scylla-rust-wrapper/src/statement.rs
> +                        }
Applied the suggestion

2024-12-04 00:55 UTC, muzarski commented
v3.1: Applied some of the suggestions by @Lorak-mmk

2024-12-04 08:04 UTC, wprzytula commented on scylla-rust-wrapper/src/statement.rs
>                      .collect();
Let's have an issue about this, as I think it will require more thorough lifetime/ownership analysis.

2024-12-04 11:05 UTC, muzarski commented on scylla-rust-wrapper/src/statement.rs
>                      .collect();
https://github.com/scylladb/cpp-rust-driver/issues/214

2024-12-04 11:49 UTC, Lorak-mmk commented on scylla-rust-wrapper/src/statement.rs
> +                    free_index = self.bound_values.iter().position(|v| matches!(v, Unset));
I'm curious, do you know if it is possible to use unprepared statements in the batch in cpp-driver? I wonder how it behaves then given that named parameters are broken in batches: https://github.com/apache/cassandra/blob/3078aea1cfc70092a185bab8ac5dc8a35627330f/doc/native_protocol_v4.spec#L444-L450

2024-12-04 12:00 UTC, Lorak-mmk commented on scylla-rust-wrapper/src/statement.rs
>                      .collect();
Notice that `bind_cql_value_by_name` matches `self.statement`, then calls `bind_multiple_values_by_name` in Prepared case, which in turn calls `bind_cql_value`, which again matches `self.statement`.
This suggests to me that we should extend `Statement` enum with bind values, it would look like:
```
struct SimpleStatementWithValues {
    statement: SimpleQuery
    values: bound_values: Vec<MaybeUnset<Option<CassCqlValue>>>
}
struct PreparedStatementWithValues {
    statement: Arc<CassPrepared>
    values: bound_values: Vec<MaybeUnset<Option<CassCqlValue>>>
}

enum StatementWithParams
{
 Simple(SimpleStatementWithValues)
 Prepared(PreparedStatementWithValues)
}
```

`bind_cql_value_by_name` and `bind_cql_value` would be defined on `SimpleStatementWithValues` and `PreparedStatementWithValues`. The implementation in  `CassStatement` would match the enum and forward to them.
Now the impls of `bind_cql_value_by_name` don't need to borrow from self for match, and so are free to call another methods. This solves both this issue, and the one where I proposed `let ... = ... { something} else {panic...}`

2024-12-04 12:02 UTC, Lorak-mmk commented on scylla-rust-wrapper/src/statement.rs
>                      .collect();
📝 `PreparedStatementWithValues` is basically a `BoundStatement` - so when we introduce `BoundStatement` to Rust Driver we might be able to utilize it here.

2024-12-04 12:43 UTC, muzarski commented on scylla-rust-wrapper/src/statement.rs
>                      .collect();
Your suggestion has a lof of sense. Should I do the refactor as a part of this PR?

2024-12-04 12:48 UTC, Lorak-mmk commented on scylla-rust-wrapper/src/statement.rs
>                      .collect();
Unless it turns out to be a lot of work for some reason I don't see why not.

2024-12-04 19:05 UTC, muzarski commented on scylla-rust-wrapper/src/statement.rs
> +                    free_index = self.bound_values.iter().position(|v| matches!(v, Unset));
It's possible, but the values can only be bound by index: https://github.com/scylladb/cpp-driver/blob/master/src/batch_request.cpp#L142-L146

2024-12-05 02:49 UTC, muzarski commented
v4:
- Applied a suggestion by @Lorak-mmk. Moved `bound_values` out of `CassStatement`, to new structs `BoundSimpleQuery` and `BoundPreparedStatement`. It reduces the complexity of binding functions, as we do not have to match against `&self.statement` in multiple places.
- Defined two new integration test cases that perform by-name binding to multiple columns using the same bind marker

2024-12-05 02:53 UTC, muzarski commented on scylla-rust-wrapper/src/statement.rs
>                      .collect();
I did the refactor. This however, does not solve the issue with borrow-checker. We still try to mutate `&mut self` while iterating over an iterator that borrows from `&self` (it borrows from prepared statement's metadata).

2024-12-05 13:23 UTC, Lorak-mmk commented on scylla-rust-wrapper/src/statement.rs
>                      .collect();
It can be done like this: https://github.com/scylladb/cpp-rust-driver/compare/master...Lorak-mmk:cpp-rust-driver:enable-named-parameters-tests?expand=1
This is a PoC, probably needs more work

2024-12-05 13:57 UTC, muzarski commented on scylla-rust-wrapper/src/statement.rs
>                      .collect();
Ok, so I believe that it's out of scope of this PR

2024-12-06 18:02 UTC, Lorak-mmk commented on scylla-rust-wrapper/src/statement.rs
> +                Ok(())
This assumes that columns have corresponding name->index mapping, right?
What about a case where used bound some values by name and some others by index (so they don't have the mapping)?

How does cpp-driver handle this case?

2024-12-09 12:30 UTC, muzarski commented on scylla-rust-wrapper/src/statement.rs
> +                Ok(())
> and some others by index (so they don't have the mapping)?

It's not necessarily true that there won't be a mapping. For example, consider that user firstly binds by name: `by_name("foo", 5)`. It will store value 5 at `index 0` and remember the mapping `"foo"->0`. Now, when user calls `by_index(0, 10)`, it will overwrite the value, but will not change the name->index mapping - it is still there. So interleaving `by_name` and `by_index` calls are ok, as long as user provides mapping for each bind marker's name. If there is any missing name in `name->index` mapping, then we return `UnknownNamedParameterError`.

The behaviour I just described are cpp-driver's semantics.

2024-12-09 12:34 UTC, muzarski commented
Rebased on master

2024-12-10 11:09 UTC, Lorak-mmk commented on scylla-rust-wrapper/src/statement.rs
> +                Ok(())
I'm talking about a different case.
User creates unprepared statement with 2 bound variables.
User binds `by_name("foo", 5)`, we have mapping `"foo"->0`.
User binds `by_index(1, 37)`.

Now the value at index 1 is bound, but has no name mapping, right?
The code in your PR doesn't handle this case I think. How does cpp-driver behave?

2024-12-10 18:41 UTC, muzarski commented on scylla-rust-wrapper/src/statement.rs
> +                Ok(())
cpp-driver then ignores the value at index `1`. What cpp-driver does during serialization, is it iterates over the hashmap (their custom implementation):
```c
// Format: [<name_1><value_1>...<name_n><value_n>]
// where:
// <name> is a [string]
// <value> is a [bytes]
int32_t QueryRequest::encode_values_with_names(ProtocolVersion version, RequestCallback* callback,
                                               BufferVec* bufs) const {
  int32_t size = 0;
  for (size_t i = 0; i < value_names_->size(); ++i) {
    const Buffer& name_buf = (*value_names_)[i].buf;
    bufs->push_back(name_buf);

    Buffer value_buf(elements()[i].get_buffer());
    bufs->push_back(value_buf);

    size += name_buf.size() + value_buf.size();
  }
  return size;
}
```

For some context: `value_names_` is their implementation of hashmap (our `name_to_bound_index`). `elements()` returns the vector that stores the values (our `bound_values`).

In the case you provided, the value at index `1` will be simply ignored. This is what we do in cpp-rust-driver - we iterate over column specs, then based on them and `name_to_bound_index`, we retrieve the values (ignoring the values that do not have the mapping).

I see one issue, though...
Assume that user declared 2 parameters. Then he does:
- `by_name("foo", 5)` <- stores value 5 at index 0, remembers `"foo"->0` mapping
- `by_index(1, 19)` <- stores value 19 at index 1
- `by_name("bar", 10)` <- tries to find a free index for "bar", but does not find one! It's because we search for FIRST value that is `Unset`, but our vector is already filled (user declared 2 parameters).

In case of cpp-driver, it would overwrite the value at index 1, and remember the mapping `"bar"->1`.

I see two solutions.
1. Fix the behaviour so we are compatible with cpp-driver, and introduce some integration test for this
2. Completely drop the compatibility with cpp-driver in regards to interleaving by_name and by_index bindings.
We could introduce some "binding state" e.g.:
```rust
enum BindingState {
    Init,
    ByName,
    ByIndex { name_to_bound_index: ... },
}
```

The initial state would obviously be `BindingState::Init`. The transitions are obvious:
- Init -> ByName on first by_name bind
- Init -> ByIndex on first by_index bind
- By[Name/Index] -> Init on `cass_statement_reset_parameters`

We would return an error when user binds by name in `ByIndex` state, and vice versa.

I'm slightly leaning towards the second option, since this is safer and who knows how many edge cases there are that we haven't discovered yet.

cc: @wprzytula

2024-12-10 19:58 UTC, muzarski commented
v4.1: Thanks to @Lorak-mmk I discovered a small inconsistency between cpp-rust and cpp-driver in regards to interleaving by name and by index bindings. I fixed it (commit: `binding: adjust finding new index to cpp-driver semantics`) and introduced integration test cases that verify this (last commit). I checked that the same test cases pass for cpp-driver.

2024-12-10 19:58 UTC, muzarski commented on scylla-rust-wrapper/src/statement.rs
> +                Ok(())
I went with the first approach. Already pushed the fixes (and integration tests)

2024-12-11 13:51 UTC, Lorak-mmk approved these changes

2024-12-11 16:52 UTC, wprzytula approved these changes
I think I'd feel more safe about these changes with at least a number of unit tests of the `BoundStatement`. There are integration tests, that's true, but for some reason I tend to trust Rust unit tests targetting the specific area more.

2024-12-11 17:03 UTC, muzarski commented
> I think I'd feel more secure about these changes with at least a number of unit tests of the `BoundStatement`. There are integration tests, that's true, but for some reason I tend to trust Rust unit tests targetting the specific area more.

I think it would be possible to implement unit tests for simple queries, if I extracted another struct containing binding payload (everything from `BoundSimpleQuery` apart from `Query`). It would be possible because `Query` is not required during binding, and we could mock metadata for serialization.

However, I don't see how we could implement unit tests for prepared statements. Does rust driver allow to somehow mock `PreparedStatement` structure?

Anyhow, I'll merge it as is. There are multiple places where Rust unit tests would be useful, be currently (AFAIK), we don't have a way to mock structures from rust-driver.

2024-12-11 17:08 UTC, merged