build: generate bindings for basic types
scylladb/cpp-rs-driver pull request #188
Opened 2024-10-10 18:50 UTC by muzarski

## Motivation

All of the numeric types were for some reason defined by us in `types.rs`. We should let `bindgen` generate bindings for them.

This is what this PR does. Removes basic types definitions from `types.rs` and tells bindgen to generate bindings for these types.

## size_t
Second commit addresses the issue with `size_t` binding. There is a question regarding whether we should treat it as `usize` or not. Please, take a look at that.

## Pre-review checklist

- [x] I have split my patch into logically separate commits.
- [x] All commit messages clearly explain what they change and why.
- [x] PR description sums up the changes and reasons why they should be introduced.
- ~[ ] I have implemented Rust unit tests for the features/changes introduced.~
- ~[ ] I have enabled appropriate tests in `.github/workflows/build.yml` in `gtest_filter`.~
- ~[ ] I have enabled appropriate tests in `.github/workflows/cassandra.yml` in `gtest_filter`.~

2024-10-10 19:10 UTC, Lorak-mmk approved these changes
I think the current version of the PR is fine (meaning `size_t_is_usize` should remain false). I see it as a safer option - there is no way for C definition and our definition to diverge.

Note: now the `types.rs` file doesn't actually define any types. We should probably remove the of the definitions from it.

2024-10-10 19:14 UTC, wprzytula approved these changes
Great to see this fixed.

2024-10-10 19:16 UTC, Lorak-mmk commented
> I think the current version of the PR is fine (meaning `size_t_is_usize` should remain false). I see it as a safer option - there is no way for C definition and our definition to diverge.
> 
> Note: now the `types.rs` file doesn't actually define any types. We should probably remove the of the definitions from it.

Actually we could, for each generated module, have an entry in `lib.rs`:
```
mod generated_mod {
    include!(concat!(env!("OUT_DIR"), "/generated_mod.rs"));
}
```

That way, `lib.rs` would be the only file in which we use `include!` macro - the rest of the project could just use the modules as usual.

2024-10-10 19:40 UTC, wprzytula commented
> That way, `lib.rs` would be the only file in which we use `include!` macro - the rest of the project could just use the modules as usual.

Yes, please. I hate those `include!`s.

2024-10-11 12:32 UTC, muzarski commented
> > I think the current version of the PR is fine (meaning `size_t_is_usize` should remain false). I see it as a safer option - there is no way for C definition and our definition to diverge.
> > Note: now the `types.rs` file doesn't actually define any types. We should probably remove the of the definitions from it.
> 
> Actually we could, for each generated module, have an entry in `lib.rs`:
> 
> ```
> mod generated_mod {
>     include!(concat!(env!("OUT_DIR"), "/generated_mod.rs"));
> }
> ```
> 
> That way, `lib.rs` would be the only file in which we use `include!` macro - the rest of the project could just use the modules as usual.

Done. Adjusted the names of some of the generated .rs files as well.

2024-10-11 13:35 UTC, Lorak-mmk requested changes

2024-10-11 13:35 UTC, Lorak-mmk commented on scylla-rust-wrapper/src/lib.rs
>      pub static ref LOGGER: RwLock<Logger> = RwLock::new(Logger {
I'm not a fun of introducing this. "misc" is like "utils" - a pleace for people to put stuff when they don't want to think about where the proper place would be.

2024-10-11 13:35 UTC, Lorak-mmk commented on scylla-rust-wrapper/src/lib.rs
>  lazy_static! {
There was a file generated for batch types, which you put into "misc", but here you retain the module for compression types. Why?
Can't we retain both?

2024-10-11 13:44 UTC, muzarski commented on scylla-rust-wrapper/src/lib.rs
>      pub static ref LOGGER: RwLock<Logger> = RwLock::new(Logger {
Yeah, I'm gonna be honest that I wasn't able to come up with a proper name for this module. But I'm sure it should not be called `cppdriver_data_query_error` as it was previously. Maybe we should decouple it into multiple modules. Do you have any suggestions?

2024-10-11 13:46 UTC, muzarski commented on scylla-rust-wrapper/src/lib.rs
>      pub static ref LOGGER: RwLock<Logger> = RwLock::new(Logger {
How it looks in rust-driver:
- `Consistency` is defined in `scyla-cql::frame::types.rs`
- `WriteType` is defined in `scylla_cql::frame::response::error.rs`
- `BatchType` is defined in `scylla_cql::frame::request::batch.rs`

2024-10-11 13:47 UTC, muzarski commented on scylla-rust-wrapper/src/lib.rs
>      pub static ref LOGGER: RwLock<Logger> = RwLock::new(Logger {
I think the most reasonable approach would be to introduce a separate module for each type. WDYT?

2024-10-11 13:53 UTC, Lorak-mmk commented on scylla-rust-wrapper/src/lib.rs
>      pub static ref LOGGER: RwLock<Logger> = RwLock::new(Logger {
Makes sense

2024-10-14 11:41 UTC, muzarski commented
v2: Created `cass_consistency_types` and `cass_batch_types` module (instead of having common `cass_misc_types` module). Moved `CassWriteType` to `cass_error_types` module.

2024-10-14 11:46 UTC, Lorak-mmk commented on scylla-rust-wrapper/build.rs
>          &out_path,
Is `CassWriteType` an error?

2024-10-14 11:48 UTC, muzarski commented on scylla-rust-wrapper/build.rs
>          &out_path,
It is only used in server errors. In rust-driver, `CassWriteType` is defined in a module corresponding to server errors as well.

2024-10-14 11:52 UTC, Lorak-mmk approved these changes

2024-10-15 13:45 UTC, wprzytula approved these changes

2024-10-15 13:45 UTC, wprzytula commented on scylla-rust-wrapper/src/lib.rs
> +    include!(concat!(env!("OUT_DIR"), "/basic_types.rs"));
Possible micro-enhancement: maybe we could introduce a macro, e.g. `include_bindgen_generated(filename)`, that would do the concatenation with `OUT_DIR` underneath? Just not to repeat ourselves everywhere we include such a file.

2024-10-15 15:37 UTC, muzarski commented
Rebased on main. I'll apply @wprzytula 's suggestion in the next push

2024-10-15 16:06 UTC, wprzytula approved these changes

2024-10-15 16:23 UTC, merged