lbp: rack awareness
scylladb/cpp-rs-driver pull request #195
Opened 2024-10-17 13:21 UTC by muzarski

Fix: https://github.com/scylladb/cpp-rust-driver/issues/156
See: https://github.com/scylladb/cpp-driver/pull/73

## Changes
Implemented `cass_[cluster/exeuction_profile]_set_load_balance_rack_aware[_n]`. Adjusted the documentation, and extended unit tests for API related to LBP.

## Important note about documentation and default behaviour of rack aware policy
I removed this part of the docstring:
```
 * With empty local_rack and local_dc,  default local_dc and local_rack
 * is chosen from the first connected contact point,
 * and no remote hosts are considered in query plans.
 * If relying on this mechanism, be sure to use only contact
 * points from the local rack.
```

There are multiple reasons for this:
- this behaviour does not make much sense, and we should not mimic it IMO
- rust-driver does not behave like this
- this is not even true for cpp-driver

Why it's not true for cpp-driver:
If you carefully study the changes introduced to cpp-driver in the aforementioned
commit, you will notice that it's not possible for the driver to use rack aware
policy with an empty strings. This is because API functions reject
empty string, thus RackAwarePolicy object is never constructed in such case.
```
CassError cass_cluster_set_load_balance_rack_aware_n(CassCluster* cluster, const char* local_dc,
                                                   size_t local_dc_length,
                                                   const char* local_rack,
                                                   size_t local_rack_length) {
  if (local_dc == NULL || local_dc_length == 0 || local_rack == NULL || local_rack_length == 0) {
    return CASS_ERROR_LIB_BAD_PARAMS;
  }
  cluster->config().set_load_balancing_policy(new RackAwarePolicy(
      String(local_dc, local_dc_length), String(local_rack, local_rack_length)));
  return CASS_OK;
}
```

Why is this part of docstring included in cpp-driver then? No idea. Maybe,
because `cass_cluster_set_load_balance_dc_aware` mentions something similar
for empty (non-specified) dc. However, in this case it's true, since dc awareness is enabled
by default in cpp-driver. See the docstring:
```
 * Configures the cluster to use DC-aware load balancing.
 * For each query, all live nodes in a primary 'local' DC are tried first,
 * followed by any node from other DCs.
 *
 * <b>Note:</b> This is the default, and does not need to be called unless
 * switching an existing from another policy or changing settings.
 * Without further configuration, a default local_dc is chosen from the
 * first connected contact point, and no remote hosts are considered in
 * query plans. If relying on this mechanism, be sure to use only contact
 * points from the local DC.
```

## Default node location preference
Cpp-driver, is dc-aware by default. This is not true for rust-driver, and probably will never be. In rust-driver, by default there are no node location preferences. I adjusted the documentation of `cass_cluster_set_load_balance_dc_aware` by removing the mention of dc awareness being enabled by default.

## Pre-review checklist

- [x] I have split my patch into logically separate commits.
- [x] All commit messages clearly explain what they change and why.
- [x] PR description sums up the changes and reasons why they should be introduced.
- [x] I have implemented Rust unit tests for the features/changes introduced.
- ~[ ] I have enabled appropriate tests in `.github/workflows/build.yml` in `gtest_filter`.~
- ~[ ] I have enabled appropriate tests in `.github/workflows/cassandra.yml` in `gtest_filter`.~

2024-10-17 13:49 UTC, Lorak-mmk requested changes

2024-10-17 13:49 UTC, Lorak-mmk commented on scylla-rust-wrapper/src/cluster.rs
> +        } else if let Some(dc_awareness) = self.dc_awareness {
When I see a comment like this the immediate first thought is: maybe this should be an enum, to handle this on type level instead of in runtime?

Right now the semantics are different than cpp-driver in an edge case: if you set dc aware, then rack aware, then dc aware again, cpp driver would use dc aware, but this would use rack aware.

2024-10-17 13:49 UTC, Lorak-mmk commented on include/cassandra.h
>   * replication factor number of nodes failing and the full cluster failing. Only
I generally dislike the machanism of using first contact point DC as local DC (/rack), but I wonder if this won't cause compatibility issues.

We could probably implement it by, in case dc name is empty, following mechanism:
- After session is connected check the DC of first contact point
- Then create new LBP with this DC set as local
- Swap it in session using something like this:
```rust
let handle = session.get_default_execution_profile_handle().clone();
let new_profile = handle.pointee_to_builder().load_balancing_policy(...).build();
handle.map_to_another_profile(new_profile);
```

I'm not sure preserving this mechanism is worth introducing such trickery - probably not.

2024-10-17 13:54 UTC, muzarski commented on scylla-rust-wrapper/src/cluster.rs
> +        } else if let Some(dc_awareness) = self.dc_awareness {
> Right now the semantics are different than cpp-driver in an edge case: if you set dc aware, then rack aware, then dc aware again, cpp driver would use dc aware, but this would use rack aware.

This scenario convinced me. I'll apply the suggestion (an enum) and introduce a test for this specific edge case.

2024-10-17 14:26 UTC, muzarski commented
v2: Introduced `NodeLocationPreferences` enum. Removed `DcAwareness` and `RackAwareness` structs.

2024-10-17 14:32 UTC, wprzytula requested changes

2024-10-17 14:32 UTC, wprzytula commented on scylla-rust-wrapper/src/cluster.rs
>          }
That's my boy! (that's I believe the best translation of Polish "Moja krew!") :smile:

2024-10-17 14:32 UTC, wprzytula commented on include/cassandra.h
> +/**
This is error-prone that we have two instances of `cassandra.h`. Let's try to unify them; it's too easy to make them differ.

2024-10-17 14:32 UTC, wprzytula commented on scylla-rust-wrapper/src/cluster.rs
> +        // Prioritize rack awareness if user for some reason set both rack+dc and dc preferencies.
preferencies -> preferences

2024-10-17 14:32 UTC, wprzytula commented on scylla-rust-wrapper/src/cluster.rs
> +        // One of them is either null pointer, is an empty string or is not a proper utf-8.
nit: `is either null pointer` -> `either is a null pointer`

2024-10-17 14:32 UTC, wprzytula commented on include/cassandra.h
> + * cluster load balancing policy is used when profile does not contain a policy.
How can we make a profile contain a load balancing policy? This is unclear to me from this docstring; is it clear from some other documentation?

2024-10-17 14:32 UTC, wprzytula commented on include/cassandra.h
>   * replication factor number of nodes failing and the full cluster failing. Only
Wow! Is it going to be the first time when profile mapping feature is actually useful (and used by anyone!) ?

2024-10-17 14:32 UTC, wprzytula commented on scylla-rust-wrapper/src/cluster.rs
> +                            "rack1\0".as_ptr() as *const i8,
Let's use C str literals, as they've been stabilised: https://doc.rust-lang.org/nightly/edition-guide/rust-2021/c-string-literals.html

2024-10-17 14:32 UTC, wprzytula commented on scylla-rust-wrapper/src/cluster.rs
> +                            "eu\0".as_ptr() as *const i8,
ditto: C str

2024-10-17 14:33 UTC, wprzytula commented on include/cassandra.h
> +/**
(ofc out of scope of this PR)

2024-10-17 14:35 UTC, muzarski commented on include/cassandra.h
> +/**
There is an issue regarding it https://github.com/scylladb/cpp-rust-driver/issues/116. I haven't investigated it yet - I'm not exactly sure, but it looks like currently we need both of them, i.e. we can't simply remove one of them without making any additional adjustments.

2024-10-17 14:37 UTC, Lorak-mmk commented on include/cassandra.h
>   * replication factor number of nodes failing and the full cluster failing. Only
As I said, I'm not convinced we should do this - actually, I'm more and more convinced that we shouldn't. So unfortunately it won't :(

2024-10-17 14:40 UTC, wprzytula commented on include/cassandra.h
> +/**
What about symlinks?

2024-10-17 14:41 UTC, muzarski commented on include/cassandra.h
> + * cluster load balancing policy is used when profile does not contain a policy.
cpp-rust-driver's session wrapper additionally holds a map of execution profiles, indexed by their custom names. You can firstly construct a profile, and provide custom options to it, and then pass it to `CassCluster` via `cass_cluster_set_execution_profile` with a name chosen for this profile.

Then, having multiple execution profiles defined and stored (each with unique name), you can "bind" one of your choice to some statement (see `cass_statement_set_execution_profile`), identifying the chosen profile by its name.

2024-10-17 14:47 UTC, muzarski commented on include/cassandra.h
> +/**
I'll try it out.

2024-10-17 15:05 UTC, muzarski commented on include/cassandra.h
> +/**
Looks good. Build is successful: https://github.com/scylladb/cpp-rust-driver/pull/196

2024-10-17 15:15 UTC, muzarski commented on scylla-rust-wrapper/src/cluster.rs
> +        // Prioritize rack awareness if user for some reason set both rack+dc and dc preferencies.
Comment removed after refactor introducing `NodeLocationPreference`.

2024-10-17 15:29 UTC, muzarski commented on scylla-rust-wrapper/src/cluster.rs
> +                            "rack1\0".as_ptr() as *const i8,
Done. BTW, I cannot replace `let empty_str = "\0".as_ptr() as *const i8;` with `let empty_str = c"";` It results in a following `ntest::timeout` proc macro panic:

```
error: custom attribute panicked
   --> src/cluster.rs:884:5
    |
884 |     #[ntest::timeout(100)]
    |     ^^^^^^^^^^^^^^^^^^^^^^
    |
    = help: message: Unrecognized literal: `c""`
```

It happens for any c str literal constructed outside of some other macro (e.g. `assert_cass_error_eq`).

2024-10-17 17:52 UTC, wprzytula commented on include/cassandra.h
> + * cluster load balancing policy is used when profile does not contain a policy.
I know the mechanism you described, it was me who implemented it :)
The thing is, what does it mean that a profile contains a policy?

2024-10-17 17:52 UTC, wprzytula commented on scylla-rust-wrapper/src/cluster.rs
> +                            "rack1\0".as_ptr() as *const i8,
Oh, maybe you should open an issue to `ntest`?

2024-10-21 11:11 UTC, muzarski commented on include/cassandra.h
> + * cluster load balancing policy is used when profile does not contain a policy.
Ok, now I understand your question. So I studied the logic of cpp-driver, and it seems that this statement is true for cpp-driver. See: https://github.com/scylladb/cpp-driver/blob/master/src/request_processor.cpp#L196-L209

If user does not define an LBP for execution profile (i.e. exec profile does not CONTAIN lbp), then the session-wide LBP is used for this execution profile. So it means, we are inconsistent with cpp-driver. Consider following scenario:
- user sets session-wide LBP to dc aware: `cass_cluster_set_load_balance_dc_aware(...)`
- user creates some exeuction profile, but does not define LBP for it (let's call this exec profile "foo")
- now, when user executes a statement with a "foo" exec profile:
  - in cpp-driver, the session-wide DC-aware LBP is chosen for this statement execution
  - in cpp-rust-driver/rust-driver, the `DefaultPolicy::default()` is always chosen, no matter what session-wide LBP is set to

I believe that if we wanted to mimic this behaviour, then it's relatively easy to implement - no changes to `rust-driver` are required. The question is, however, whether we want to mimic such behaviour?

cc: @Lorak-mmk

2024-10-21 11:27 UTC, Lorak-mmk commented on include/cassandra.h
> + * cluster load balancing policy is used when profile does not contain a policy.
I don't see anything wrong with such behavior. It actually seems quite useful - if you want to overwrite some things (e.g. CL and timeout) for some statements but don't want to overwrite everything. As this behavior is not buggy / footgun etc I see no reason to change it.


Actually I didn't even know that Rust Driver worked this way, I thought it behaved like cpp-driver in this regard :D

2024-10-21 13:37 UTC, muzarski commented on include/cassandra.h
> + * cluster load balancing policy is used when profile does not contain a policy.
Opened a PR: https://github.com/scylladb/cpp-rust-driver/pull/197

2024-10-21 17:12 UTC, wprzytula commented on include/cassandra.h
> + * cluster load balancing policy is used when profile does not contain a policy.
> Actually I didn't even know that Rust Driver worked this way, I thought it behaved like cpp-driver in this regard :D

I can vaguely remember that we decided that overriding the global per-session execution only partly with per-statement exec profile is too complex (for a user). A profile should be considered a full configuration. If only some options are to be changed for a statement compared to the session globally, it's adviced to derive an execution profile - either by cloning the builder beforehand or by calling `to_builder()` on an existing profile.

2024-10-24 10:49 UTC, muzarski commented
v2.1: rebased on master. (now there is only one `cassadra.h` header.

Still waiting for: https://github.com/scylladb/cpp-rust-driver/pull/197

2024-11-18 20:42 UTC, muzarski commented
v3: Rebased on master, and addressed all comments. Moving out of draft, since it's ready for review again.

2024-11-18 21:04 UTC, Lorak-mmk requested changes

2024-11-18 21:04 UTC, Lorak-mmk commented on include/cassandra.h
Commit: " cluster: define and implement cass_cluster_set_load_balance_rack_aware[_n]"

Nit: First line of commit message is too long which causes GH to display it badly. I think you can drop "define and".

After reading the commit message, I wonder - do we handle DC aware like cpp-driver? Meaning that we treat first contact point as local DC. If not, should we even try? Or just remove this from docs?

2024-11-18 21:04 UTC, Lorak-mmk commented on include/cassandra.h
Ah, I see you removed it in the third commit. Maybe we should have an issue to discuss this? I'm generally all for improving weird behavior of cpp-driver, even if the change would be slightly breaking. In this case I wonder if it isn't too breaking. Isn't this something that users could depend on?

I guess providing a migration guide could be an option? That would still benefit from an issue so we don't forget about this incompatibility.

2024-11-19 16:32 UTC, muzarski commented on include/cassandra.h
Opened an issue: https://github.com/scylladb/cpp-rust-driver/issues/204

2024-11-19 16:35 UTC, muzarski commented
v3.1: fixed commit titles and opened and issue regarding default local DC

2024-11-19 17:30 UTC, Lorak-mmk approved these changes

2024-11-20 13:44 UTC, merged