exec_profile: Use cluster lbp for exec profiles by default
scylladb/cpp-rs-driver pull request #197
Opened 2024-10-21 13:34 UTC by muzarski

The documentation of `cass_execution_profile_set_load_balance_...` functions states:
```
 <b>Note:</b> Profile-based load balancing policy is disabled by default.
 cluster load balancing policy is used when profile does not contain a policy.
```
It seems to be true, see: https://github.com/scylladb/cpp-driver/blob/master/src/request_processor.cpp#L196-L209.

We should adjust cpp-rust-driver so it behaves the same way.

This PR consist mostly of some refactor commits that prepare for the logic change in the last commit.

## Pre-review checklist

- [x] I have split my patch into logically separate commits.
- [x] All commit messages clearly explain what they change and why.
- [x] PR description sums up the changes and reasons why they should be introduced.
- ~[ ] I have implemented Rust unit tests for the features/changes introduced.~
- ~[ ] I have enabled appropriate tests in `.github/workflows/build.yml` in `gtest_filter`.~
- ~[ ] I have enabled appropriate tests in `.github/workflows/cassandra.yml` in `gtest_filter`.~

2024-10-21 16:13 UTC, Lorak-mmk requested changes

2024-10-21 16:13 UTC, Lorak-mmk commented on scylla-rust-wrapper/src/cluster.rs
`bp_config: move LoadBalancingKind to upper layer`:
After reading code changes and commit message it is still not clear to me why this change is necessary or helpful - please explain it in commit message.

This moves one field out of LoadBalancingConfig and it is not immediately obvious to me why: code users of `CassCluster` can access this field just as well not matter if it is in `CassCluster` or in `LoadBalancingConfig` (which is in `CassCluster`.

2024-10-21 16:13 UTC, Lorak-mmk commented on scylla-rust-wrapper/src/session.rs
>          }
Why go through all the trouble of having `default_lbp` returned from other functions instead of extracting it here using `session.get_default_execution_profile_handle().pointee_to_builder()`? It looks like the code that needs default_lbp can be moved below session creation, so it should work.

2024-10-21 16:25 UTC, muzarski commented on scylla-rust-wrapper/src/session.rs
>          }
That's what I wanted to do in the first place. However, there is no much we can do having the builder. All of its fields are private, and we don't provide any public getters for its fields.

2024-10-21 16:29 UTC, Lorak-mmk commented on scylla-rust-wrapper/src/session.rs
>          }
Huh, you are right, I'm surprised.

Maybe we should add getters for the builder? I don't see any disadvantages of that.

cc: @wprzytula

2024-10-21 16:34 UTC, muzarski commented on scylla-rust-wrapper/src/cluster.rs
That's right. We move a field from `LoadBalancingConfig` to both structs that use it: `CassCluster` and `CassExecProfile`. The reason is that cluster's LBP is not optional (and set to `LoadBalancingKind::RoundRobin` by default), while it is optional for `CassExecProfile` (transformed to `Option<LoadBalancingKind>` in last commit). We can't easily represent it while having this field in a common struct - `LoadBalancingConfig`.

Sure, we could have `LoadBalancingConfig` hold `Option<LoadBalancingKind>`, but then we would need to introduce some `unwrap()`s to the code.

If this explanation is enough, I'll update the commit message appropriately.

2024-10-21 16:40 UTC, Lorak-mmk commented on scylla-rust-wrapper/src/cluster.rs
I'm still not sure I understand.

CassCluster is only used to create Session, right?

Why can't it have `Option<...>`, and call `.unwrap_or_default` / `.unwrap_or_else` to provide default LBP during session building?

2024-10-21 16:56 UTC, muzarski commented on scylla-rust-wrapper/src/cluster.rs
Ok, then `LoadBalancingConfig::build` would look like:
```rust
    // This is `async` to prevent running this function from beyond tokio context,
    // as it results in panic due to DefaultPolicyBuilder::build() spawning a tokio task.
    pub(crate) async fn build(self) -> Arc<dyn LoadBalancingPolicy> {
        let load_balancing_kind = self
            .load_balancing_kind
            .unwrap_or(LoadBalancingKind::RoundRobin);
        let mut builder = DefaultPolicyBuilder::new().token_aware(self.token_awareness_enabled);
        if self.token_awareness_enabled {
            // Cpp-driver enables shuffling replicas only if token aware routing is enabled.
            builder =
                builder.enable_shuffling_replicas(self.token_aware_shuffling_replicas_enabled);
        }
        if let LoadBalancingKind::DcAware { local_dc } = load_balancing_kind {
            builder = builder.prefer_datacenter(local_dc).permit_dc_failover(true)
        }
        if self.latency_awareness_enabled {
            builder = builder.latency_awareness(self.latency_awareness_builder);
        }
        builder.build()
    }
```

I guess we could then adjust the logic of `CassExecProfile::build` accordingly (notice that `if let Some(...)` corresponds to optional `load_balancing_kind` contained in `LoadBalancingConfig`):
```rust
    pub(crate) async fn build(
        self,
        cluster_default_lbp: Arc<dyn LoadBalancingPolicy>,
    ) -> ExecutionProfile {
        let load_balacing = if let Some(_) = self.load_balancing_config.load_balancing_kind {
            self.load_balancing_config.build().await
        } else {
            // We don't want to call self.load_balancing_config.build()
            // as it would result in round robin lbp by default due to `unwrap_or` call inside this function.
            cluster_default_lbp
        };

        self.inner.load_balancing_policy(load_balacing).build()
    }
```

2024-10-21 16:57 UTC, muzarski commented on scylla-rust-wrapper/src/cluster.rs
So we can either use the code samples I provided, or move the field from `LoadBalancingConfig` (current version).

2024-10-21 18:02 UTC, muzarski commented on scylla-rust-wrapper/src/session.rs
>          }
It sounds fine. But I have a minor doubt about it. All of the fields of `ExecutionProfileBuilder` are optional. It results in some weird types, such as `Option<Option<Arc<dyn SpeculativeExecutionPolicy>>>`. In this case:
- `None` indicates that no spec execution policy was chosen yet, and the default one (`None` - no speculative execution) will be chosen when building
- `Some(None)` indicates that speculative execution policy has been set to None, i.e. driver will not perform a speculative execution for this profile
- `Some(Some(...))` is obvious

Does it make sense to implement a getter that returns `Option<Option<...>>`? Is it really helpful for the user? Maybe the getter should remove one layer of `Option`ness, indicating whether the field has been set in the builder, by returning default value in case the field is not set in the builder. For example:
```rust
pub fn get_speculative_execution_policy(&self) -> Option<Arc<dyn SpeculativeExecutionPolicy>> {
    self.speculative_exeuction_policy
        .clone()
        .unwrap_or_else(defaults::speculative_execution_policy)
}
```

This obviously could cost us an additional allocation if `defaults::speculative_execution_policy()` allocated an `Arc`. This is not the case here, since it returns `None`. But `defaults::[load_balancing_policy/retry_policy]()` both allocate if we wanted to follow the same approach for lbp and retry policy getters.

2024-10-22 08:49 UTC, Lorak-mmk commented on scylla-rust-wrapper/src/cluster.rs
Those snippets look good to me. Will those allow you to revert `connect: pass default LBP to connect_fut `?

2024-10-22 08:51 UTC, Lorak-mmk commented on scylla-rust-wrapper/src/session.rs
>          }
We can replace nested Option with an enum (NotSet / Fallback, Disabled, Enabled(policy).

Which I think is a good idea in general - we have several `Option<Option<...>>` in the driver and it is never obvious what they mean.

2024-10-22 08:54 UTC, muzarski commented on scylla-rust-wrapper/src/cluster.rs
For this, we need `ExecutionProfileBuilder` getters.

2024-10-22 09:04 UTC, Lorak-mmk commented on scylla-rust-wrapper/src/cluster.rs
Ok. For the getters I'd like to know what @wprzytula thinks about them.

2024-10-22 09:36 UTC, muzarski commented
v2: Reverted the changes introduced by `lbp_config: move LoadBalancingKind to upper layer` (removed this commit). Now, the `load_balancing_kind` field is optional in `LoadBalancingConfig`.

2024-10-30 12:09 UTC, muzarski commented
v3: Rebased on https://github.com/scylladb/cpp-rust-driver/pull/200. Addressed all of @Lorak-mmk comments

2024-10-30 15:59 UTC, Lorak-mmk approved these changes

2024-10-30 18:07 UTC, muzarski commented
Rebased on master

2024-11-18 20:02 UTC, merged