cluster: tracing config options
scylladb/cpp-rs-driver pull request #199
Opened 2024-10-24 15:55 UTC by muzarski

Implemented:
- `cass_cluster_set_tracing_consistency`
- `cass_cluster_set_tracing_max_wait_time`
- `cass_cluster_set_tracing_retry_wait_time`

Set the defaults for this options as well.

Notice, that we needed to make use of a small hack, since rust-driver does not expose the option to set tracing info fetch timeout. Instead, it allows user to define maximum number of retries. This can be computed based on timeout and retry interval provided by user via cpp-rust-driver API.

## Pre-review checklist

- [x] I have split my patch into logically separate commits.
- [x] All commit messages clearly explain what they change and why.
- [x] PR description sums up the changes and reasons why they should be introduced.
- ~[ ] I have implemented Rust unit tests for the features/changes introduced.`~
- ~[ ] I have enabled appropriate tests in `.github/workflows/build.yml` in `gtest_filter`.~
- ~[ ] I have enabled appropriate tests in `.github/workflows/cassandra.yml` in `gtest_filter`.~

2024-12-01 21:34 UTC, wprzytula requested changes

2024-12-01 21:34 UTC, wprzytula commented on scylla-rust-wrapper/src/cass_types.rs
>              CassConsistency::CASS_CONSISTENCY_LOCAL_QUORUM => Ok(Consistency::LocalQuorum),
typo in commit name: `CassConsistency: adjust converion to serial variants of Consistency` -> `conversion`

2024-12-01 21:34 UTC, wprzytula commented on scylla-rust-wrapper/src/cass_types.rs
> +            CassConsistency::CASS_CONSISTENCY_SERIAL => Ok(Consistency::Serial),
This is a bug fix! Let's prioritise such things more, instead of packing them into PRs with new features. Bugs should be fixed ASAP!

2024-12-01 21:34 UTC, wprzytula commented on scylla-rust-wrapper/src/cluster.rs
> +    let tracing_info_fetch_attemps = {
typo: `attemps` -> `attempts`

2024-12-01 21:34 UTC, wprzytula commented on scylla-rust-wrapper/src/cluster.rs
> +        let attemps = cluster.tracing_max_wait_time.as_millis()
ditto

2024-12-01 21:34 UTC, wprzytula commented on scylla-rust-wrapper/src/cluster.rs
> +
Could you please add a unit test for setting all tracing parameters?

2024-12-03 10:36 UTC, Lorak-mmk commented on scylla-rust-wrapper/src/cass_types.rs
> +            CassConsistency::CASS_CONSISTENCY_SERIAL => Ok(Consistency::Serial),
For a driver still in alpha packing a bugfix in a small PR like this is imo perfectly acceptable.

2024-12-03 10:48 UTC, Lorak-mmk commented on scylla-rust-wrapper/src/cluster.rs
>  // - tracing consistency is ONE
❓ 3ms is the defualt in Rust Driver. Is that the default in cpp-driver too?

2024-12-03 10:48 UTC, Lorak-mmk commented on scylla-rust-wrapper/src/cluster.rs
> +
❓ 🤔💭 What is the semantics of `cass_cluster_set_tracing_max_wait_time` in cpp-driver?
If it puts a time limit on whole tracing fetch, then this is very different to what you did.
Rust Driver, afaict, doesn't have a timeout for a single attempt - only a limit on number of attempts.
So a single attempt can take arbitrarily long time, and you assume they are instant.

Maybe a correct solution here is to wrap `get_tracing_info` calls into `tokio::time::timeout`?
Actually, what is the API in cpp-driver to retrieve tracing info? I don't see any call to `get_tracing_info`.
And if there are none, then what those parameters even do?

📌 As a side note, maybe we should add a timeout for single attempt to Rust Driver?

2025-04-30 14:30 UTC, muzarski commented on scylla-rust-wrapper/src/cluster.rs
> +
>  I don't see any call to `get_tracing_info`. And if there are none, then what those parameters even do?

Great observation - I was sure that there was already an implemented method which fetches the tracing info. There is no such method (even in cassandra.h) - cpp-driver docs say:
```
**Note**: The driver does not return the actual tracing data for the request. The
application itself must use the returned tracing identifier to query the tables.

## Configuration

By default, when tracing is enabled, the driver will wait for the query's tracing
data to become available in the server-side tables before setting the request's
future. The amount of time it will wait, retry, and the consistency level of the
tracing data can be controls by setting `CassCluster` configuration options.
```

So this is something we have to implement in cpp-rust-driver.

2026-02-26 15:08 UTC, Lorak-mmk commented
Closing this - we decided to not implement those functions, because of the weird semantics.
If we introduce support for tracing, we'll do it in a better way (for example allowing user to access the result).

2026-02-26 15:08 UTC, closed without merging