Add result functions
scylladb/cpp-rs-driver pull request #2
Opened 2021-10-21 18:02 UTC by cvybhu

Adds some basic functions needed for result handling

there are now two declarations of size_t - will fix later

2021-10-21 18:14 UTC, piodul commented on scylla-rust-wrapper/src/future.rs
> +    let future: &mut CassFuture = unsafe { future_raw.as_mut().unwrap() };
You can use `deref_ptr_mut` here

2021-10-21 18:25 UTC, piodul commented on scylla-rust-wrapper/src/query_result.rs
> +            }
Nit: bools should convert to integers with an `as` conversion:

```rust
(iter.position < rs.len()) as cass_bool_t
```

2021-10-21 18:27 UTC, piodul commented on scylla-rust-wrapper/src/query_result.rs
> +    }
Ditto

2021-10-22 09:55 UTC, Lorak-mmk requested changes
Please rebase on Piotr's PR, and mark user-facing functions as unsafe.

One question regarding iterators: how would they work with paged queries? In cppdriver, iterator will iterate over current page, not fetch next page automatically - you need to fetch next pages manually, there are functions for that,

2021-10-22 09:55 UTC, Lorak-mmk commented on scylla-rust-wrapper/src/query_result.rs
> +        CqlValue::Int(i) => *out = *i,
Don't we need to check for integer size also?

2021-10-22 09:55 UTC, Lorak-mmk commented on scylla-rust-wrapper/src/utils.rs
> +}
Rebase on top of Piotr's PR to avoid duplicating util functions

2021-10-22 09:56 UTC, cvybhu commented on scylla-rust-wrapper/src/query_result.rs
> +        CqlValue::Int(i) => *out = *i,
CqlValue has separate variants for all integer types, an int64 would be `CqlValue::BigInt` or something like that

2021-10-22 09:57 UTC, cvybhu commented
New version ready, rebased and cleaned

2021-10-22 10:01 UTC, Lorak-mmk commented on scylla-rust-wrapper/src/query_result.rs
> +// This was const for some reason, seems like a mistake in cpp driver
It's not a mistake - dec_ref is marked as const, because ref counter is marked as mutable, so in C it can be const. Here we probably need to remove this const as you did.

2021-10-22 10:02 UTC, Lorak-mmk approved these changes

2021-10-22 10:17 UTC, piodul approved these changes
Left some very tiny nits, looks good otherwise.

2021-10-22 10:17 UTC, piodul commented on scylla-rust-wrapper/src/query_result.rs
> +    };
Super tiny nit: this could be written as follows:

```rust
row.columns.get(index_usize).unwrap_or(std::ptr::null())
```

2021-10-22 10:17 UTC, piodul commented on scylla-rust-wrapper/src/query_result.rs
> +    row
Super tiny nit: rewrite this as follows:

```rust
iter.result.rows.as_ref().and_then(|rs| rs.get(iter.position)).unwrap_or(std::ptr::null());
```

2021-10-22 10:34 UTC, merged