cargo: point to rust-driver 07553fee
scylladb/cpp-rs-driver pull request #200
Opened 2024-10-28 13:36 UTC by muzarski

Currently, there are some open PRs that depend on changes recently introduced to rust-driver.
Let's bump the version of rust-driver dependency.

## Pre-review checklist

- [x] I have split my patch into logically separate commits.
- [x] All commit messages clearly explain what they change and why.
- [x] PR description sums up the changes and reasons why they should be introduced.
- ~[ ] I have implemented Rust unit tests for the features/changes introduced.~
- ~[ ] I have enabled appropriate tests in `.github/workflows/build.yml` in `gtest_filter`.~
- ~[ ] I have enabled appropriate tests in `.github/workflows/cassandra.yml` in `gtest_filter`.~

2024-10-28 13:40 UTC, Lorak-mmk commented on scylla-rust-wrapper/src/query_result.rs
> +
When is this called? On each query?

2024-10-28 14:09 UTC, wprzytula requested changes

2024-10-28 14:09 UTC, wprzytula commented on scylla-rust-wrapper/src/query_result.rs
> +            .collect();
I haven't included `ColumnSpec::into_owned` on purpose: it would be inefficient, as another Vec would have to be allocated.
This shouldn't be needed; the `ColumnSpec` stored in `QueryResult` (soon `LegacyQueryResult`) is `'static`.
Actually, there is a bug in `QueryResult`:
```rust
pub fn col_specs(&self) -> &[ColumnSpec] {
```

...while it should be:
```rust
pub fn col_specs(&self) -> &[ColumnSpec<'static>] {
```

2024-10-28 14:09 UTC, wprzytula commented on scylla-rust-wrapper/src/query_result.rs
> +        col_specs: &[ColumnSpec],
```suggestion
        col_specs: &[ColumnSpec<'static>],
```

2024-10-28 14:09 UTC, wprzytula commented on scylla-rust-wrapper/src/query_result.rs
> +
Yes, unfortunately. But soon it will be irrelevant, when we switch to new `QueryResult` with its `RowDeserializerOwned`.

2024-10-28 14:09 UTC, muzarski commented on scylla-rust-wrapper/src/query_result.rs
> +
Yeah... It's because current `QueryResult` API is in awkward state.

The main issue is that ColumnSpec lifetime is bound by lifetime of result:
```rust
    /// Returns column specifications.
    #[inline]
    pub fn col_specs(&self) -> &[ColumnSpec] {
        self.metadata
            .as_ref()
            .map(|metadata| metadata.col_specs())
            .unwrap_or_default()
    }
```

This is equivalent to:
```rust
pub fn col_specs<'s>(&'s self) -> &'s [ColumnSpec<'s>]
```
even though this version of `QueryResult` holds metadata consisting of `ColumnSpec<'static>` (owned column specs). To return `&[ColumnSpec<'static>]`, we also need fix introduced by this commit: https://github.com/scylladb/scylla-rust-driver/pull/1093/commits/e53a92c1721738dce4a6a4d257e5e0e48edaee21

Then we wouldn't need to call this `map` in cpp-rust-driver:
```rust
  .map(|col_spec| {
      // TODO: introduce ColumnSpec::[in]to_owned() methods in rust-driver.
      let name = col_spec.name().to_owned();
      let typ = col_spec.typ().clone().into_owned();
      let table_spec = col_spec.table_spec().to_owned();
      ColumnSpec::owned(name, typ, table_spec)
  })
```

I could open a small PR in rust-driver that does that (so we get rid of this mapping from borrowed col spec to owned col spec). This would be a temporary fix, before the final version of `QueryResult` is introduced in rust-driver.

As a side note: I believe that once final version of lazy deserialization is merged, the corresponding structures in cpp-rust-driver will need to be adjusted/refactored appropriately so we are as efficient as we can.

2024-10-28 14:10 UTC, muzarski commented on scylla-rust-wrapper/src/query_result.rs
> +            .collect();
> Actually, there is a bug in `QueryResult`:
> 
> ```rust
> pub fn col_specs(&self) -> &[ColumnSpec] {
> ```
> 
> ...while it should be:
> 
> ```rust
> pub fn col_specs(&self) -> &[ColumnSpec<'static>] {
> ```

Yes, that's what I mentioned in response to @Lorak-mmk 's comment.

2024-10-28 14:12 UTC, muzarski commented on scylla-rust-wrapper/src/query_result.rs
> +        col_specs: &[ColumnSpec],
This also needs adjustment in `QueryResult::col_specs()`, so it returns `&[ColumnSpec<'static>]`

2024-10-28 14:42 UTC, muzarski commented
v1.1: In rust-driver, we changed an error message emitted when statement id changes after repreparation. I adjusted the corresponding intergration test (`PreparedTests.Integration_Cassandra_FailFastWhenPreparedIDChangesDuringReprepare`) to this new error message.

2024-10-28 14:58 UTC, muzarski commented
v2: Adjusted to https://github.com/scylladb/scylla-rust-driver/commit/da199a182e0ab95efd2caae495ad3583f09bdd85. Now there is no need to convert `ColumnSpec<'query_result>` to `ColumnSpec<'static>`

2024-10-28 14:59 UTC, muzarski commented on scylla-rust-wrapper/src/query_result.rs
> +        col_specs: &[ColumnSpec],
I reverted the change (from accepting `Vec<...>` to accepting slice), so now we accept `Vec<ColumnSpec<'static>>`

2024-10-30 12:03 UTC, muzarski commented
v2.1: Bumped again to https://github.com/scylladb/scylla-rust-driver/commit/64b4afcdb4286b21f6cc1acb55266d6607f250e0

2024-10-30 14:25 UTC, Lorak-mmk requested changes

2024-10-30 14:25 UTC, Lorak-mmk commented on scylla-rust-wrapper/src/cass_types.rs
>          ColumnType::Ascii => CassDataType::Value(CassValueType::CASS_VALUE_TYPE_ASCII),
`s` is a `&String`, right? So why do we need both `.clone()` and `.into_owned()`? Isn't one of those enough?

2024-10-30 14:25 UTC, Lorak-mmk commented on scylla-rust-wrapper/src/cass_types.rs
> +                })
ditto

2024-10-30 14:25 UTC, Lorak-mmk commented on scylla-rust-wrapper/src/cass_types.rs
> +            name: type_name.clone().into_owned(),
ditto

2024-10-30 14:25 UTC, Lorak-mmk commented on scylla-rust-wrapper/src/exec_profile.rs
> +        DowngradingConsistencyRetryPolicy(downgrading) => downgrading.clone(),
Please use `Arc::clone` if you need to clone `Arc`. `.clone` is less obvious.

2024-10-30 14:32 UTC, muzarski commented on scylla-rust-wrapper/src/cass_types.rs
>          ColumnType::Ascii => CassDataType::Value(CassValueType::CASS_VALUE_TYPE_ASCII),
`s` is `&Cow<'_, str>`. We need to `clone` the `Cow` and then convert it to `String`.

2024-10-30 14:38 UTC, muzarski commented on scylla-rust-wrapper/src/cass_types.rs
>          ColumnType::Ascii => CassDataType::Value(CassValueType::CASS_VALUE_TYPE_ASCII),
`str::to_owned(s)` or `s.to_string()` seems to work as well. In case you prefer something shorter compared to current version. Notice that `s.to_owned()` returns an owned `Cow` (not `String`).

2024-10-30 14:50 UTC, muzarski commented
v2.2: replaced `.clone()` with `Arc::clone()` and rebased on master

2024-10-30 15:04 UTC, Lorak-mmk commented on scylla-rust-wrapper/src/cass_types.rs
>          ColumnType::Ascii => CassDataType::Value(CassValueType::CASS_VALUE_TYPE_ASCII),
> `s` is `&Cow<'_, str>`. We need to `clone` the `Cow` and then convert it to `String`.

I didn't realize that. In that case the current version is fine.

2024-10-30 15:04 UTC, Lorak-mmk approved these changes

2024-10-30 16:40 UTC, wprzytula approved these changes

2024-10-30 16:48 UTC, merged