type safety: ffi pointer manipulation API
scylladb/cpp-rs-driver pull request #207
Opened 2024-11-25 19:25 UTC by muzarski

## Pre-review checklist

- [ ] I have split my patch into logically separate commits.
- [ ] All commit messages clearly explain what they change and why.
- [ ] PR description sums up the changes and reasons why they should be introduced.
- [ ] I have implemented Rust unit tests for the features/changes introduced.
- [ ] I have enabled appropriate tests in `.github/workflows/build.yml` in `gtest_filter`.
- [ ] I have enabled appropriate tests in `.github/workflows/cassandra.yml` in `gtest_filter`.

2024-12-01 20:17 UTC, wprzytula requested changes
In general, looks good.

2024-12-01 20:17 UTC, wprzytula commented on scylla-rust-wrapper/src/cass_types.rs
> +unsafe impl Sync for CassDataType {}
Why is this needed? AFAIK, raw pointers do not implement Send nor Sync; for the same reason, I think `CassDataType` also should not, unless it's required due to some other important reasons.

2024-12-01 20:17 UTC, wprzytula commented on scylla-rust-wrapper/src/cass_types.rs
> +    }
For a moment, I was afraid that this is unsound. We're creating a `&mut` that may alias the same memory as some other accesses!
Tbh, I'm in two minds if this is sound or not.

2024-12-01 20:17 UTC, wprzytula commented on scylla-rust-wrapper/src/cass_types.rs
> +    }
Nit: I'd prefer `new_arced` as the name, as it seems more idiomatic to me.

2024-12-01 20:17 UTC, wprzytula commented on scylla-rust-wrapper/src/argconv.rs
> +    }
Nit: `as_maybe_ref` makes more sense to me. `as` is the name of the operation, and `maybe_ref` is the target of the conversion.

2024-12-01 20:17 UTC, wprzytula commented on scylla-rust-wrapper/src/argconv.rs
> +// }
Nit: let's delete those lines instead of commenting them out in this commit.

2024-12-02 13:08 UTC, muzarski commented on scylla-rust-wrapper/src/cass_types.rs
> +    }
Before that, we would create a `&mut` directly from a pointer passed to the function. With new approach, we are more explicit, and the user needs to wrap the call with an `unsafe` block. Is it sound? Well, it's the caller's responsibility to ensure the soundness.

2024-12-02 14:29 UTC, muzarski commented
Rebased on master

2024-12-02 14:57 UTC, muzarski commented on scylla-rust-wrapper/src/cass_types.rs
> +unsafe impl Sync for CassDataType {}
There are multiple places in the code where the compiler complains when I comment it out. One of them is the place where we define types with a static lifetime - an optimization for untyped collections/tuples. There are also some types that are indirect owners of `CassDataType`, and are passed to an async block which is required to be `Send`.

2024-12-02 14:58 UTC, muzarski commented
v2: addressed @wprzytula comments

2024-12-04 12:07 UTC, wprzytula approved these changes

2024-12-04 13:20 UTC, Lorak-mmk commented on scylla-rust-wrapper/src/cass_types.rs
>      type_name_length: size_t,
❓ Can you remind me / cite some source on what are the semantics of `*mut` vs `*const`? `CassDataType* data_type` is used on C side, which is not a const object, right? If that is the case, why do we use `*const` here?

2024-12-04 13:20 UTC, Lorak-mmk commented on scylla-rust-wrapper/src/cass_types.rs
>      type_name_length: size_t,
This applied to other places where `*mut` was changed to `*const`.

2024-12-04 13:28 UTC, wprzytula commented on scylla-rust-wrapper/src/cass_types.rs
>      type_name_length: size_t,
The semantics of `*const` means that no one is going to modify the pointee through the pointer. Here, this is **not** the case.

2024-12-04 13:31 UTC, Lorak-mmk commented on scylla-rust-wrapper/src/cass_types.rs
>      type_name_length: size_t,
What does modify mean? Let's say we get a `*const Mutex<something>`. Are we allowed to lock the mutex and modify its contents?

2024-12-04 13:42 UTC, wprzytula commented on scylla-rust-wrapper/src/cass_types.rs
>      type_name_length: size_t,
_Modify_ on structs is defined by induction, by modifying one of its fields. And _modyfing_ a value of a primitive type involves changing bits of their memory representation.

However, _interior mutability_ is what makes an exception: if a type allows for _internal mutability_ (in Rust, it basically means that it holds an `UnsafeCell`), then mutation inside that type are not considered mutation from outside. So answering your question, we are allowed to lock the Mutex through `*const Mutex`.

2024-12-04 18:16 UTC, muzarski commented on scylla-rust-wrapper/src/cass_types.rs
>      type_name_length: size_t,
I believe that Wojciech answered your question. Notice, that all these `*const` and `*mut` will not matter after a follow-up PR, since raw pointers are going to be replaced by our new type representing a pointer.

2024-12-06 17:28 UTC, Lorak-mmk approved these changes

2024-12-09 12:23 UTC, merged