safety: introduce pointer types and their restrictions
scylladb/cpp-rs-driver pull request #208
Opened 2024-11-26 15:47 UTC by muzarski

## Pre-review checklist

- [ ] I have split my patch into logically separate commits.
- [ ] All commit messages clearly explain what they change and why.
- [ ] PR description sums up the changes and reasons why they should be introduced.
- [ ] I have implemented Rust unit tests for the features/changes introduced.
- [ ] I have enabled appropriate tests in `.github/workflows/build.yml` in `gtest_filter`.
- [ ] I have enabled appropriate tests in `.github/workflows/cassandra.yml` in `gtest_filter`.

2024-12-01 21:20 UTC, wprzytula requested changes
The approach is very impressive.
I couldn't check all the changes, there were too much of them; I just peeked through them. I trust your meticulousness :)

2024-12-01 21:20 UTC, wprzytula commented on scylla-rust-wrapper/src/collection.rs
> +lazy_static! {
I've seen that [LazyLock](https://doc.rust-lang.org/beta/std/sync/struct.LazyLock.html) is already stable. Maybe it's better to transition to it instead of an external `lazy_static` dependency?

2024-12-01 21:20 UTC, wprzytula commented on scylla-rust-wrapper/src/collection.rs
> +            cass_data_type_free(empty_set_dt as *mut _)
I think this mentioned comment in `cass_data_type_new` is not yet there in this commit (`collection: allocate static empty collections`).

2024-12-01 21:20 UTC, wprzytula commented on scylla-rust-wrapper/src/metadata.rs
> +    }
Why are we calling `RefFFI::as_ptr` on an `Arc`? I would expect `ArcFFI::as_ptr`.

2024-12-01 21:20 UTC, wprzytula commented on scylla-rust-wrapper/src/argconv.rs
> +pub trait Ownership: sealed::Sealed {}
This commit (`argconv: pointers`) misses description, which is much needed here for future readers to understand reasons of adding this.

2024-12-01 21:20 UTC, wprzytula commented on scylla-rust-wrapper/src/argconv.rs
> +pub type CassSharedPtr<T> = CassPtr<T, (Shared, Const)>;
Maybe let's point to the `CassDataType` here, so that future readers can reach there for a reference on how to provide sound interior mutability to `CassSharedPtr` semantics?

2024-12-01 21:20 UTC, wprzytula commented on scylla-rust-wrapper/src/argconv.rs
> +    unsafe fn into_ref<'a>(self) -> Option<&'a T> {
Converts

2024-12-01 21:20 UTC, wprzytula commented on scylla-rust-wrapper/src/argconv.rs
> +    fn new(b: Box<T>) -> Self {
I'm not sure about this suggestion, because I haven't seen usage yet, but my idea is:
Wouldn't `from_box` be clearer about what's expected here instead of a generic `new`? With the constructor named `new` for every `CassPtr` instantiation but accepting different arguments, this may resemble the loathed (at least by me) method overloading (which adds complexity to understanding things, because a method of a given name may in reality be multiple different methods).

2024-12-01 21:20 UTC, wprzytula commented on scylla-rust-wrapper/src/argconv.rs
> +    }
Does this need to be `unsafe`, if you argue in the comment that it's safe?

2024-12-01 21:20 UTC, wprzytula commented on scylla-rust-wrapper/src/argconv.rs
> +impl<T> RefFFI for T where T: FFI<Ownerhsip = OwnershipBorrowed> {}
Missing docstrings.

2024-12-01 21:20 UTC, wprzytula commented on scylla-rust-wrapper/src/argconv.rs
> +impl<T> RefFFI for T where T: FFI<Ownerhsip = OwnershipBorrowed> {}
At least `FFI` should be documented.

2024-12-01 21:20 UTC, wprzytula commented on scylla-rust-wrapper/src/argconv.rs
> +    type Ownerhsip;
typo: `Ownerhsip` -> `Ownership`.

2024-12-02 15:05 UTC, muzarski commented
Rebased on master

2024-12-02 15:32 UTC, muzarski commented on scylla-rust-wrapper/src/collection.rs
> +lazy_static! {
Good point. Please, see: https://github.com/scylladb/cpp-rust-driver/pull/212 (removes `lazy_static` dependency altogether)

2024-12-02 16:21 UTC, muzarski commented on scylla-rust-wrapper/src/collection.rs
> +            cass_data_type_free(empty_set_dt as *mut _)
The comment was already there a long time ago:
```
// Changed return type to const ptr - ArcFFI::into_ptr is const.
// It's probably not a good idea - but cppdriver doesn't guarantee
// thread safety apart from CassSession and CassFuture.
// This comment also applies to other functions that create CassDataType.
```

However, it's going to be outdated once we migrate to new pointer types later in this PR. But your comment reminded me that I did not remove the outdated comment next to `cass_data_type_new` :).

2024-12-02 16:46 UTC, muzarski commented on scylla-rust-wrapper/src/metadata.rs
> +    }
See the implementation (and the comment):
```rust
// Either:
// - owned by CassMaterializedViewMeta - won't be given to user
// - Owned by CassKeyspaceMeta (in Arc), referenced (Weak) by CassMaterializedViewMeta
impl FFI for CassTableMeta {
    type Ownerhsip = OwnershipBorrowed;
}
```

By implementing the `RefFFI` for this type, we purposely narrow the set of functionalities exposed on the pointer type representing `CassTableMeta`. Specifically, we do not let do the following:
- convert the pointer back to `Arc` (i.e. free)
- obtain an `Arc` by cloning (increasing RC)

Thus, when implementing `RefFFI` for this type, we make a promise (expressed in Rust type system), that we do not make any assumption about the pointer (specifically, we do not care whether it was allocated via `Arc`, or it was simply obtained from some valid reference). When implementing `RefFFI`, we only care about the validity of the pointer - the fact that it can be converted to some **valid** reference.

It's exactly why `RefFFI` is a good choice for `CassTableMeta` - the user does not need to free the memory associated with the pointer (it's automatically done, when either `CassMaterializedViewMeta` or `CassKeyspaceMeta` is freed). The user also cannot clone (increase the reference count) it in any way.

The reason we store `CassTableMeta` inside an `Arc` in `CassKeyspaceMeta` (the owner), is because we want to have a weak reference to it in `CassMaterializedViewMeta`.

2024-12-02 17:02 UTC, muzarski commented on scylla-rust-wrapper/src/argconv.rs
> +    }
Good observation - adjusted remaining occurrences as well.

2024-12-02 17:02 UTC, muzarski commented on scylla-rust-wrapper/src/argconv.rs
> +    fn new(b: Box<T>) -> Self {
Applied the suggestion. Did the same for `CassSharedPtr` (`from_arc`)

2024-12-02 17:35 UTC, wprzytula commented on scylla-rust-wrapper/src/metadata.rs
> +    }
Great explanation, thank you.
I believe it deserves being put in a comment!

2024-12-02 19:32 UTC, muzarski commented
v1.1: Addressed @wprzytula comments

2024-12-02 19:39 UTC, muzarski commented on scylla-rust-wrapper/src/argconv.rs
> +impl<T> RefFFI for T where T: FFI<Ownerhsip = OwnershipBorrowed> {}
Added docs for the `FFI` trait and the structs

2024-12-04 12:09 UTC, wprzytula commented
Waiting with review for a rebase on #207.

2024-12-04 12:28 UTC, wprzytula commented on scylla-rust-wrapper/src/argconv.rs
> +/// C and Rust API. We currently distinguish 3 kinds of implementors,
:wrench: typos: `This trait should be implemented`

2024-12-04 12:38 UTC, muzarski commented
> Waiting with review for a rebase on #207.

Everything is up to date

2024-12-04 13:21 UTC, wprzytula requested changes

2024-12-04 13:21 UTC, wprzytula commented on scylla-rust-wrapper/src/argconv.rs
> +}
:question: Do you think these items can be left without docstrings? I think I'd add at least some basic ones.

2024-12-04 13:21 UTC, wprzytula commented on scylla-rust-wrapper/src/argconv.rs
> +    }
:warning: :wrench:  Contrary to what I previously said about this function not being `unsafe`, there exists a scenario that triggers UB. Namely, `Self`, being a `CassPtr`, implements `Clone`; thus, when having two copies of the same pointer, one can call `into_box` on both, causing a _double free_.

Actually, even though this method accept `self` by value, it does not consume it, because `Self: Copy`.

2024-12-04 13:44 UTC, muzarski commented on scylla-rust-wrapper/src/argconv.rs
> +    }
Wow, I'm glad you noticed that. This is obviously a bug. So my proposition would be:
- implement Copy and Clone with `#[cfg(test)]` - in unit tests we get the pointers from API functions, and we need to be able to `Copy` then (same as C API user)
- `[Box/Arc/Ref]FFI::as_ref()` should accept `&CassPtr<_, _>` instead of `CassPtr<_, _>` - this would represent an aliasing to a valid non-mutable reference. The lifetime of reference would be inherited from the lifetime of the pointer
- remaining methods, e.g. `into_box`, `into_arc`, `into_mut_ref` (aliasing ^ mutability) should consume the pointer

WDYT?

2024-12-04 14:10 UTC, wprzytula commented on scylla-rust-wrapper/src/argconv.rs
> +    }
> - implement Copy and Clone with #[cfg(test)] - in unit tests we get the pointers from API functions, and we need to be able to Copy them (same as C API user)

This unfortunately is still not sound. The `test` code must uphold to the same rules as non-`test` code, which means that safe code there must not trigger UB in any case.

> - [Box/Arc/Ref]FFI::as_ref() should accept &CassPtr<_, _> instead of CassPtr<_, _> - this would represent an aliasing to a valid non-mutable reference. The lifetime of reference would be inherited from the lifetime of the pointer
> - remaining methods, e.g. into_box, into_arc, into_mut_ref (aliasing ^ mutability) should consume the pointer

:+1 I'm fine with these ideas.

2024-12-04 14:47 UTC, muzarski commented on scylla-rust-wrapper/src/argconv.rs
> +    }
> > * [Box/Arc/Ref]FFI::as_ref() should accept &CassPtr<_, _> instead of CassPtr<_, _> - this would represent an aliasing to a valid non-mutable reference. The lifetime of reference would be inherited from the lifetime of the pointer
> > * remaining methods, e.g. into_box, into_arc, into_mut_ref (aliasing ^ mutability) should consume the pointer
> 
> 👍 I'm fine with these ideas.

There are a couple things that need to be addressed (and discussed)

## API functions accept owned pointers
This is a problem, when some API function calls other API function. For example `cass_result_paging_state_token` does something like this:
```rust
    if cass_result_has_more_pages(result) == cass_false {
        return CassError::CASS_ERROR_LIB_NO_PAGING_STATE;
    }

    ... keep on using result, but it is consumed by cass_result_has_more_pages...
```
A workaround, which in my opinion makes sense is to extract the `cass_result_has_more_pages` to some function that accepts a reference to the pointer. This should be easy - there are only a couple of places where something like this occurs.

## Sometimes, we need to "erase" the lifetime of the reference
In some cases, we do not want to inherit the lifetime from the pointer provided to the API call. In other words, the reference should be valid when function call ends. From my investigation, there are two cases:
1. When we "erase" the lifetime in iterators (i.e. cast to `'static`). This one probably will not be a problem once replace `'static` lifetimes in iterators with some named lifetimes.
2. When we pass the `CassSession` reference to some future which is required to be `'static`. For example, see the comment to `CassSessionInner::connect()`:
```rust
    fn connect(
        // This reference is 'static because this is the only was of assuring the borrow checker
        // that holding it in our returned future is sound. Ideally, we would prefer to have
        // the returned future's lifetime constrained by real lifetime of the session's RwLock,
        // but this is impossible to be guaranteed due to C/Rust cross-language barrier.
        session_opt: &'static RwLock<Option<CassSessionInner>>,
        cluster: &CassCluster,
        keyspace: Option<String>,
    )
```

The solution: Introduce `[...]FFI::into_ref()` methods which will **CONSUME** the pointer, in favor of reference not inheriting the pointer's lifetime. Since we consume, the borrow-checker will work as expected with other FFI API functions.

As I mentioned, I believe that issue `1.` will disappear once we replace `'static` lifetimes in iterators with some named lifetimes (I might be too optimistic, though).
I'm not sure whether issue `2.` can be addressed some other way.

## CassFuture set_callback case...

This one is really tricky. This is the only place in current code, where we need to operate on an owned pointer, by passing it to the method called on a reference that inherits the pointer's lifetime. I'm not really sure how to address it. I believe this is the main reason I implemented `Copy` for `CassPtr`.

Here is a code snippet:
```rust
#[no_mangle]
pub unsafe extern "C" fn cass_future_set_callback(
    future_raw: CassSharedPtr<CassFuture>,
    callback: CassFutureCallback,
    data: *mut ::std::os::raw::c_void,
) -> CassError {
    ArcFFI::as_ref(&future_raw)
        .unwrap()
        .set_callback(future_raw, callback, data)
}
```

Compiler error:
```rust
error[E0505]: cannot move out of `future_raw` because it is borrowed
   --> src/future.rs:304:23
    |
298 |     future_raw: CassSharedPtr<CassFuture>,
    |     ---------- binding `future_raw` declared here
...
302 |     ArcFFI::as_ref(&future_raw)
    |                    ----------- borrow of `future_raw` occurs here
303 |         .unwrap()
304 |         .set_callback(future_raw, callback, data)
    |          ------------ ^^^^^^^^^^ move out of `future_raw` occurs here
    |          |
    |          borrow later used by call
    |
note: if `CassPtr<CassFuture, (argconv::Shared, Const)>` implemented `Clone`, you could clone the value
   --> src/argconv.rs:154:1
    |
154 | pub struct CassPtr<T: Sized, P: Properties> {
    | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ consider implementing `Clone` for this type
    |
   ::: src/future.rs:302:21
    |
302 |     ArcFFI::as_ref(&future_raw)
    |                     ---------- you could clone this value

```

2024-12-04 15:48 UTC, wprzytula commented on scylla-rust-wrapper/src/argconv.rs
> +    }
> ## CassFuture set_callback case...
> 
> This one is really tricky. This is the only place in current code, where we need to operate on an owned pointer, by passing it to the method called on a reference that inherits the pointer's lifetime. I'm not really sure how to address it. I believe this is the main reason I implemented `Copy` for `CassPtr`.

From what I see, the callback is used as an opaque pointer; what's important about it is merely its address. Then, we could make `set_callback` accept `*const CassFuture` and adjust `CassFutureCallback` accordingly. The exact FFI is irrelevant in this specific case, because no allocations/deallocations happen there anyway.
Then, we could have a safe API function `to_raw(&self)` on `CassPtr` that would return the raw pointer. The Rust code as such does nothing with that particular pointer, only passes it down to the callback function (which is going to be implemented in C/C++). WDYT?

2024-12-04 17:19 UTC, muzarski commented on scylla-rust-wrapper/src/argconv.rs
> +    }
I love it! Thank you.

2024-12-04 17:59 UTC, muzarski commented on scylla-rust-wrapper/src/argconv.rs
> +}
Added basic docstrings

2024-12-04 18:09 UTC, muzarski commented
v2: Improved pointer API based on @wprzytula suggestions. Thank you!
- removed `Copy` and `Clone` implementations for `CassPtr` (currently, it's only defined for test purposes. I need to think how to address it some other way)
- Left `CassPtr::into_ref()` as is. As discussed in the comment, it is required to "erase" the lifetime of the returned reference. This method consumes the pointer.
- Introduced `CassPtr::as_ref()` method. It accepts a reference to the pointer. The lifetime of reference is inherited from pointer's lifetime.
- Changed `CassExclusiveMutPtr::into_mut_ref()` to `[...]::as_mut_ref()`. It accepts `&mut CassExclusiveMutPtr`. The lifetime of returned mutable reference is inherited from mutable borrow of the pointer. This is really cool, because this ensures `aliasing ^ mutability` at borrow-checker level.
- `CassPtr::is_null()` now borrows the pointer, instead of consuming it
- `CassFuture::set_callback()`, and `CassFutureCallback` now expect a raw pointer. Safe `CassPtr::as_raw()` method is introduced for this use-case

I still need to think how to address the issue in tests. It's not possible to reuse the pointer, which is not `Copy`, while passing it to multiple API functions that consume the pointer.

2024-12-04 20:30 UTC, wprzytula commented
> I still need to think how to address the issue in tests. It's not possible to reuse the pointer, which is not `Copy`, while passing it to multiple API functions that consume the pointer.

You could have an `unsafe` `clone()` method for tests only, then this would not break soundness guarantees of safe code.

2024-12-04 22:43 UTC, muzarski commented
> > I still need to think how to address the issue in tests. It's not possible to reuse the pointer, which is not `Copy`, while passing it to multiple API functions that consume the pointer.
> 
> You could have an `unsafe` `clone()` method for tests only, then this would not break soundness guarantees of safe code.

Applied the suggestion. At first, I did not understand how is this different from implementing `Copy` and `Clone` for `test` only. But this part: "this would not break soundness guarantees of **safe** code" convinced me.

2024-12-06 06:58 UTC, wprzytula approved these changes

2024-12-06 06:58 UTC, wprzytula commented on scylla-rust-wrapper/src/argconv.rs
> +}
:+1: Now it looks correct. Let's put motivation for this in a comment (why we even need to `clone` in tests).

2024-12-06 06:58 UTC, wprzytula commented on scylla-rust-wrapper/src/argconv.rs
> +/// This trait should be implement for types that are passed between
:pick:  typo: `implement` -> `implemented`

2024-12-06 06:58 UTC, wprzytula commented on scylla-rust-wrapper/src/batch.rs
>      match &statement.statement {
:question: :pushpin: Is this function still correct in case `Arc::make_mut(&mut batch.state)` returns an `Arc` to a new allocation, because there already have been multiple owners of `state`?

2024-12-06 13:06 UTC, muzarski commented on scylla-rust-wrapper/src/batch.rs
>      match &statement.statement {
This is as valid, as it was before the changes - we did not change the logic. But to answer your question (is it valid), I'd need to investigate it. TBH, I haven't touched batches in cpp-rust-driver yet. However, all these `Arc::make_mut` calls are a bit suspicious to me.

2024-12-06 14:04 UTC, wprzytula commented on scylla-rust-wrapper/src/batch.rs
>      match &statement.statement {
Yep, this is out of scope of this PR. Just wanted to raise your awareness about the potential bug here.

2024-12-09 12:46 UTC, muzarski commented
Rebased on master

2024-12-09 12:54 UTC, muzarski commented
v2.1: improved docstrings as suggested by @wprzytula

2024-12-09 13:06 UTC, muzarski commented on scylla-rust-wrapper/src/batch.rs
>      match &statement.statement {
I investigated this. It looks fine to me. It looks like a small optimization.

The reason is that we need to clone fields of `CassBatch` in `cass_session_execute_batch` - we should not make any assumptions about the provided `CassBatch` object in the functions - it could have been modified, or even freed:
```rust
    let session_opt = ArcFFI::into_ref(session_raw).unwrap();
    let batch_from_raw = BoxFFI::as_ref(&batch_raw).unwrap();
    let mut state = batch_from_raw.state.clone();
    let request_timeout_ms = batch_from_raw.batch_request_timeout_ms;

    // DO NOT refer to `batch_from_raw` inside the async block, as I've done just to face a segfault.
    let batch_exec_profile = batch_from_raw.exec_profile.clone();
```

So how the optimization works?
This statement `let mut state = batch_from_raw.state.clone();` is cheap, because it clones an Arc.

When it works?
Well, `Arc::make_mut` can potentially allocate, but this will not be the case if there is no concurrent execution of `cass_session_execute_batch` in the background.

Notice that this is all sound, because we do not expose the state to the users in any way.

2024-12-11 15:08 UTC, Lorak-mmk commented
I've read the first few commits, and it talks about `cass_data_type_new_from_existing` expecting a Arc-allocated CassDataType, but I don't see why.
For context, the code of this function:
```
#[no_mangle]
pub unsafe extern "C" fn cass_data_type_new_from_existing(
    data_type: *const CassDataType,
) -> *const CassDataType {
    let data_type = ptr_to_ref(data_type);
    Arc::into_raw(Arc::new(data_type.clone()))
}
```

As far as I can tell it copies the whole object, not Arc, and does not assume it is Arc-allocated.

2024-12-11 15:30 UTC, muzarski commented
> I've read the first few commits, and it talks about `cass_data_type_new_from_existing` expecting a Arc-allocated CassDataType, but I don't see why. For context, the code of this function:
> 
> ```
> #[no_mangle]
> pub unsafe extern "C" fn cass_data_type_new_from_existing(
>     data_type: *const CassDataType,
> ) -> *const CassDataType {
>     let data_type = ptr_to_ref(data_type);
>     Arc::into_raw(Arc::new(data_type.clone()))
> }
> ```
> 
> As far as I can tell it copies the whole object, not Arc, and does not assume it is Arc-allocated.

Sorry for the confusion. I remember that I made a mistake in some commit message, but forgot to fix it. I meant `cass_data_type_add_sub_type` function:
```rust
#[no_mangle]
pub unsafe extern "C" fn cass_data_type_add_sub_type(
    data_type: CassSharedPtr<CassDataType>,
    sub_data_type: CassSharedPtr<CassDataType>,
) -> CassError {
    let data_type = ArcFFI::as_ref(&data_type).unwrap();
    match data_type
        .get_mut_unchecked()
        .add_sub_data_type(ArcFFI::cloned_from_ptr(sub_data_type).unwrap())
    {
        Ok(()) => CassError::CASS_OK,
        Err(e) => e,
    }
}
```

2024-12-11 15:32 UTC, muzarski commented
Pushed fixed commit message (`collection: allocate static empty collections`).

2024-12-11 15:46 UTC, Lorak-mmk commented
The same mistake is present in `metadata: store CassDataType behind an Arc ` commit message.

2024-12-11 16:46 UTC, wprzytula commented on scylla-rust-wrapper/src/batch.rs
>      match &statement.statement {
:+1:  Please put the above findings in a comment there, not to confuse future readers.

2024-12-12 02:04 UTC, muzarski commented
Rebased on master

2024-12-16 11:21 UTC, Lorak-mmk requested changes
I did not review the whole thing, because I spotted some important issues in argconv.rs. In general, please describe with more detail in precision what guarantees / requirements the types / methods require and provide. Without it it is a bit difficult to reason about the code.

2024-12-16 11:21 UTC, Lorak-mmk commented on scylla-rust-wrapper/src/metadata.rs
> +    }
Is it possible for this upgrade to fail? Or does it indicate a bug in the driver?
If it is possible, can we have a test for that?

2024-12-16 11:21 UTC, Lorak-mmk commented on scylla-rust-wrapper/src/future.rs
>  }
Shouldn't this `invoke` method be unsafe? It does have a requirement for its argument to be a correct (alingment, lifetime etc) pointer.

2024-12-16 11:21 UTC, Lorak-mmk commented on scylla-rust-wrapper/src/future.rs
>              // Another callback has been already set
Here `self_ptr` should refer to the same `CassFuture` as `self`, right?
Can you instead make the receiver of this function an arc? `self: &Arc<CassFuture>`

2024-12-16 11:21 UTC, Lorak-mmk commented on scylla-rust-wrapper/src/argconv.rs
> +impl Mutability for Mut {}
🔧 Could you describe more what mutability means here? It is not obvious in ffi-related code:
- It could be Rust mutability (where mutable reference = exclusive reference)
- It could be C++ mutability: logical mutability (so if object is const, its logical state won't change).

2024-12-16 11:21 UTC, Lorak-mmk commented on scylla-rust-wrapper/src/argconv.rs
> +}
⛏ Could you move it above the aliases? It is a bit confusing when reading the code: you see aliases that use `CassPtr`, but the `CassPtr` was not yet defined.

2024-12-16 11:21 UTC, Lorak-mmk commented on scylla-rust-wrapper/src/argconv.rs
> +impl Ownership for Borrowed {}
🔧 This also could use a bit more extensive doc comments for future contributors.
If a function receives `Shared` pointer, what it means? Is it guaranteed to be Arc-allocated, or is it logical sharing (and Arc is a job of ArcFFI, a higher layer)? Is the pointer borrowed to us, or given to us? It is important because it determines who (we or caller) is responsible for pointee destruction.

2024-12-16 11:21 UTC, Lorak-mmk commented on scylla-rust-wrapper/src/argconv.rs
> +    }
💯 CassPtr is an object passed as function argument, so its lifetime is tied to the function scope, so this lifetime won't we static. I like that.

2024-12-16 11:21 UTC, Lorak-mmk commented on scylla-rust-wrapper/src/argconv.rs
> +    }
OTOH here we can easily create a 'static reference from an object that was just borrowed to us for the function call!

2024-12-16 11:21 UTC, Lorak-mmk commented on scylla-rust-wrapper/src/argconv.rs
> +}
🤔 It will probably become clear later, but after reading this I'm wondering why do we need this - isn't the goal to not use raw pointers?

2024-12-16 11:21 UTC, Lorak-mmk commented on scylla-rust-wrapper/src/argconv.rs
> +}
If it is unsafe, could you please describe safety requirements?

2024-12-16 11:21 UTC, Lorak-mmk commented on scylla-rust-wrapper/src/argconv.rs
> +
```rust
let obj: Arc<()> = Arc::new(());
let x: CassSharedPtr<()> = CassSharedPtr::from_ref(&obj);
std::mem::drop(obj);
let obj2: Arc<()> = CassSharedPtr::into_arc(x);
```

Isn't that use-after-free with safe code?

2024-12-16 11:21 UTC, Lorak-mmk commented on scylla-rust-wrapper/src/argconv.rs
>      }
Do we need to expose `into_ref`? It is quite easy to cause a memory leak with it.

2024-12-16 11:21 UTC, Lorak-mmk commented on scylla-rust-wrapper/src/argconv.rs
>  }
```rust
let obj: Arc<()> = Arc::new(());
let ptr = ArcFFI::as_ptr(&obj);
std::mem::drop(obj);
let obj2 = ArcFFI::from_ptr(ptr);
```

Another use after free :(

2024-12-16 12:21 UTC, muzarski commented on scylla-rust-wrapper/src/argconv.rs
> +    }
That's exactly the use-case - to erase the lifetime. Otherwise, we wouldn't be able to return the types that borrow and hold references. For example, iterators hold some `'static` references.

2024-12-16 12:25 UTC, muzarski commented on scylla-rust-wrapper/src/argconv.rs
> +}
The only use case is `cass_future_set_callback` function. See the discussion: https://github.com/scylladb/cpp-rust-driver/pull/208#discussion_r1869828743

2024-12-16 12:26 UTC, Lorak-mmk commented on scylla-rust-wrapper/src/argconv.rs
> +    }
We did discuss the possibility of such structs being lifetime-generic iiuc.

For now, you could hold a pointer in such struct instead of a static reference.

2024-12-16 12:35 UTC, muzarski commented on scylla-rust-wrapper/src/argconv.rs
> +    }
Still, the issue is not solved. I have a branch with `lifetime-generic` iterators, and erasing the lifetime is still necessary.

Why?
The function accepts an owned `CassPtr`, and we want to return something with the lifetime of this pointer (which is a lifetime of function body). So in the end, we want to return a type that references something that has a lifetime of function call.

Example:
```rust
pub struct CassRowsResultIterator<'result> {
    iterator: TypedRowIterator<'result, 'result, CassRawRow<'result>>,
    result_metadata: &'result CassResultMetadata,
    current_row: Option<CassRow<'result>>,
}

#[no_mangle]
pub unsafe extern "C" fn cass_iterator_from_result<'result>(
    result: CassSharedPtr<CassResult>,
) -> CassExclusiveMutPtr<CassIterator<'result>> {
    let result_from_raw = ArcFFI::as_ref(&result).unwrap();

    let iterator = match &result_from_raw.kind {
        CassResultKind::NonRows => CassResultIterator::NonRows,
        CassResultKind::Rows(cass_rows_result) => {
            CassResultIterator::Rows(CassRowsResultIterator {
                iterator: cass_rows_result.raw_rows.rows_iter().unwrap(),
                result_metadata: &cass_rows_result.metadata,
                current_row: None,
            })
        }
    };

    BoxFFI::into_ptr(Box::new(CassIterator::CassResultIterator(iterator)))
}
```

Compiler error:
```rust
error[E0515]: cannot return value referencing function parameter `result`
    --> src/query_result.rs:1047:5
     |
1034 |     let result_from_raw = ArcFFI::as_ref(&result).unwrap();
     |                                          ------- `result` is borrowed here
...
1047 |     BoxFFI::into_ptr(Box::new(CassIterator::CassResultIterator(iterator)))
     |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ returns a value referencing data owned by the current function
```

2024-12-17 16:36 UTC, muzarski commented on scylla-rust-wrapper/src/argconv.rs
> +
Yeah.. Analogous issue appears with `CassBorrowedPtr`:
```rust
struct Bar;

impl RefFFI for Bar { }

struct Owner {
   owned: Bar,
}

let owner = Owner { owned: Bar };
let borrowed_ptr: CassBorrowedPtr<Bar> = RefFFI::as_ptr(&owner.owned);
std::mem::drop(owner);
// A reference from invalid pointer
let bar = RefFFI::as_ref(&borrowed_ptr);
```

I don't think there is a safe way to prevent such scenarios. I'll document that this API can be misused (and so, should be `unsafe`) and where we expect valid pointers etc.

2024-12-17 20:20 UTC, muzarski commented
v3:
## New `Origin` trait and modified `Ownership` trait
Introduced new `Origin` trait which represents an origin of the pointer, and three implementors:
- `FromBox` - box allocated, exclusive (potentially mutable) pointers
- `FromArc` - arc-allocated, shared (either owned, or borrowed) const pointers
- `FromRef` - pointers created from a valid rust reference, always borrowed and const

Modified implementors of `Ownership` trait. Now we distinguish two ownership kinds:
- `Owned` - owned pointer. Data needs to be freed
- `Borrowed` - borrowed pointers. Conversions to reference/Arcs from such pointers are `unsafe` - caller needs to ensure that owner of the data is alive

## Additional commit
Moved the changes that introduce `CassPtr` (and traits) to a separate commit. I hope this aids readability and reduces the noise during review.

Thoroughly documented each type/trait and its methods. Explained what each type guarantees (and what it does not guarantee). Justified the choice of the methods being safe/`unsafe`.

2024-12-18 07:56 UTC, wprzytula commented on scylla-rust-wrapper/src/argconv.rs
> +
> ```rust
> let obj: Arc<()> = Arc::new(());
> let x: CassSharedPtr<()> = CassSharedPtr::from_ref(&obj);
> std::mem::drop(obj);
> let obj2: Arc<()> = CassSharedPtr::into_arc(x);
> ```
> 
> Isn't that use-after-free with safe code?

Wouldn't [Arc::increment_strong_count](https://doc.rust-lang.org/std/sync/struct.Arc.html#method.increment_strong_count) called upon `CassSharedPtr::from_ref` solve this particular case? By the way, I believe we should be doing that shared ownership with pointers. I remember that in the past, cpp-rust-driver used to call that function.

2024-12-18 08:00 UTC, Lorak-mmk commented on scylla-rust-wrapper/src/argconv.rs
> +
The way I understand it, `from_ref` is for borrowing data to the user. If you increment strong count, then user is a co-owner of that data, not a borrower. This could be used in cases where user is supposed to call some `_free` function later.

2024-12-18 08:13 UTC, muzarski commented on scylla-rust-wrapper/src/argconv.rs
> +
> > ```rust
> > let obj: Arc<()> = Arc::new(());
> > let x: CassSharedPtr<()> = CassSharedPtr::from_ref(&obj);
> > std::mem::drop(obj);
> > let obj2: Arc<()> = CassSharedPtr::into_arc(x);
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Isn't that use-after-free with safe code?
> 
> Wouldn't [Arc::increment_strong_count](https://doc.rust-lang.org/std/sync/struct.Arc.html#method.increment_strong_count) called upon `CassSharedPtr::from_ref` solve this particular case? By the way, I believe we should be doing that shared ownership with pointers. I remember that in the past, cpp-rust-driver used to call that function.

Sure, it solves this particular case. However, it will almost certainly cause memory leaks in some scenarios. 

Consider `CassDataType`. There are multiple functions that return pointer to `CassDataType`. However, the semantics differ based on the context. For example:
- `cass_data_type_new` -> returns a pointer with a shared **ownership**. The pointee needs to be freed with `cass_data_type_free`.
- `cass_result_column_data_type` -> returns a pointer originated from Arc-allocation, but it **lends** the data. User is not expected (and he should not!!!) free the data type. This is the exact use case for `CassSharedPtr::from_ref()` (`ArcFFI::as_ptr()`). If we increased the reference count, we have a memory leak.

The distinctions between two semantics are better visible after my latest push, where I decoupled `Ownership` trait and implementors into `Origin` (`FromBox`, `FromArc`, `FromRef`) and `Ownership` (`Owned`, `Borrowed`).
There, `cass_data_type_new` returns a pointer that is `FromArc` and `Owned` (and `cass_data_type_free` accepts only `FromArc`, `Owned` pointers as well).  OTOH, `cass_result_column_data_type` returns `FromArc`, `Borrowed` pointer.

2024-12-18 08:19 UTC, wprzytula commented on scylla-rust-wrapper/src/argconv.rs
> +
> * `cass_result_column_data_type` -> returns a pointer originated from Arc-allocation, but it **lends** the data. User is not expected (and he should not!!!) free the data type. This is the exact use case for `CassSharedPtr::from_ref()` (`ArcFFI::as_ptr()`). If we increased the reference count, we have a memory leak.

Then it's clear that the UAF performed by the above code by @Lorak-mmk is the user's fault (as understood by the C API). Only in Rust do we have to make the API `unsafe`, because Rust understands the mere possibility of introducing UAF condition as a bug in API. Do I get this correctly?

2024-12-18 08:29 UTC, muzarski commented on scylla-rust-wrapper/src/argconv.rs
> +
> Only in Rust do we have to make the API `unsafe`, because Rust understands the mere possibility of introducing UAF condition as a bug in API. Do I get this correctly?

Yes, for me this is `unsafe`, because we can copy and paste the exact code snippet @Lorak-mmk provided and cause UAF. In general, in my new push all of the conversions `Owned` ptr -> `reference/Arc/Box` are safe, while `Borrowed` ptr -> `reference/Arc` are `unsafe`, because we are not guaranteed that the owner of borrowed data is alive when we dereference the pointer.

BTW, I was wondering if there is a way for a pointer to somehow inherit the lifetime, when the pointer is being borrowed (i.e. created from some immutable borrow). I'm not really sure if this is possible.

2024-12-18 08:31 UTC, Lorak-mmk commented on scylla-rust-wrapper/src/argconv.rs
> +
Yes this is true. I'm currently reading this PR and will experiment with it a little.
What I'm currently thinking:
- CassPtr should be lifetime-generic instead of having `Ownership` AT. OwnedPtr would be static, BorrowedPtr could be created from it (and borrow from it).
- `Origin` should be tied to the type (and so, the FFI trait), not the pointer.

2024-12-19 15:58 UTC, muzarski commented on scylla-rust-wrapper/src/argconv.rs
> +}
It's removed in recent push

2024-12-19 16:01 UTC, muzarski commented on scylla-rust-wrapper/src/argconv.rs
>      }
I investigated where we previously needed to erase the lifetime. There were two cases:
- iterators with `'static` references. I replaced them with generic lifetimes
- CassSession `'static` reference passed to an async block. I changed it, so we pass an `Arc` to the async block. This is a good change (and a fix), because cpp-driver assumes that session object can be prematurely free'd by the user. It should not cause segfaults in executions that haven't been awaited yet. What's more, there is a test that expects that prematurely freed session awaits all the futures before closing. We are not doing that yet, thus the test is not enabled.

After adjusting these two things, I could get rid of `into_ref` method.

2025-03-10 06:43 UTC, muzarski commented
Rebased on master

2025-03-10 08:48 UTC, muzarski commented on scylla-rust-wrapper/src/metadata.rs
> +    }
AFAIU, it should not be possible, and it indicates a bug in the driver. Why?

`CassSchemaMeta` contains and **owns** all metadata. It's obtained from `cass_session_get_schema_meta` - allocated as Box. So we have following relationship between the metadata structs:
- `CassSchemaMeta` owns `CassKeyspaceMeta`
- `CassKeyspaceMeta` owns both `CassTableMeta` and `CassMaterializedViewMeta`
- `CassMaterializedViewMeta` holds a weak reference to `CassTableMeta` that is owned by `CassKeyspaceMeta`

An idea on how to obtain the state where this upgrade() returns `None` (and write analogous test):
1. get schema metadata `CassSchemaMeta`
2. obtain a pointer to some view (`CassMaterializedViewMeta`) - easily done using API methods (`cass_schema_meta_keyspace_by_name` then `cass_keyspace_meta_materialized_view_by_name`)
3. free schema metadata (`cass_schema_meta_free`)
4. Call `cass_materialized_view_meta_base_table` (where upgrade happens) with the pointer obtained from bullet 2. <- this will panic, because the pointer is invalid. The owner (`CassSchemaMeta`) has already been freed.

2025-03-10 09:05 UTC, muzarski commented on scylla-rust-wrapper/src/future.rs
>              // Another callback has been already set
I don't see a good reason behind it. We get a pointer in `cass_future_set_callback`, then we would need to convert it to `Arc` (increase a refcount), just to then convert it back to pointer (decrease refcount) and pass the ponter to callback.

2025-03-17 12:18 UTC, muzarski commented
v4:
- Introduced `CMutability` property - it simply tells whether the pointer was `T*` or `const T*` - as defined in C API. It tells about **logical mutability** of the pointer.
- Rebased on main
- Updated cover letter

2025-03-20 14:23 UTC, wprzytula requested changes

2025-03-20 14:23 UTC, wprzytula commented on scylla-rust-wrapper/src/argconv.rs
> +}
:thought_balloon: Wouldn't it make more sense in naming to call these `into_ref`, `into_mut_ref` ?

2025-03-20 14:23 UTC, wprzytula commented on scylla-rust-wrapper/src/argconv.rs
> +impl<'a, T: Sized, CM: CMutability> CassPtr<'a, T, (Mut, CM)> {
:wrench: This should be likely part of the previous commit.

2025-03-20 14:23 UTC, wprzytula commented on scylla-rust-wrapper/src/argconv.rs
> +    }
:question: :pick: Why is this only for tests? Even if it's not currently used in the code, I'd rather silence the unused warning, yet made it discoverable by the IntelliSense for future devs of this lib.

2025-03-20 14:23 UTC, wprzytula commented on scylla-rust-wrapper/src/argconv.rs
> +        // to convert such pointer back to owned Arc.
:pick:

2025-03-20 14:23 UTC, wprzytula commented on scylla-rust-wrapper/src/argconv.rs
> +        // to convert such pointer back to owned Arc.
```suggestion
        // ArcFFI::into_ptr(). It converts an owned Arc into the pointer. It is thus safe
        // to convert such pointer back to owned Arc.
```

2025-03-20 14:23 UTC, wprzytula commented on scylla-rust-wrapper/src/argconv.rs
> +        // 1. validity guarantee - pointer is valid, since it's obtained from Arc allocation
:pick:

2025-03-20 14:23 UTC, wprzytula commented on scylla-rust-wrapper/src/argconv.rs
> +        // 1. validity guarantee - pointer is valid, since it's obtained from Arc allocation
```suggestion
        // 1. validity guarantee - pointer is valid, since it's obtained from Arc allocation.
```

2025-03-20 14:23 UTC, wprzytula commented on scylla-rust-wrapper/src/argconv.rs
> +        //    via ArcFFI::free().
:pick: to be more specific

2025-03-20 14:23 UTC, wprzytula commented on scylla-rust-wrapper/src/argconv.rs
> +        //    via ArcFFI::free().
```suggestion
        // 2. pointer's lifetime - returned pointer has a 'static lifetime. It is a shared
        //    owner of the pointee. User has to decrement the RC of the pointer (and potentially free the memory)
        //    via ArcFFI::free().
```

2025-03-20 14:23 UTC, wprzytula commented on scylla-rust-wrapper/src/argconv.rs
> +        // It is thus safe, to increase the reference count of the pointer, and convert
:pick:

2025-03-20 14:23 UTC, wprzytula commented on scylla-rust-wrapper/src/argconv.rs
> +        // It is thus safe, to increase the reference count of the pointer, and convert
```suggestion
        // It is thus safe to increase the reference count of the pointer, and convert
```

2025-03-20 14:23 UTC, wprzytula commented on scylla-rust-wrapper/src/argconv.rs
> +        // to provide the pointer that points to already deallocated memory.
:pick:

2025-03-20 14:23 UTC, wprzytula commented on scylla-rust-wrapper/src/argconv.rs
> +        // to provide the pointer that points to already deallocated memory.
```suggestion
        // it to Arc. Because of the borrow-checker, it is not possible for the user
        // to provide a pointer that points to already deallocated memory.
```

2025-03-20 14:23 UTC, wprzytula commented on scylla-rust-wrapper/src/argconv.rs
> +
:thought_balloon: I'm wondering why the function needs to be `unsafe`. Is the following scenario one valid reason for that?
```rust
let data = ...;
let arc = Arc::new(data);
let weak = Arc::downgrade(&arc);
let ptr = weak_as_ptr(&weak);
std::mem::drop(arc);

// Now `ptr` is dangling...
```

2025-03-20 14:23 UTC, wprzytula commented on scylla-rust-wrapper/src/argconv.rs
> +
If I'm correct, maybe let's put this short example in the docstring of this function? Just to convince readers that `unsafe` is needed here.

2025-03-20 14:23 UTC, wprzytula commented on scylla-rust-wrapper/src/batch.rs
> +    statement: CassBorrowedPtr<CassStatement, CMut>,
:thought_balloon: I'm wondering why it's `CassBorrowedPtr` and not `CassBorrowedConstPtr`. After all, it's `*const` and `*mut` in Rust, so if want to be in line with this naming, we should include the `Const` part. Also, the constness guarantee would stand out more in code.

2025-03-20 14:23 UTC, wprzytula commented on scylla-rust-wrapper/src/binding.rs
> +                Ok(v) => $consume_v(BoxFFI::as_mut_ref( this).unwrap(), name, v),
:pick:

2025-03-20 14:23 UTC, wprzytula commented on scylla-rust-wrapper/src/binding.rs
> +                Ok(v) => $consume_v(BoxFFI::as_mut_ref( this).unwrap(), name, v),
```suggestion
                Ok(v) => $consume_v(BoxFFI::as_mut_ref(this).unwrap(), name, v),
```

2025-03-20 14:23 UTC, wprzytula commented on scylla-rust-wrapper/src/binding.rs
> +                Ok(v) => $consume_v(BoxFFI::as_mut_ref( this).unwrap(), v),
:pick:

2025-03-20 14:23 UTC, wprzytula commented on scylla-rust-wrapper/src/binding.rs
> +                Ok(v) => $consume_v(BoxFFI::as_mut_ref( this).unwrap(), v),
```suggestion
                Ok(v) => $consume_v(BoxFFI::as_mut_ref(this).unwrap(), v),
```

2025-03-20 14:23 UTC, wprzytula commented on scylla-rust-wrapper/src/lib.rs
> +pub mod argconv;
:question: Why is this needed?

2025-03-20 14:41 UTC, muzarski commented on scylla-rust-wrapper/src/argconv.rs
> +}
TBH, I couldn't decide. According to https://rust-lang.github.io/api-guidelines/naming.html#ad-hoc-conversions-follow-as_-to_-into_-conventions-c-conv, there is no naming convention that matches our case.

I understand your reasoning - you suggest `into_` because methods accepts `self` (owned type). OTOH, how I understand this operation is that we convert one referential type (wrapper over raw pointer) to some other referential type - `as_` convention somehow sounds more naturally to me in such case.

2025-03-20 15:52 UTC, wprzytula commented on scylla-rust-wrapper/src/argconv.rs
> +}
For me, the more important distinction is between `borrow()` (which borrows) and this method (which consumes) the caller. That's why my suggestion.
Normal references and pointers are `Copy`, whereas `CassPtr` is not even `Clone`. Therefore, it's different from usual Rust references and thus it should be closer to owned types wrt naming.

2025-03-21 13:34 UTC, muzarski commented on scylla-rust-wrapper/src/batch.rs
> +    statement: CassBorrowedPtr<CassStatement, CMut>,
I definitely agree. Let's make the naming consistent.

2025-03-21 13:47 UTC, muzarski commented on scylla-rust-wrapper/src/argconv.rs
> +    }
The compiler does not even complain if I remove the cfg - probably because this trait is `pub`... As a bonus, I'll change `pub` to `pub(crate)` in `argconv.rs` in a separate commit.

2025-03-21 13:48 UTC, muzarski commented on scylla-rust-wrapper/src/argconv.rs
> +}
You convinced me. Renamed to `into_*`.

2025-03-21 13:50 UTC, muzarski commented on scylla-rust-wrapper/src/lib.rs
> +pub mod argconv;
It is not. I'm not sure when and why I introduced this change.

2025-03-21 13:51 UTC, muzarski commented on scylla-rust-wrapper/src/argconv.rs
> +
> 💭 I'm wondering why the function needs to be `unsafe`. Is the following scenario one valid reason for that?
> 
> ```rust
> let data = ...;
> let arc = Arc::new(data);
> let weak = Arc::downgrade(&arc);
> let ptr = weak_as_ptr(&weak);
> std::mem::drop(arc);
> 
> // Now `ptr` is dangling...
> ```

Correct.

> If I'm correct, maybe let's put this short example in the docstring of this function? Just to convince readers that `unsafe` is needed here.

Ok. Good idea.

2025-03-21 13:59 UTC, muzarski commented on scylla-rust-wrapper/src/lib.rs
> +pub mod argconv;
Nvm, it is needed. I forgot that doctests are compiled as a separate crate. Thus, they can access only `pub` items from our crate. I justified this change in the comment in code.

2025-03-21 13:59 UTC, muzarski commented on scylla-rust-wrapper/src/argconv.rs
> +    }
> As a bonus, I'll change `pub` to `pub(crate)` in `argconv.rs` in a separate commit.

Nvm, I can't do that because of doctests. The ffi traits need to be `pub`.

2025-03-21 14:12 UTC, muzarski commented
v4.1: addressed @wprzytula comments

2025-03-25 08:25 UTC, wprzytula approved these changes

2025-03-28 16:56 UTC, Lorak-mmk requested changes
💯 Really great work! I no longer see any big problems, only left some minor comments.

I'm not a fan of the workaround in cass_future_set_callback, but I don't have any good ideas on how to improve it.

2025-03-28 16:56 UTC, Lorak-mmk commented on scylla-rust-wrapper/src/argconv.rs
> +impl Mutability for Mut {}
`Mutability` and `CMutability` are quite similar names. The names of specific structs are also similar.

WDYT about
`Mutability` -> `Ownership`
`Const` -> `Shared`
`Mut` -> `Exclusive`

I think it better reflects what this property is about, and reflects the imo better way to think about rust references.

2025-03-28 16:56 UTC, Lorak-mmk commented on scylla-rust-wrapper/src/argconv.rs
> +
❓ Why is this `allow` necessary? According to the table at https://rust-lang.github.io/rust-clippy/master/index.html#wrong_self_convention it should be fine.

2025-03-28 16:56 UTC, Lorak-mmk commented on scylla-rust-wrapper/src/argconv.rs
> +/// At first glance, it seems impossible to obtain multiple immutable reference from one pointer.
I see no such methods. You meant `into_ref` and `into_mut_ref`, right?

2025-03-28 16:58 UTC, muzarski commented on scylla-rust-wrapper/src/argconv.rs
> +/// At first glance, it seems impossible to obtain multiple immutable reference from one pointer.
Yeah, I forgot to address the docstrings after renaming the methods.

2025-03-28 17:00 UTC, muzarski commented on scylla-rust-wrapper/src/argconv.rs
> +
It used to be called `as_*` (but @wprzytula eventually convinced me to "into_*"). Forgot to remove the allow.

2025-03-28 17:14 UTC, muzarski commented on scylla-rust-wrapper/src/argconv.rs
> +impl Mutability for Mut {}
I definitely agree with `Exclusive` and `Shared` names. Not sure about `Ownership`. For me, Ownership property is currently represented via lifetimes (Owned vs Borrowed).

OTOH, `Mutability` name is not perfect either. I'll try to come up with some reasonable name. If I fail to do so, I'll apply your suggestion and rename the trait to `Ownership`.

2025-03-28 17:15 UTC, muzarski commented on scylla-rust-wrapper/src/argconv.rs
> +
Ref: https://github.com/scylladb/cpp-rust-driver/pull/208#discussion_r2005329145

2025-03-30 21:13 UTC, muzarski commented on scylla-rust-wrapper/src/argconv.rs
> +impl Mutability for Mut {}
I couldn't come up with a better name. Renamed the trait and corresponding struct as you suggested.

2025-03-30 21:14 UTC, muzarski commented
v4.2: Addressed @Lorak-mmk comments.

2025-03-31 07:44 UTC, wprzytula commented
Hmm, why did cassandra tests fail?

2025-03-31 07:47 UTC, wprzytula commented
The cover letter needs to be adjusted for the recent `Mutability` -> `Ownership` change.

2025-03-31 08:31 UTC, muzarski commented
> Hmm, why did cassandra tests fail?

Due to the recent change on scylla-ccm's master. I'll be investivating this, but the failure is not related to this PR.

2025-03-31 11:56 UTC, muzarski commented
> > Hmm, why did cassandra tests fail?
> 
> Due to the recent change on scylla-ccm's master. I'll be investivating this, but the failure is not related to this PR.

@wprzytula @Lorak-mmk I opened an issue on scylla-ccm: https://github.com/scylladb/scylla-ccm/issues/646. As a temporary fix, should I set the ccm version in CI to the version before the change that introduced the bug?

2025-03-31 12:06 UTC, Lorak-mmk commented
> > > Hmm, why did cassandra tests fail?
> > 
> > Due to the recent change on scylla-ccm's master. I'll be investivating this, but the failure is not related to this PR.
> 
> @wprzytula @Lorak-mmk I opened an issue on scylla-ccm: https://github.com/scylladb/scylla-ccm/issues/646. As a temporary fix, should I set the ccm version in CI to the version before the change that introduced the bug?

Yes

2025-03-31 12:48 UTC, muzarski commented
CI passed - I am merging

2025-03-31 12:48 UTC, merged