deser: lazy CassRow construction
scylladb/cpp-rs-driver pull request #213
Opened 2024-12-03 20:32 UTC by muzarski

## Pre-review checklist

- [ ] I have split my patch into logically separate commits.
- [ ] All commit messages clearly explain what they change and why.
- [ ] PR description sums up the changes and reasons why they should be introduced.
- [ ] I have implemented Rust unit tests for the features/changes introduced.
- [ ] I have enabled appropriate tests in `.github/workflows/build.yml` in `gtest_filter`.
- [ ] I have enabled appropriate tests in `.github/workflows/cassandra.yml` in `gtest_filter`.

2025-03-18 14:03 UTC, muzarski commented
This one is ready for review. https://github.com/scylladb/cpp-rust-driver/pull/208 needs to be merged first, though.

2025-04-01 06:16 UTC, Lorak-mmk requested changes

2025-04-01 06:16 UTC, Lorak-mmk commented on scylla-rust-wrapper/.cargo/config.toml
Commit: cargo/cmake: compile with cpp_rust_unstable cfg 

Could you explain in the commit message why are changes on both files necessary? It is not clear to me why changes in config.toml are not enough.

2025-04-01 06:16 UTC, Lorak-mmk commented on scylla-rust-wrapper/src/iterator.rs
> +        }
Nit: For functions like `rows_iter` it is imo more readable to always specify the type (`.rows_iter::<Row>()`)

2025-04-01 06:16 UTC, Lorak-mmk commented on scylla-rust-wrapper/src/query_result.rs
> +
Commit: "row: borrow metadata from result, instead of cloning an Arc "

`CassRowsResult` borrows from `CassResultMetadata`, not `CassRowsResult`, so the safety comment here seems to be imprecise.

2025-04-01 06:16 UTC, Lorak-mmk commented on scylla-rust-wrapper/src/query_result.rs
> +                let first_row = unsafe { CassRowsResult::create_first_row(&raw_rows, &metadata)? };
This comment also fails to mention `CassResultMetadata`.

Why is it important? Apart from liveness there is one more important requirement: You are not allowed to move the borrowed `CassResultMetadata`, even if it keeps living.

Until one notices that it is stored behind and Arc here it is not obvious that it is not moved during, or after, creation of `CassRowsResult`

2025-04-01 06:16 UTC, Lorak-mmk commented on scylla-rust-wrapper/src/query_result.rs
> +
Also I think we should use `unsafe` blocks for unsafe operations even in unsafe functions. 
The lint is warn-by-default in 2024 edition of Rust, which we can migrate to. We could also enable it even before migrating.

2025-04-01 07:40 UTC, muzarski commented on scylla-rust-wrapper/.cargo/config.toml
From my experience, the `CMakeRust` does not pick up the config file. This might be related: https://github.com/Devolutions/CMakeRust/issues/14.

2025-04-01 07:47 UTC, muzarski commented on scylla-rust-wrapper/.cargo/config.toml
I'll adjust the cmake files, so they pick up the config file. Thanks to that, in the future, if we modify the `.cargo/config.toml` we won't need to adjust the cmake files.

2025-04-01 07:47 UTC, Lorak-mmk commented on scylla-rust-wrapper/.cargo/config.toml
Ok, please explain it in the commit message.

2025-04-01 08:19 UTC, muzarski commented on scylla-rust-wrapper/.cargo/config.toml
> I'll adjust the cmake files, so they pick up the config file. Thanks to that, in the future, if we modify the `.cargo/config.toml` we won't need to adjust the cmake files.

It's annoying, but I won't be able to do that. According to the documentation (https://doc.rust-lang.org/cargo/reference/config.html#buildrustflags), the `RUSTFLAGS` env variable overrides the rustflags defined in the config file. Cmake sets some RUSTFLAGS. At first, I thought that I might be able to add these to `config.toml`, but the RUSTFLAGS defined by the cmake are not static - they are dependent on the platform.

So I'll leave the current version and add a comment explaining why it has to be like that.

2025-04-01 08:30 UTC, Lorak-mmk commented on scylla-rust-wrapper/.cargo/config.toml
Ok. Out of curiosity: what RUSTFLAGS are set there? It is a bit surprising that we need any (other than cpp_rust_unstable).

2025-04-01 09:20 UTC, muzarski commented on scylla-rust-wrapper/.cargo/config.toml
On my machine these are: `RUSTFLAGS=-Clink-arg=-Wl,-soname=libscylla-cpp-driver.so.2`

2025-04-01 09:23 UTC, muzarski commented on scylla-rust-wrapper/src/query_result.rs
> +
> Also I think we should use `unsafe` blocks for unsafe operations even in unsafe functions. The lint is warn-by-default in 2024 edition of Rust, which we can migrate to. We could also enable it even before migrating.

Opened a PR: https://github.com/scylladb/cpp-rust-driver/pull/232

2025-04-01 09:29 UTC, muzarski commented on scylla-rust-wrapper/src/query_result.rs
> +
> Commit: "row: borrow metadata from result, instead of cloning an Arc "
> 
> `CassRowsResult` borrows from `CassResultMetadata`, not `CassRowsResult`, so the safety comment here seems to be imprecise.

What I had in mind, is that `CassRow` borrows the metadata (`CassResultMetadata`) which is owned by `CassRowsResult`. But I agree, that the safety comment is not perfect. I'll adjust it.

2025-04-01 09:34 UTC, muzarski commented on scylla-rust-wrapper/src/query_result.rs
> +                let first_row = unsafe { CassRowsResult::create_first_row(&raw_rows, &metadata)? };
Good catch. I took for granted the fact that most of (if not all) the objects created by our API are heap-allocated and cannot be moved out of the allocated memory unless free'd.

2025-04-01 09:49 UTC, muzarski commented
Rebased on master (to include https://github.com/scylladb/cpp-rust-driver/pull/232)

2025-04-01 10:28 UTC, muzarski commented
v1.1: Adjusted safety comments and commit messages as @Lorak-mmk suggested.

The CI will fail - still waiting for https://github.com/scylladb/cpp-rust-driver/pull/233 to finish (cmake version bump)

2025-04-01 10:34 UTC, muzarski commented
WTF, `Build / Build, lint and run unit tests` passed. It looks like not all GH runners have CMake updated to 4.0 yet.

2025-04-01 11:37 UTC, Lorak-mmk requested changes

2025-04-01 11:37 UTC, Lorak-mmk commented on scylla-rust-wrapper/src/query_result.rs
> +    /// 2. is not moved while the row lives (will not change its place in memory)
```
3. No mutable reference to this `CassResultMetadata` is created during the lifetime of returned CassRow.
In other words - Rust borrowing rules are upheld.
```

2025-04-01 11:37 UTC, Lorak-mmk commented on scylla-rust-wrapper/src/query_result.rs
> +                let first_row = unsafe { CassRowsResult::create_first_row(&raw_rows, &metadata)? };
And we do not create mut refs to this metadata, right?

2025-04-01 11:40 UTC, muzarski commented on scylla-rust-wrapper/src/query_result.rs
> +                let first_row = unsafe { CassRowsResult::create_first_row(&raw_rows, &metadata)? };
Correct, `CassResultMetadata` is immutable.

2025-04-01 11:51 UTC, muzarski commented
v1.2: Rebased on master (cmake version bump) and addressed @Lorak-mmk comments

2025-04-01 11:54 UTC, Lorak-mmk approved these changes

2025-04-01 13:44 UTC, wprzytula requested changes

2025-04-01 13:44 UTC, wprzytula commented on scylla-rust-wrapper/src/iterator.rs
> +        let iter_position = match rows_result_iterator.position {
:recycle: I suggest replacing this `if let` with `let else` for better code flow.

2025-04-01 13:44 UTC, wprzytula commented on scylla-rust-wrapper/src/iterator.rs
>          CassIterator::Row(row_iterator) => {
:camping: I believe this method should only delegate to `next()` implementations for all of: `CassRowIterator`, `CassResultIterator`, etc. Those implementations should be extracted from this single method into separate methods; this would aid readability.

2025-04-01 13:44 UTC, wprzytula commented on scylla-rust-wrapper/src/iterator.rs
> +    iterator: CassBorrowedSharedPtr<'result, CassIterator<'result>, CConst>,
:thinking: Hmm, why does it syntactically type check? Before this commit, `CassBorrowedSharedPtr` had no lifetime specified and now it takes one. Is it allowed to omit lifetime arguments?

2025-04-01 13:44 UTC, wprzytula commented on scylla-rust-wrapper/src/iterator.rs
>      RefFFI::null()
:recycle: `let-else` for better logic linearity.

2025-04-01 13:44 UTC, wprzytula commented on scylla-rust-wrapper/src/iterator.rs
>  }
:thinking: As the whole iterator is parametrized by a lifetime `'result`, why do we need to have a shared ownership over `CassResultMetadata`? Can't we borrow it instead from the same source that we borrow raw frame contents from?

2025-04-01 13:44 UTC, wprzytula commented on scylla-rust-wrapper/src/iterator.rs
>  }
```rust
pub struct CassRowsResultIterator<'frame, 'metadata> {
    iterator: TypedRowIterator<'frame, 'metadata, Row>,
    result_metadata: &'metadata CassResultMetadata,
    current_row: Option<CassRow>,
}
```

2025-04-01 13:44 UTC, wprzytula commented on scylla-rust-wrapper/src/iterator.rs
> +                    }
:disappointed: So sad that the API is so bad...

2025-04-01 13:44 UTC, wprzytula commented on scylla-rust-wrapper/src/query_error.rs
>      Deserialization(#[from] DeserializationError),
:camping: Shall we rename this module to `execution_error`, together with renaming `Query` to `Statement`?

2025-04-01 13:44 UTC, wprzytula commented on scylla-rust-wrapper/src/query_result.rs
>                      }),
:question: Just to make sure it's supposed to work: we're creating a `CassRowsResult` with `raw_rows` still containing the first row, even though the first row is already deserialized. Won't this make the first row deserialized/returned twice?

2025-04-01 13:44 UTC, wprzytula commented on scylla-rust-wrapper/src/iterator.rs
>  }
Or, if we need an `Arc` to be available for cloning due to some APIs, then we could maybe store `&'metadata Arc<ResultMetadata>`?

2025-04-01 13:44 UTC, wprzytula commented on scylla-rust-wrapper/src/query_result.rs
> +            .map(|row| std::mem::transmute(CassRow::from_row_and_metadata(row, metadata)));
:wrench: `mem::transmute` is a particularly wounding footgun. IIUC, the only thing you achieve by using it is lifetime extension (from `'a` to `'static`). Let's extract a local function that does only that (encapsulating and limiting the destructive potential of `mem::transmute`) and call it.

2025-04-01 13:44 UTC, wprzytula commented on scylla-rust-wrapper/src/query_result.rs
> +            .map(|row| std::mem::transmute(CassRow::from_row_and_metadata(row, metadata)));
```suggestion
        fn extend_lifetime<T>(v: &'_ T) -> &'static T {
            std::mem::transmute(v)
        }
        
        let first_row = raw_rows
            .rows_iter::<Row>()
            // unwrap: Row always passes the typecheck.
            .unwrap()
            .next()
            .transpose()?
            .map(|row| extend_lifetime(CassRow::from_row_and_metadata(row, metadata)));
```

2025-04-01 13:44 UTC, wprzytula commented on scylla-rust-wrapper/src/query_result.rs
> +                // This is becase, first_row is a part of constructed CassRowsResult.
:wrench:

2025-04-01 13:44 UTC, wprzytula commented on scylla-rust-wrapper/src/query_result.rs
> +                // This is becase, first_row is a part of constructed CassRowsResult.
```suggestion
                // SAFETY: We make sure that `CassRow` will live no longer than `CassRowsResult` that it borrows from.
                // This is because `first_row` is a part of constructed CassRowsResult.
```

2025-04-01 13:44 UTC, wprzytula commented on scylla-rust-wrapper/src/query_result.rs
> +                // This is becase, first_row is a part of constructed CassRowsResult.
:memo:

> The fields of a [struct](https://doc.rust-lang.org/reference/types/struct.html) are dropped in declaration order.

`metadata` is declared below `first_row`, so `first_row` will indeed live no longer than `metadata` :+1:.

2025-04-01 13:49 UTC, Lorak-mmk commented
Regarding the self-reference problem: maybe we could use `yoke` as we did in Rust Driver?

2025-04-01 14:14 UTC, muzarski commented on scylla-rust-wrapper/src/query_result.rs
>                      }),
If someone creates the `cass_iterator_from_result` which iterates over `CassRow`s, it is expected that the first row is still there. So you are right, the first row will be deserialized again during iteration (first call to `cass_iterator_next`).

2025-04-01 14:15 UTC, muzarski commented on scylla-rust-wrapper/src/iterator.rs
>  }
It is addressed in last commit. `CassRowsResultIterator` looks exactly as you suggested.

2025-04-01 14:23 UTC, wprzytula commented on scylla-rust-wrapper/src/query_result.rs
>                      }),
> If someone creates the `cass_iterator_from_result` which iterates over `CassRow`s, it is expected that the first row is still there. So you are right, the first row will be deserialized again during iteration (first call to `cass_iterator_next`).

Can we somehow skip the second deserialization, as we already have the first row deserialized?

2025-04-01 14:44 UTC, muzarski commented on scylla-rust-wrapper/src/query_result.rs
>                      }),
I don't think it's possible with current API. `TypedRowIterator` performs deserialization in `next()`. Even if we wanted to skip the first row, we would need to call `next()`. So in the end, we would still need to deserialize the row.

Maybe if `TypedRowIterator` was `Clone` (but it's not), then we could:
1. create TypedRowIterator
2. deserialize first row (call `next()` on the iterator)
3. store the iterator without the first row in `CassRowsResult` (self-borrowing yet again)
4. during the call to `cass_iterator_from_result`, we could pass the first row (deserialized) and iterator (without first row) to the `CassRowsResultIterator` by cloning.

I don't believe that such micro-optimizations are worth introducing at the cost of code simplicity and readability.

Notice that I am working towards the lazy deserialization, so there won't be any allocations during the deserialization except the allocation for vector of values, which is necessary

2025-04-01 14:55 UTC, Lorak-mmk commented on scylla-rust-wrapper/src/query_result.rs
>                      }),
Side question: currently you are always deserializing to `Row`, right? Is that the final approach? I don't thing it will allow implementing `cass_value_get_bytes`, for that you need full lazy deserialization.

2025-04-01 15:05 UTC, muzarski commented on scylla-rust-wrapper/src/query_result.rs
>                      }),
It's not the final approach. The follow-up PR will have two new structs defined:
```rust
pub struct CassRawValue<'result> {
    pub typ: &'result ColumnType<'result>,
    pub slice: Option<FrameSlice<'result>>,
}
impl DeserializeValue for CassRawValue { ... }

pub struct CassRawRow<'result> {
    columns: Vec<CassRawValue<'result>>,
}
impl DeserializeRow for CassRawRow { ... }
```

The `CassRawValue` is going to be stored directly in `CassValue`. Let's say someone calls `cass_value_get_float`, then we can easily deserialize the value using `f32 as DeserializeValue` because we store the `FrameSlice` and `ColumnType`. It also allows us to implement `cass_value_get_bytes` (because we store the serialized data).

2025-04-01 15:06 UTC, muzarski commented on scylla-rust-wrapper/src/query_result.rs
>                      }),
So in the end, we replace `Row` with `CassRawRow` and `CqlValue` with `CassRawValue`.

2025-04-01 15:19 UTC, muzarski commented
> Regarding the self-reference problem: maybe we could use `yoke` as we did in Rust Driver?

I considered this. I'd need to investigate how easy it would be to implement it. I'm not that familiar with `yoke` traits, but I always have the rust-driver deserialization code as a reference.

2025-04-02 04:03 UTC, muzarski commented on scylla-rust-wrapper/src/iterator.rs
> +    iterator: CassBorrowedSharedPtr<'result, CassIterator<'result>, CConst>,
It's not possible. The compiler complains that it does not know which of the two `iterator` lifetimes to choose.

`CassRowsResultIterator` before this commit:
```rust
pub struct CassRowsResultIterator<'result> {
    result: &'result CassRowsResult,
    position: Option<usize>,
}
```
I'll try to explain in pseudo code what happened before this commit.
```rust
fn cass_iterator_get_row<'ptr, 'result>(
    iterator: CassPtr<'ptr, CassIterator<'result>>
) -> CassPtr<'result, CassRow> {
     let iter: &'ptr CassIterator<'result> = BoxFFI::as_ref(iterator);
     // ... Some manipulation to obtain the reference to `CassRow`. Assume that we have get_row() method which returns the reference that iterator holds.
     // The lifetime is 'result, because iterator holds &'result CassRowsResult
     let row: &'result CassRow = iter.get_row(); 
     let result_ptr: CassPtr<'result, CassRow> = RefFFI::as_ptr(row);
     result_ptr
}
```
So in this case, the lifetime of the pointer `'ptr` is arbitrary. No constraints are needed.


`CassRowsResultIterator` after this commit:
```rust
pub struct CassRowsResultIterator<'result> {
    iterator: TypedRowIterator<'result, 'result, Row>,
    result_metadata: Arc<CassResultMetadata>,
    current_row: Option<CassRow>,
}
```

pseudo-code with lifetimes after this commit:
```rust
fn cass_iterator_get_row<'ptr, 'result>(
    iterator: CassPtr<'ptr, CassIterator<'result>>
) -> CassPtr<'result, CassRow> {
     let iter: &'ptr CassIterator<'result> = BoxFFI::as_ref(iterator);
     // Let's ignore the fact that this is an Option.
     // The lifetime is `'ptr` because the iterator OWNS this row. The lifetime of 'iter' is 'ptr
     let row: &'ptr CassRow = &iter.current_row; 
     // The pointer inherits the lifetime of the reference
     let result_ptr: CassPtr<'ptr, CassRow> = RefFFI::as_ptr(row);
     result_ptr

    // Oh no! But we asked for CassPtr<'result, CassRow>, and not CassPtr<'ptr, CassRow>.
    // The constraint 'ptr: 'result is required!
}
```

So the difference is that in the first case, the iterator **borrows** the `CassRow` with some lifetime `'result`, while in the second case, the iterator **owns** the `CassRow`.

2025-04-02 04:06 UTC, muzarski commented on scylla-rust-wrapper/src/iterator.rs
>          CassIterator::Row(row_iterator) => {
Done in a separate commit.

2025-04-02 04:31 UTC, muzarski commented on scylla-rust-wrapper/src/query_error.rs
>      Deserialization(#[from] DeserializationError),
Done in a separate commit

2025-04-02 04:31 UTC, muzarski commented
v2.0:
- addressed @wprzytula comments
- implemented self-borrowing using `yoke`, as @Lorak-mmk suggested

2025-04-02 10:07 UTC, Lorak-mmk approved these changes

2025-04-02 11:10 UTC, wprzytula requested changes

2025-04-02 11:10 UTC, wprzytula commented on scylla-rust-wrapper/src/iterator.rs
> +    iterator: CassBorrowedSharedPtr<'result, CassIterator<'result>, CConst>,
Thanks for so detailed explanation! I followed it carefully and understood a lot about practical implications of our new FFI model around lifetime-parameterised `CassPtr`.

2025-04-02 11:10 UTC, wprzytula commented on scylla-rust-wrapper/src/query_result.rs
>          }
:pick: I'd use this one in `new_from_raw_rows_and_metadata` for two reasons:
1. Not to duplicate the code around `Yoke`'s usage.
2. To separate and encapsulate `Yoke`-related code.

2025-04-02 11:10 UTC, wprzytula commented on scylla-rust-wrapper/src/query_result.rs
> +                });
:100: Good job with employing `Yoke`!

2025-04-02 11:10 UTC, wprzytula commented on scylla-rust-wrapper/src/cass_error.rs
> +use crate::execution_error::CassErrorResult;
:wrench:
`CassErrorResult::Query` variant still needs rename. Same for variables: `query_error` -> `execution_error`.

2025-04-02 12:43 UTC, muzarski commented
v2.1: Addressed @wprzytula comments

2025-04-02 12:51 UTC, wprzytula requested changes

2025-04-02 12:51 UTC, wprzytula commented on scylla-rust-wrapper/src/query_result.rs
> +        }
:wrench: IIUC, this constructor creates the `RowWithSelfBorrowedMetadata` based on **the first row** of `DeserializedMetadataAndRawRows`. I believe this property should be highlighted in the constructor's name, or at least in its docstring.

2025-04-02 12:56 UTC, muzarski commented
v2.2: Renamed the constructor so it indicates that it constructs first row only.

2025-04-02 12:59 UTC, wprzytula approved these changes
LGTM

2025-04-02 12:59 UTC, wprzytula commented on scylla-rust-wrapper/src/query_result.rs
> +    }
:question: Does this need to be `pub`? Isn't `pub(self)` enough?

2025-04-02 13:00 UTC, muzarski commented on scylla-rust-wrapper/src/query_result.rs
> +    }
No - apart from the internal usage, the test is using it as well.

2025-04-02 13:02 UTC, wprzytula commented on scylla-rust-wrapper/src/query_result.rs
> +    }
I though (perhaps wrongly) that the test is put in the same module (or in a submodule).

2025-04-02 13:07 UTC, muzarski commented on scylla-rust-wrapper/src/query_result.rs
> +    }
The structure is following:
```rust
mod query_result {
    mod row_with_self_borrowed_metadata {
        impl RowWithSelfBorrowedMetadata { ... }
    }

    mod tests {
         use super::row_with_self_borrowed_metadata::RowWithSelfBorrowedMetadata;
         ...
    }
}
```

The method cannot be `pub(self)`. But, it could be `pub(super)`. I'll do it.

2025-04-02 13:10 UTC, muzarski commented
v2.3: Reduced visibility of `RowWithSelfBorrowedMetadata` methods to `pub(super)`.

2025-04-02 13:12 UTC, wprzytula approved these changes

2025-04-02 13:14 UTC, Lorak-mmk approved these changes

2025-04-02 13:33 UTC, merged