Cass types v2
scylladb/cpp-rs-driver pull request #57
Opened 2021-12-01 14:39 UTC by Lorak-mmk

This is a continuation of https://github.com/hackathon-rust-cpp/cpp-rust-driver/pull/18
Changes from original PR:
- Derive PartialOrd and PartialEq for generated enums
- Reorder functions in cass_types to the same order as in spreadsheet.
- Reimplement cass_data_type_new - it's behaviour should depend on argument, as in cppdriver
- Add strlen helper function
- Implement missing variants of CassDataType
- Implement missing function of CassDataType - apart from is_frozen (I can't see a scenario where it returns true)
- CassDataType is now Arc, otherwise it's impossible to be semantically compatible with cppdriver.
- Overhaul of CassUserType (use macros to generate binding functions, binders for more values)

2021-12-06 17:44 UTC, piodul requested changes
Please do not submit PRs which introduces large changes in one commit and then modifies everything several times in later commits. It really wastes reviewers' time when one expects changes to be logically split into commits and then reviews the changes commit by commit, not to mention that it makes both maintaining the repo and reviewing the git history much harder.

I know that this PR is an expanded version of another PR, but we aren't going to merge the old one so there is no need to preserve the old commits.

Judging by how nice the PR looks in the "Files changed" view, I think that most of the commits in this PR could be squashed together. Please clean it up a little.

2021-12-06 17:44 UTC, piodul commented on scylla-rust-wrapper/src/user_type.rs
> +        let mut indices = Vec::new();
I understand that the borrow done by `get_udt_type` does not let you borrow `self` as mutable again in this `for` loop, but let's not introduce unnecessary allocations - the `indices` vector can be avoided with some reorganization. To avoid the problem you can start by converting `get_udt_type` to be a method of `CassDataType` and then inlining some of the logic of `set_option_by_index` inside the loop.

2021-12-06 17:44 UTC, piodul commented on scylla-rust-wrapper/src/user_type.rs
> +    // TODO: this function should probably somewhere else
When is this planned to be implemented?

2021-12-10 13:01 UTC, Lorak-mmk commented on scylla-rust-wrapper/src/user_type.rs
> +    // TODO: this function should probably somewhere else
In one of the future PR (probably sooner rather than later). This should be too hard to implement, as it's most likely going to just be direct translation of https://github.com/scylladb/cpp-driver/blob/master/src/data_type.hpp#L433-L564

2021-12-10 13:03 UTC, Lorak-mmk commented
Closing, refactored changes in https://github.com/hackathon-rust-cpp/cpp-rust-driver/pull/59 and https://github.com/hackathon-rust-cpp/cpp-rust-driver/pull/60

2021-12-10 13:03 UTC, closed without merging