Implement CassDataType, CassUserType, CassTuple
scylladb/cpp-rs-driver pull request #60
Opened 2021-12-10 13:02 UTC by Lorak-mmk

Based on https://github.com/hackathon-rust-cpp/cpp-rust-driver/pull/58
Implements CassDataType
Implements CassUserType, CassTuple and all bindings related to them, using new macros.

2022-01-03 16:59 UTC, piodul requested changes

2022-01-03 16:59 UTC, piodul commented on scylla-rust-wrapper/src/cass_types.rs
> +        for (field_name, field_type) in self.field_types.iter() {
Nit: not sure if you like terse, iterator-base style, but if you do this should work, too:
```rust
self.field_types
    .iter()
    .find(|(field_name, _)| field_name == name)
    .map(|(_, t)| t)
```

2022-01-03 16:59 UTC, piodul commented on scylla-rust-wrapper/src/user_type.rs
> +    unsafe fn set_option_by_index(&mut self, index: usize, value: Option<CqlValue>) -> CassError {
Why is this function unsafe?

2022-01-03 16:59 UTC, piodul commented on scylla-rust-wrapper/src/user_type.rs
> +    unsafe fn set_option_by_name(&mut self, name: &str, value: Option<CqlValue>) -> CassError {
Ditto?

2022-01-03 16:59 UTC, piodul commented on scylla-rust-wrapper/src/tuple.rs
> +    pub data_type: CassDataTypeArc,
It was a bit surprising for me to find out that the tuple in cpp driver actually only validates the first N types specified in its data type (and if it is a completely new tuple, it doesn't validate anything). Until I realized this, the logic looked incorrect to me and I was thinking how it should be fixed.

Please describe this behavior in this file so that other people reading/modifying this code in the future will understand what is going on quicker.

2022-01-07 17:46 UTC, Lorak-mmk commented on scylla-rust-wrapper/src/tuple.rs
> +    pub data_type: CassDataTypeArc,
I'm don't fully understand your comment, but it made me look at cppdriver's tuple code again, and it seems my implementation here is incorrect in few places. I'll fix it and leave some comments.

2022-01-07 19:00 UTC, Lorak-mmk commented
@piodul I fixed all issues pointed by you. Could you check if current tuple implementation is consistent with cpp-driver? I don't trust myself - I was sure it was correct before, but today it turned out to be wrong.

2022-01-18 11:34 UTC, haaawk commented
@piodul could you help @Lorak-mmk with tuples question?

2022-01-18 14:33 UTC, piodul commented on scylla-rust-wrapper/src/tuple.rs
> +    pub data_type: CassDataTypeArc,
I guess the most confusing part for me was the `inner_types.len() > index` check. It is always true if the tuple was created with `cass_tuple_new_from_data_type` and always false when with tuples created by `cass_tuple_new`. It does not depend on the value of `index` at all.

To make things worse, I didn't know that either `inner_types.len() == 0` or `inner_types.len() == self.items.len()`, so I was wondering what would be the meaning of the original check if `0 < inner_types.len() < self.items.len()`.

In addition to the comment with description (which I can see you have already added) I would suggest expressing intent more clearly in the code. Maybe we could change `data_type` into an `Option<CassDataTypeArc>`? It would be `None` if created with `cass_tuple_new`, and `Some` in the other case.

2022-01-18 15:03 UTC, piodul commented
@Lorak-mmk I'm not too familiar with the cpp-driver's logic, but from what I managed to understand, your current logic checks out. In the future, it would be worthwhile to write differential tests in order to help enforce the same behavior as in the cpp-driver.

2022-01-18 15:05 UTC, piodul reviewed
Please address the issue of confusing `data_type` for untyped tuples and I think it will be OK to merge.

2022-03-02 12:07 UTC, Lorak-mmk commented
Fixed. I had to use global variable to handle `cass_tuple_data_type` for tuples created by `cass_tuple_new` @piodul

2022-03-21 11:39 UTC, piodul approved these changes

2022-03-21 11:40 UTC, merged