Add RowIterator implementation
scylladb/cpp-rs-driver pull request #64
Opened 2022-07-08 17:30 UTC by Gor027

This PR is dependent upon #63

As the C++ driver interface requires functions `cass_iterator_from_result` and `cass_iterator_from_row` to return `CassIterator`, this PR modifies already existing `CassIterator` struct to be enum and to contain `CassResultIterator` and `CassRowIterator`.
Additionally, some necessary functions were implemented in order to have at least 1 passing integration test. So, it should pass a basic test called `BasicsTests.Integration_Cassandra_RowsInRowsOut`.

2022-07-21 11:24 UTC, piodul requested changes

2022-07-21 11:24 UTC, piodul commented on scylla-rust-wrapper/src/query_result.rs
> +            };
Tip: you can use `map_or` to make is shorter:

```rust
let new_pos = result_iterator.map_or(0, |x| x + 1);
```

2022-07-21 11:24 UTC, piodul commented on scylla-rust-wrapper/src/query_result.rs
> +#[repr(C)]
`repr(C)` is not needed here. It's only important if you have a corresponding definition in a C header and you want both Rust and C to use the same struct. If you return an opaque pointer to C then `repr` doesn't matter and it's better to leave it as default.

2022-07-21 11:24 UTC, piodul commented on scylla-rust-wrapper/src/query_result.rs
> +#[repr(C)]
No need for `repr(C)`.

2022-07-21 11:24 UTC, piodul commented on scylla-rust-wrapper/src/query_result.rs
> +#[repr(C)]
No need for `repr(C)`.

2022-07-21 11:24 UTC, piodul commented on scylla-rust-wrapper/src/query_result.rs
> +        let column: &CassValue = row_iterator.row.columns.get(iter_position).unwrap();
Is this panic here intentional? If the iterator goes past the last column, there will be a panic here. How does the original cpp driver code behave?

2022-07-21 11:24 UTC, piodul commented on scylla-rust-wrapper/src/query_result.rs
> +    Arc::into_raw(Arc::new(cass_data_type))
The docstring next to `cass_value_data_type` contains the following text:

```
 * @return Returns a reference to the data type of the value.
 * Do not free this reference as it is bound to the lifetime of the value.
```

We cannot allocate and return new objects because users won't be freeing them and this will lead to memory leaks.

You need to store a `CassDataType` along with `CassValue` somehow.

2022-07-21 11:24 UTC, piodul commented on scylla-rust-wrapper/src/query_result.rs
> +            };
Use `map_or` here, too.

2022-07-21 21:07 UTC, Gor027 commented on scylla-rust-wrapper/src/query_result.rs
> +        let column: &CassValue = row_iterator.row.columns.get(iter_position).unwrap();
If the iterator goes past the last column then `cass_iterator_next` should return `false` and `cass_iterator_get_column` will not get executed.

2022-07-22 08:52 UTC, Gor027 commented on scylla-rust-wrapper/src/query_result.rs
> +    Arc::into_raw(Arc::new(cass_data_type))
The only way I could think of is to change the type `CassValue` to either a tuple or a struct to contain `CassDataType`, but that would cause a lot more other changes. Perhaps, you have other suggestions?

2022-07-22 09:03 UTC, piodul commented on scylla-rust-wrapper/src/query_result.rs
> +        let column: &CassValue = row_iterator.row.columns.get(iter_position).unwrap();
Nothing prevents users from calling `cass_iterator_get_column` after `cass_iterator_next` returns false. In such case we should behave as the original driver does.

Besides, you already implemented a similar function `cass_iterator_get_row` and there you return `std::ptr::null()` when it is called on an exhausted iterator. We have two similar functions which behave inconsistently. Please check how the original driver behaves and align those functions with this behavior (I'd expect that they return null).

2022-07-22 09:10 UTC, piodul commented on scylla-rust-wrapper/src/query_result.rs
> +    Arc::into_raw(Arc::new(cass_data_type))
I'm afraid changing `CassValue` to a struct that contains `CassDataType` is the simplest solution that I can think of.

2022-07-26 16:26 UTC, piodul commented on scylla-rust-wrapper/src/query_result.rs
> +    Arc::into_raw(Arc::new(cass_data_type))
This doesn't really fix it. OK, you added `value_type` field to `CassValue`, but you are still using `Arc::new()` which allocates a new object. You will still have memory leaks because users won't free this object.

Once again - the docstring explains that the function is supposed to return a `CassDataType` which lives as long as the `CassValue` it is associated with. Therefore, you just need to return a pointer to the `value_type`.

2022-07-26 16:45 UTC, piodul commented
Please avoid addressing review comments by adding commits that fix bugs introduced in previous commits. In particular, the first commit still has the issue with the lifetime of the value returned from `cass_value_data_type`. You should first change the `CassValue` to store `CassDataType` so that you can correctly implement `cass_value_data_type` in the next commit.

Moreover, please add commit descriptions. Each description should explain what is changed in the commit and why.

2022-07-27 10:59 UTC, piodul requested changes

2022-07-27 10:59 UTC, piodul commented on scylla-rust-wrapper/src/query_result.rs
> +    match val.value.clone() {
Why `.clone()`? You aren't moving out anything of the value you are matching on, so probably `match &val.value` will suffice.

2022-07-27 10:59 UTC, piodul commented on scylla-rust-wrapper/src/query_result.rs
> +pub fn get_type_from_value(value: Option<CqlValue>) -> CassDataType {
CqlValue might potentially be a big object. There is no reason for this function to receive it by value, it only forces the caller to `.clone()` it. Please change the type of `value` to `&Option<CqlValue>`.

2022-07-27 10:59 UTC, piodul commented on scylla-rust-wrapper/src/query_result.rs
> +        return Box::into_raw(Box::new(column)) as *const CassValue;
This function does not allocate a new value in the original implementation. It just returns a reference to an existing `CassValue`.

You need to make bigger changes in order to make it work. More specifically, You need to change `CassRow` so that it keeps a `Vec<CassValue>`. In turn, you probably need to modify the definition of `CassResult`, too. I suggest doing those changes first, in a separate commit, and then continuing with the rest.

2022-07-29 09:58 UTC, piodul requested changes

2022-07-29 09:58 UTC, piodul commented on scylla-rust-wrapper/src/query_result.rs
> +    let row = match iter
Nit: please avoid doing irrelevant changes like this. They introduce unnecessary noise in the diff.

If you want to do some cleanups (and have a good reason to do so, e.g. it is related to the PR) then I recommend putting them in a separate commit. In this case it's better to drop it altogether IMO.

2022-07-29 09:58 UTC, piodul commented on scylla-rust-wrapper/src/query_result.rs
> +    pub result_: Arc<CassResultData>,
Why is there an underscore at the end of `result_`?

Besides, wouldn't a name like `metadata` be better, like in `CassResult::metadata`? I don't understand why it is inconsistent now.

2022-07-29 09:58 UTC, piodul commented on scylla-rust-wrapper/src/session.rs
> +}
Tip: no need to write such a big `match` block. The `populate_cass_rows_from_rows` function returns an `Option`, so you can just use the `?` operator:

```rust
let rows = rows.as_ref()?;
let cass_rows = /* ... */
```

2022-07-29 09:58 UTC, piodul commented on scylla-rust-wrapper/src/session.rs
> +fn populate_cass_rows_from_rows(
Nitpick: usually, `populate` means filling an already existing structure with data. This function creates a completely new `Option<Vec<CassRow>>`, so how about using `create` instead of `populate`?

2022-07-29 09:58 UTC, piodul commented on scylla-rust-wrapper/src/query_result.rs
> +// This was const for some reason, seems like a mistake in cpp driver
It looks like `free_arced` takes a const pointer as an argument. Shouldn't this function work with `*const CassResult`?

2022-07-29 09:58 UTC, piodul commented on scylla-rust-wrapper/src/query_result.rs
> +    let column_spec: &ColumnSpec = result_from_raw.metadata.col_specs.get(index_usize).unwrap();
How does the original function behave when `index_usize` is larger than the last column index? I doubt that we should crash here.

2022-07-29 09:58 UTC, piodul commented on scylla-rust-wrapper/src/session.rs
> +    rows: &Option<Vec<Row>>,
Takes `rows` by value, not by reference. This way you can later use `rs.into_iter()` instead of `rs.iter()` and avoid copying.

2022-07-29 09:58 UTC, piodul commented on scylla-rust-wrapper/src/session.rs
> +fn populate_cass_row_columns(row: &Row) -> Vec<CassValue> {
If you address my comment about `populate_cass_rows_from_rows`, then you will be able to change this function so that it takes `row` by value.

Also, please change `populate` to `create` in the function's name.

2022-07-29 09:58 UTC, piodul commented on scylla-rust-wrapper/src/cass_types.rs
> +pub fn get_type_from_value(value: &Option<CqlValue>) -> CassDataType {
You cannot get a complete type just from the value alone. It doesn't contain full information about complex data types, i.e.: lists, sets, maps and UDTs. You must get this information from the metadata in `CassResultData`.

2022-07-29 11:31 UTC, Gor027 commented on scylla-rust-wrapper/src/query_result.rs
> +
We check it here, and in case it's larger than the last column index, just returns a `CassError::CASS_ERROR_LIB_INDEX_OUT_OF_BOUNDS`. The implementation is the same as in the C++ driver.

2022-07-29 11:33 UTC, Gor027 commented on scylla-rust-wrapper/src/query_result.rs
> +    let column_spec: &ColumnSpec = result_from_raw.metadata.col_specs.get(index_usize).unwrap();
We check it here, and in case it's larger than the last column index, just returns a `CassError::CASS_ERROR_LIB_INDEX_OUT_OF_BOUNDS`. The implementation is the same as in the C++ driver.

2022-07-29 11:35 UTC, Gor027 commented on scylla-rust-wrapper/src/query_result.rs
> +    let row = match iter
Here, the type of `row` was changed to `CassRow`, so I just removed the explicit type annotation. Maybe it is better to annotate it as `CassRow`.

2022-07-29 12:12 UTC, Gor027 commented on scylla-rust-wrapper/src/cass_types.rs
> +pub fn get_type_from_value(value: &Option<CqlValue>) -> CassDataType {
`CassResultData.col_specs` has enough information to retrieve a complete type, however, it's not accessible. The field `typ: ColumnType` of `ColumnSpec` is not public in the Rust driver. I think the only way of getting column-specific metadata is the `QueryResult.col_specs`, so we are obliged to make some changes in the Rust driver side: making the field `typ: ColumnType` to be public. Perhaps we should do that in another PR?

2022-07-29 12:36 UTC, Gor027 commented on scylla-rust-wrapper/src/cass_types.rs
> +pub fn get_type_from_value(value: &Option<CqlValue>) -> CassDataType {
EDIT: sorry, I looked at the forked driver version, in the original repo the mentioned `ColumnSepc.typ` is public. So, after merging #67, the function `get_type_from_value` can be fixed to return complete type.

2022-08-02 09:23 UTC, Gor027 commented on scylla-rust-wrapper/src/cass_types.rs
> +pub fn get_type_from_value(value: &Option<CqlValue>) -> CassDataType {
@piodul This is fixed now, could you please review it once again?

2022-08-02 13:13 UTC, piodul requested changes

2022-08-02 13:13 UTC, piodul commented on scylla-rust-wrapper/src/cass_types.rs
> +pub fn get_column_type(column_type: Option<ColumnType>) -> CassDataType {
`ColumnType` can be potentially heavy when describing compound types such as collections or UDTs. This function doesn't have to take `column_type` by value, you can take it by reference.

2022-08-02 13:13 UTC, piodul commented on scylla-rust-wrapper/src/session.rs
> +    rows: &Option<Vec<Row>>,
Changing the type of `rows` should be made in the first commit.

2022-08-02 13:13 UTC, piodul commented on scylla-rust-wrapper/src/session.rs
> +        .map(|(index, col)| CassValue {
Tip: the length of `col_specs` and `row.columns` should always be the same, so you should be able to just use `zip`:

```rust
row.columns
    .iter()
    .zip(metadata.col_specs.iter())
    .map(|(col, spec)| {
        // ...
    })
    .collect();
```

2022-08-03 10:15 UTC, piodul commented on scylla-rust-wrapper/src/session.rs
> +    let rows = rows.as_ref()?;
Drop `as_ref()` here and you won't have to clone in line `117`. Rows contain user data so they can be potentially large and we would like to avoid copies.

2022-08-03 16:23 UTC, piodul commented on scylla-rust-wrapper/src/query_result.rs
> +    let column_spec: &ColumnSpec = result_from_raw.metadata.col_specs.get(index_usize).unwrap();
Right, I missed it, thanks.

2022-08-03 16:25 UTC, piodul approved these changes

2022-08-05 08:50 UTC, avelanarius approved these changes

2022-08-05 14:25 UTC, merged