Basic tests
scylladb/cpp-rs-driver pull request #65
Opened 2022-07-20 08:55 UTC by Gor027

This PR is dependent upon #64

This PR adds implementation for some necessary functions to pass all `BasicTests`.

2022-08-03 17:12 UTC, piodul requested changes

2022-08-03 17:12 UTC, piodul commented on .github/workflows/build.yml
> +      run: valgrind --error-exitcode=123 ./cassandra-integration-tests --version=release:5.0.0 --category=CASSANDRA --verbose=ccm --gtest_filter="ClusterTests.*:BasicsTests.*"
This change seems to remove tests from the filter. Is that intended?

2022-08-03 17:12 UTC, piodul commented on scylla-rust-wrapper/src/query_result.rs
> +    let mut b = BytesMut::from(slice::from_raw_parts(
[`Bytes::copy_from_slice`](https://docs.rs/bytes/latest/bytes/struct.Bytes.html#method.copy_from_slice) will be more explicit here than `Bytes::from`. Its name more clearly conveys what exactly it is doing.

2022-08-03 17:12 UTC, piodul commented on scylla-rust-wrapper/src/query_result.rs
> +            .as_ptr() as *const c_char;
You are (most probably) returning a pointer to freed memory here.

.clone() creates a temporary `Option<Bytes>` object, cloned from `paging_state`. I'm not entirely sure how it will work under the hood, but one of two things will happen:

- the new object will increase a reference count of the memory the old `Bytes` object pointed to (semantics similar to `Arc`),
- or the new object will allocate its own memory and will copy the contents from the old `Bytes` (semantics similar to `Box`).

If it's the first one, then you will just increase and decrease the reference count unnecessarily, but it will work.

If it's the second, then it's worse. You then call `as_ptr()` to get the pointer to the contents of the temporary `Bytes`, return it, but then the temporary object is deallocated, and the pointer you just returned points to freed memory.

----
I guess that the lifetime of the memory pointed by the result of `cass_result_paging_state_token` is bound to the `CassResult`, right? If so, then you should call `as_ref().unwrap().as_ptr()`, similarly to the previous statement.

2022-08-03 17:12 UTC, piodul commented on scylla-rust-wrapper/src/query_result.rs
> +    if result_from_raw.metadata.paging_state.is_none() {
Instead of checking for `is_none()` and then `unwrap()`-ping, I'd recommend converting the `if {} else {}` block into `match` block.

2022-08-03 17:12 UTC, piodul commented on tests/src/integration/tests/test_basics.cpp
> +  if (server_version_ >= "release:2.2.0") {
I'm not sure it is the best way to do it. All other tests which perform such a comparison will probably have to be updated in such fashion. Perhaps we should strip the `release:` prefix elsewhere, before `server_version_` is initialized.

@jul-stas is this problem handled in the original driver?

2022-08-08 11:08 UTC, Gor027 commented on .github/workflows/build.yml
> +      run: valgrind --error-exitcode=123 ./cassandra-integration-tests --version=release:5.0.0 --category=CASSANDRA --verbose=ccm --gtest_filter="ClusterTests.*:BasicsTests.*"
Actually, it does not remove a test instead, it enables all `BasicsTests` including the `RowsInRowsOut` test in it.

2022-08-08 11:12 UTC, Gor027 commented on scylla-rust-wrapper/src/query_result.rs
> +    let mut b = BytesMut::from(slice::from_raw_parts(
I think `BytesMut` does not have such a method as `copy_from_slice` or similar. However, I have slightly changed the implementation to first ensure the necessary capacity allocated and then to create `Bytes` from a slice, so that we can avoid unnecessary reallocation.

2022-08-08 11:17 UTC, Gor027 commented on tests/src/integration/tests/test_basics.cpp
> +  if (server_version_ >= "release:2.2.0") {
I have changed the implementation to set `server_version_` to `3.0.8` in case provided version has the prefix `release:`. The `cpp-driver` tests are also run with the same version on Jenkins, and some of the tests which are not disabled may be skipped: e.g. `NoCompactEnabledConnection` test in `BasicsTests`.

2022-08-08 11:21 UTC, Gor027 commented
V2:

* Changed `cass_statement_set_paging_state_token` implementation to first ensure necessary capacity and then create Bytes from a slice.
* `server_version_` is statically set to `3.0.8` if the provided version has the prefix `release:`.

2022-08-08 13:33 UTC, piodul commented on .github/workflows/build.yml
> +      run: valgrind --error-exitcode=123 ./cassandra-integration-tests --version=release:5.0.0 --category=CASSANDRA --verbose=ccm --gtest_filter="ClusterTests.*:BasicsTests.*"
Oh, I see. The filter used to include tests which match on `BasicsTests.*RowsInRowsOut`, now it is `BasicsTests.*` which matches on a larger number of tests.

2022-08-08 15:31 UTC, piodul commented on scylla-rust-wrapper/src/query_result.rs
> +    match &value_from_raw.value {
AFAIK the original `cass_value_get_bytes` works on all CQL types (see [here](https://github.com/scylladb/cpp-driver/blob/739b87c15428d1d26ec0160444b7b693543772c2/src/value.cpp#L142-L149)). I understand that it might be difficult to implement it properly right now because the rust driver doesn't allow to return raw, serialized values but rather returns CqlValue - so please add a TODO or a FIXME comment about it.

2022-08-08 15:31 UTC, piodul commented on scylla-rust-wrapper/src/query_result.rs
> +    let mut b = BytesMut::from(slice::from_raw_parts(
Now it's even better than what I requested, thanks.

2022-08-08 15:33 UTC, piodul reviewed
LGTM after adding the TODO comment.

@jul-stas please take a look, especially at the part which sets the version to "3.0.8".

2022-08-08 16:19 UTC, piodul approved these changes

2022-08-11 10:47 UTC, merged