Import fixed version of scylla-rust-driver
scylladb/cpp-rs-driver pull request #67
Opened 2022-07-26 10:39 UTC by Gor027

This PR imports a fixed version of `scylla-rust-driver` (`0.4.7`) instead of [this](https://github.com/hackathon-rust-cpp/scylla-rust-driver.git) fork. Also, it adds necessary modifications in order to compile successfully.

2022-07-26 10:46 UTC, piodul commented on scylla-rust-wrapper/src/query_error.rs
> +        },
Why not extract the `match consistency { ... }` part to a helper function/lambda? It's repeated several times.

2022-07-26 11:02 UTC, piodul commented on scylla-rust-wrapper/src/query_result.rs
> -        Some(CqlValue::Timeuuid(uuid)) => *out = (*uuid).into(),
This should probably be not fixed like this. Look at `scylla-rust-wrapper/src/uuid.rs` - there is a `impl From<Uuid> for CassUuid` conversion defined by us. I'm not sure if it works the same as what you do here, and it would be nice to keep using it

I suspect that the `into()` conversion stopped working because you bumped the rust driver crate version before bumping the uuid crate version. The driver requires `uuid = 1.0`, but the wrapper requires `uuid = 0.8.2`; those versions are not compatible, so the Uuid struct used by the driver is __not__ the same thing as Uuid used in the wrapper.

I can see that you bumped the uuid requirement to `1.1.2`, which should be compatible with `1.0` required by the driver. IMO, the `.into()` conversion should work. Could you check?

2022-07-26 11:12 UTC, Gor027 commented on scylla-rust-wrapper/src/query_result.rs
> -        Some(CqlValue::Timeuuid(uuid)) => *out = (*uuid).into(),
Yes, seems that it works with the uuid `1.1.2` version.

2022-07-27 10:22 UTC, piodul requested changes

2022-07-27 10:22 UTC, piodul commented on scylla-rust-wrapper/src/binding.rs
> +            |v: crate::uuid::CassUuid| Ok(Some(Uuid(uuid::Uuid::from_u64_pair(v.time_and_version, v.clock_seq_and_node)))),
`.into()` should work now, so this is unnecessary (and probably incorrect).

2022-07-27 10:22 UTC, piodul commented on scylla-rust-wrapper/src/query_error.rs
> +unsafe fn get_cass_consistency_from_legacy(consistency: &LegacyConsistency) -> CassConsistency {
Does this function need to be unsafe?

2022-07-27 10:22 UTC, piodul commented on scylla-rust-wrapper/src/cluster.rs
> +    DcAwareRoundRobinPolicy { local_dc: &'static str },
Using `&'static str` is a bad idea here. In the original implementation, when you create a DC-aware policy via `cass_cluster_set_load_balance_dc_aware_n`, that function makes a copy of the string. You should use `String` here instead so that the `CassClusterChildLoadBalancingPolicy` manages its own copy of the string.

2022-07-28 09:48 UTC, piodul commented on scylla-rust-wrapper/Cargo.toml
> +scylla = "0.4.7"
The fixes you sent for the driver are not present in 0.4.7 or any other version yet. You will have to point to a specific commit in the driver's repo.

2022-07-29 10:03 UTC, piodul requested changes

2022-07-29 10:03 UTC, piodul commented on scylla-rust-wrapper/Cargo.toml
> +scylla = { git = "https://github.com/scylladb/scylla-rust-driver.git", branch = "main" }
Pointing to a branch is risky, because over time more commits are pushed and suddenly the project won't compile anymore. I'd recommend pointing to current latest commit of the main branch. See here: https://stackoverflow.com/a/54197014

2022-07-29 10:14 UTC, Gor027 commented on scylla-rust-wrapper/Cargo.toml
> +scylla = { git = "https://github.com/scylladb/scylla-rust-driver.git", branch = "main" }
I pointed first to the exact commit [here](https://github.com/scylladb/cpp-rust-driver/commit/3ef3c790bc668f870ea80b33abf8504aa8064549), then changed to the `main` branch, thinking that maybe we should keep up with the new changes in the Rust driver.

2022-07-29 12:42 UTC, piodul approved these changes

2022-08-01 14:12 UTC, avelanarius commented on scylla-rust-wrapper/src/cass_error.rs
> +            QueryError::TooManyOrphanedStreamIds(_) => CassError::CASS_ERROR_LAST_ENTRY,
Although this problem was not introduced by you, `CASS_ERROR_LAST_ENTRY` seems like a placeholder for a correct error mapping. Please add "FIXME: CASS_ERROR_LAST_ENTRY as placeholder for a correct error" so that we don't forget about it.

2022-08-01 14:14 UTC, avelanarius approved these changes
LGTM, apart from my one comment.

2022-08-01 14:27 UTC, merged