Prepared tests
scylladb/cpp-rs-driver pull request #68
Opened 2022-07-28 14:26 UTC by Gor027

## Pre-review checklist

- [x] I have split my patch into logically separate commits.
- [x] All commit messages clearly explain what they change and why.
- [x] PR description sums up the changes and reasons why they should be introduced.
- [x] I have enabled appropriate tests in `.github/workflows/build.yaml` in `gtest_filter`.

This PR is dependent upon #65

Adds necessary implementations to pass all `PreparedTests` besides `PreparedIDUnchangedDuringReprepare`, which is also ignored in the C++ driver.
Certain validations in tests are commented out for now, as their corresponding implementations in Rust are not yet present.
Also, `DowngradingConsistency` retry policies in those tests are changed to be `Default` retry consistency, as `DowngradingConsistency` is deprecated and not supported by the Rust driver.

2022-08-09 14:07 UTC, avelanarius commented on tests/src/integration/tests/test_prepared.cpp
> +//  EXPECT_EQ(bound_statement.consistency(), CASS_CONSISTENCY_LOCAL_QUORUM);
Missing `// TODO` comment

2022-08-09 16:00 UTC, piodul requested changes

2022-08-09 16:00 UTC, piodul commented on scylla-rust-wrapper/src/statement.rs
> +        Statement::Prepared(inner) => Arc::make_mut(inner).set_timestamp(Some(timeout_ms as i64)),
Timestamp is a completely different thing than timeout.

- A CQL timestamp defines the order in which writes are applied to the database.
- Timeout (here, client-side timeout) means the time the driver will wait until response arrives from the database. If no response arrives within the timeout period, the driver is supposed to return an error.

Here, I think you have accidentally implemented `cass_statement_set_timestamp`.

Currently, the rust driver doesn't support client timeouts directly, but you can implement them yourself in the wrapper code. You need to keep the timeout in the CassStatement somewhere, wrap `session.execute()` etc. calls with [`tokio::time::timeout`](https://docs.rs/tokio/latest/tokio/time/fn.timeout.html) and handle the timeout error returned by the `tokio::time::timeout` call appropriately.

2022-08-09 16:00 UTC, piodul commented on scylla-rust-wrapper/src/session.rs
> +    let statement_opt = ptr_to_ref(statement);
Why do those names have an `_opt` suffix? Those aren't `Option`s?

2022-08-09 16:00 UTC, piodul commented on scylla-rust-wrapper/src/session.rs
> +    };
By doing `statement.clone()`, you are cloning the whole statement, but then you only need a small part of it and you have unnecessarily cloned the whole statement.

Perhaps you can match on a reference (`&statement`) and move `.clone()` to the first match, like this:

```rust
let query = match &statement {
    Statement::Simple(q) => q.contents.clone(),
    Statement::Prepared(ps) => ps.get_statement().to_string(),
};
```

2022-08-09 16:00 UTC, piodul commented on scylla-rust-wrapper/src/session.rs
> +        Statement::Prepared(ps) => ps.get_statement().to_string(),
I don't think it makes sense at all to prepare a prepared statement again. I think in this case it makes sense to just clone a prepared statement, put it into a box and immediately return it.

2022-08-09 16:00 UTC, piodul commented on scylla-rust-wrapper/src/session.rs
> +            .prepare(query)
Instead of passing a string, you can put a `Query` here. AFAIK the resulting `PreparedStatement` should inherit all properties of the original `Query`, so setting them manually later shouldn't be necessary.

2022-08-09 16:00 UTC, piodul commented on scylla-rust-wrapper/src/session.rs
> +fn create_col_index_mapping(col_specs: &[ColumnSpec]) -> HashMap<String, usize> {
I think that constructing a hashmap to speed up lookup by name is an overkill. The number of columns is usually small, so linear lookup should be sufficient. Creating a hashmap allocates (at least one allocation for the hashmap itself + one allocation for each String), so it would be best to avoid it.

2022-08-17 13:53 UTC, avelanarius commented on scylla-rust-wrapper/src/session.rs
> +        match tokio::time::timeout(Duration::from_millis(request_timeout_ms), future).await {
In the future it should be replaced with driver's own client-side timeout implementation, which is a planned feature for the driver itself (https://github.com/scylladb/scylla-rust-driver/issues/304). 

cc: @wprzytula

2022-08-17 13:54 UTC, avelanarius commented on scylla-rust-wrapper/src/statement.rs
> +    pub request_timeout_ms: cass_uint64_t,
Maybe replace it with `Option<cass_uint64_t>` - if option is `None` then apply no timeout, instead of hardcoding 2 year timeout.

2022-08-17 14:00 UTC, avelanarius commented on scylla-rust-wrapper/src/session.rs
> +    let statement = statement_from_raw.statement.clone();
Small naming nit, maybe replace it with:

```
    let session = ptr_to_ref(cass_session);
    let statement = ptr_to_ref(statement);
    let statement = statement_from_raw.statement.clone();
```

2022-08-17 14:04 UTC, wprzytula commented on scylla-rust-wrapper/src/session.rs
> +        match tokio::time::timeout(Duration::from_millis(request_timeout_ms), future).await {
I confirm, I'm going to work on such implementation soon.

2022-08-17 16:57 UTC, avelanarius commented on scylla-rust-wrapper/src/session.rs
> +        match tokio::time::timeout(Duration::from_millis(request_timeout_ms), future).await {
And to be clear, we won't be waiting for this driver support before merging this PR - it's good as-is.

2022-08-18 08:09 UTC, Gor027 commented on scylla-rust-wrapper/src/session.rs
> +    let statement = statement_from_raw.statement.clone();
Do you mean to rename `session_from_raw` and `statement_from_raw` to `session` and `statement`?

2022-08-18 08:17 UTC, avelanarius commented on scylla-rust-wrapper/src/session.rs
> +    let statement = statement_from_raw.statement.clone();
Yes, but it looks OK after the latest commits.

2022-08-18 08:56 UTC, merged