Add SSL/TLS support
scylladb/cpp-rs-driver pull request #70
Opened 2022-08-16 08:34 UTC by Gor027

## Pre-review checklist

- [x] I have split my patch into logically separate commits.
- [x] All commit messages clearly explain what they change and why.
- [x] PR description sums up the changes and reasons why they should be introduced.
- [x] I have enabled appropriate tests in `.github/workflows/build.yaml` in `gtest_filter`.

This PR adds SSL/TLS support to the driver.
Integrations tests that are enabled in the C++ driver and are actually run during `Jenkins` builds, are also enabled for the `cpp-rust-driver`. Besides the integrations tests, it was also tested manually using the examples from the C++ driver.

2022-08-25 13:54 UTC, piodul requested changes

2022-08-25 13:54 UTC, piodul commented on scylla-rust-wrapper/src/ssl.rs
> +}
The difference between `cass_ssl_new` and `cass_ssl_new_no_lib_init` is that the first is supposed to perform some additional initialization. What does this initialization do in the original implementation?

2022-08-25 13:54 UTC, piodul commented on scylla-rust-wrapper/src/cluster.rs
> +    if cass_ssl.trusted_cert.is_some() {
Use `if let Some(trusted_cert) = &cass_ssl.trusted_cert` please, instead of `is_some()` + `unwrap()`. The less places which can potentially panic in the code, the better.

2022-08-25 13:54 UTC, piodul commented on scylla-rust-wrapper/src/cluster.rs
> +        ssl_context_builder.set_certificate(cert).unwrap();
There are some `ssl_context_builder.set_xyz` operations here which can fail, and you `unwrap` them. Are they supposed to always succeed? If they do, please add comments which explain that. If not, then I think that the implementation need to be rethought so that those operations are performed in functions that can return errors.

It is worth noting that the original implementation's `cass_cluster_set_ssl` is very simple and doesn't call any functions from the `openssl` library. If we are using openssl directly like the original impl, then maybe our implementation of the SSL-related functions can mirror the original ones more closely?

2022-08-26 11:10 UTC, Gor027 commented on scylla-rust-wrapper/src/ssl.rs
> +}
Yes, in `cass_ssl_new`, `openssl::init()` should be explicitly called. `SslContextBuilder::new()` does that anyway, so I thought that should be enough.

2022-08-26 11:32 UTC, Gor027 commented on scylla-rust-wrapper/src/cluster.rs
> +        ssl_context_builder.set_certificate(cert).unwrap();
The C++ driver implementation creates an `OpenSslContext` and sets the necessary configuration explicitly, however, `rust-openssl` obliges to use the `SslContextBuilder` to do so, and then consume the builder to create a `SslContext`. Another limitation is that `SslContextBuilder` cannot be cloned, so it makes us create the builder once and immediately consume it, as it is done in the `cass_cluster_set_ssl`. The `SslContext` setters, e.g. `cass_ssl_add_trusted_cert`, `cass_ssl_set_verify_flags`, validate the user-provided configuration, and `cass_cluster_set_ssl` only sets them in the `SslContextBuilder`, so I think those `unwrap` calls should always succeed.

2022-08-29 15:58 UTC, Gor027 commented
V2:

The SSL support is reimplemented, this time based on the `openssl-sys` crate which provides rust bindings for the original `OpenSSL` library. With this approach, it is possible to mirror the behavior of the SSL-related functions more closely. As before, the functionality was tested manually on ScyllaDB (some integration tests are enabled), and it was also tested on a Cassandra cluster.

2022-08-30 14:19 UTC, avelanarius commented on .github/workflows/build.yml
> +:SslNoClusterTests*:SslNoSslOnClusterTests*\
@Gor027 Also run tests with Cassandra (not only Scylla 5.0.0) so that we can test (almost?) all SSL tests.

2022-09-06 13:53 UTC, Gor027 commented on .github/workflows/build.yml
> +:SslNoClusterTests*:SslNoSslOnClusterTests*\
After merging [this](https://github.com/scylladb/cpp-rust-driver/pull/74) PR, I will add running SSL-related tests on Cassandra.

2022-09-08 10:38 UTC, piodul requested changes
There seems to be some error checking/reporting logic missing from the ported function (`ssl_log_errors`, `ERR_peek_error`).

2022-09-08 10:38 UTC, piodul commented on scylla-rust-wrapper/src/ssl.rs
> +
There are some calls missing from the original implementation here:

```c++
SSL_CTX_set_verify(ssl_ctx_, SSL_VERIFY_NONE, ssl_no_verify_callback);
// Limit to TLS 1.2 for now. TLS 1.3 has broken the handshake code.
SSL_CTX_set_max_proto_version(ssl_ctx_, TLS1_2_VERSION);
```

2022-09-08 10:38 UTC, piodul commented on scylla-rust-wrapper/src/ssl.rs
> +    SSL_CTX_set_verify(ssl.ssl_context, flags, None);
I don't think this is correct. The flags should be of type `CassSslVerifyFlags`, which is a custom enum defined by the driver, which I'm not sure if are a valid argument to `SSL_CTX_set_verify`. The original implementation seems to do something different - it stores the flags in a field which is later used in a custom verification logic.

2022-09-08 12:08 UTC, Gor027 commented on scylla-rust-wrapper/src/ssl.rs
> +
I guess `SSL_VERIFY_NONE` is the default mode, but I agree, that it is better to set it manually. I am not sure though, whether should we limit the maximum protocol version, as it works fine currently, perhaps with the latest protocol version available in `openssl-sys`.

2022-09-08 12:08 UTC, Gor027 commented on scylla-rust-wrapper/src/ssl.rs
> +    SSL_CTX_set_verify(ssl.ssl_context, flags, None);
The `CassSslVerifyFlags` partially matches with the expected argument for the `SSL_CTX_set_verify`. The C++ driver overrides the OpenSSL handshake implementation to verify the client's hostname and IP address, however, OpenSSL 1.0.2 and newer are able to verify hostname and IP addresses themselves. So, the flags `CASS_SSL_VERIFY_PEER_IDENTITY` and `CASS_SSL_VERIFY_PEER_IDENTITY_DNS` can be either removed or considered to be `CASS_SSL_VERIFY_PEER_CERT`. Although, I have tested setting those 2 additional flags while establishing a connection with a Scylla and Cassandra cluster, and it seemed to work.

2022-09-09 12:35 UTC, piodul commented on scylla-rust-wrapper/src/ssl.rs
> +
OK, I agree about the TLS version. The original comment is probably quite old.

2022-09-09 12:44 UTC, piodul commented on scylla-rust-wrapper/src/ssl.rs
> +    SSL_CTX_set_verify(ssl.ssl_context, flags, None);
Here is how CassSslVerifyFlags is defined:

```c
typedef enum CassSslVerifyFlags_ {
  CASS_SSL_VERIFY_NONE              = 0x00,
  CASS_SSL_VERIFY_PEER_CERT         = 0x01,
  CASS_SSL_VERIFY_PEER_IDENTITY     = 0x02,
  CASS_SSL_VERIFY_PEER_IDENTITY_DNS = 0x04
} CassSslVerifyFlags;
```

And here is how the flags for the `mode` argument of `SSL_CTX_set_verify` are defined:

```c
# define SSL_VERIFY_NONE                 0x00
# define SSL_VERIFY_PEER                 0x01
# define SSL_VERIFY_FAIL_IF_NO_PEER_CERT 0x02
# define SSL_VERIFY_CLIENT_ONCE          0x04
# define SSL_VERIFY_POST_HANDSHAKE       0x08
```

According to the man page here: https://linux.die.net/man/3/ssl_ctx_set_verify, `SSL_VERIFY_CLIENT_ONCE` and `SSL_VERIFY_POST_HANDSHAKE` are ignored in client mode (the driver is a client). `CASS_SSL_VERIFY_PEER_IDENTITY` and `CASS_SSL_VERIFY_PEER_IDENTITY_DNS` "seem to work" because they map to the values I mentioned in the previous sentence.

Ignoring the flags is not the proper behavior. The driver flags and the SSL flags do _not_ mean the same.

2022-09-09 13:57 UTC, Gor027 commented on scylla-rust-wrapper/src/ssl.rs
> +    SSL_CTX_set_verify(ssl.ssl_context, flags, None);
I guess `SSL_VERIFY_PEER` also verifies the peer's hostname and IP address. I think we barely can simulate the behavior of C++ driver in this case, because the handshake should occur while trying to establish a session between the client and the database, and this is being done on the Rust driver side.

2022-09-09 14:18 UTC, piodul commented on scylla-rust-wrapper/src/ssl.rs
> +    SSL_CTX_set_verify(ssl.ssl_context, flags, None);
OK. In that case, let's print a warning to stderr in case one of the non-supported flags is provided and leave a TODO comment in the code. Furthermore, please explicitly map `CASS_XYZ` values to `SSL_XYZ` values in the code - instead of passing `CassSslVerifyFlags` value to the SSL function.

2022-09-12 07:48 UTC, piodul commented on scylla-rust-wrapper/src/ssl.rs
> +        CASS_SSL_VERIFY_PEER_CERT => {
The `CASS_SSL_VERIFY_` constants are flags, they are not mutually exclusive variants of an enum. The user can specify more than one of them by OR-ing them together.

Notice that their values are powers of two:

```c
typedef enum CassSslVerifyFlags_ {
  CASS_SSL_VERIFY_NONE              = 0x00,
  CASS_SSL_VERIFY_PEER_CERT         = 0x01,
  CASS_SSL_VERIFY_PEER_IDENTITY     = 0x02,
  CASS_SSL_VERIFY_PEER_IDENTITY_DNS = 0x04
} CassSslVerifyFlags;
```

2022-09-12 09:11 UTC, Gor027 commented on scylla-rust-wrapper/src/ssl.rs
> +        CASS_SSL_VERIFY_PEER_CERT => {
Currently, there is no support for flags other than `CASS_SSL_VERIFY_NONE` and `CASS_SSL_VERIFY_PEER_CERT`, so in my opinion OR-ing with `CASS_SSL_VERIFY_PEER_IDENTITY` or `CASS_SSL_VERIFY_PEER_IDENTITY_DNS` should not be accepted.

2022-09-14 07:43 UTC, piodul reviewed
A few small comments remaining, otherwise LGTM.

2022-09-14 07:43 UTC, piodul commented on scylla-rust-wrapper/src/ssl.rs
> +            if (flags >> 1) & 1 == 1 {
Why use number literals when you can use constants?

```rust
if flags & CASS_SSL_VERIFY_PEER_IDENTITY_DNS != 0 {
    // ...
}
```

2022-09-14 07:43 UTC, piodul commented on scylla-rust-wrapper/src/ssl.rs
> +        CASS_SSL_VERIFY_PEER_CERT => {
Why not? If the user provides `CASS_SSL_VERIFY_PEER_CERT`, then we should enable the functionality provided by this flag. If they additionally provide `CASS_SSL_VERIFY_PEER_IDENTITY`, we should print a warning and ignore it, but I don't see why this should disable the first flag.

I agree that it would be the best to return an error when an unsupported flag is provided, but the function doesn't really allow us to do that.

2022-09-20 13:25 UTC, Gor027 commented
After [logging support](https://github.com/scylladb/cpp-rust-driver/pull/78) is merged into the master, the error checking/reporting functionality can be added to the SSL-related functions.

2022-09-20 23:18 UTC, merged