Add cluster schema metadata and UDT iterator
scylladb/cpp-rs-driver pull request #72
Opened 2022-08-17 14:48 UTC by Gor027

## Pre-review checklist

- [x] I have split my patch into logically separate commits.
- [x] All commit messages clearly explain what they change and why.
- [x] PR description sums up the changes and reasons why they should be introduced.
- [x] I have enabled appropriate tests in `.github/workflows/build.yaml` in `gtest_filter`.

This PR adds a possibility to fetch cluster schema metadata and adds an implementation of `UDT` iterator and functions to get `UDT` field names and values.
The `cass_session_get_schema_meta` explicitly refreshes cluster metadata before returning cluster metadata as the driver itself does not do it automatically and the integration tests also don't do it manually.

2022-09-05 09:38 UTC, piodul requested changes

2022-09-05 09:38 UTC, piodul commented on scylla-rust-wrapper/src/cass_types.rs
> +        udt_fields: &Vec<(String, CqlType)>,
Nit: unless you have a good reason to do so, always prefer `&[T]` over `&Vec<T>` in arguments. The former is able to capture a wider range of values, e.g. references to arrays, slices and references to vectors, while the last one is only able to accept a reference to vector.

2022-09-05 09:38 UTC, piodul commented on scylla-rust-wrapper/src/cass_types.rs
> +        keyspace_name: &String,
Similarly, here. `&str` is better than `&String`. You can convert `&String` to `&str`, but not the other way around.

2022-09-05 09:38 UTC, piodul commented on scylla-rust-wrapper/src/cass_types.rs
> +    udt_fields: &Vec<(String, CqlType)>,
Nit: `&[(String, CqlType)]`

2022-09-05 09:38 UTC, piodul commented on scylla-rust-wrapper/src/session.rs
> +    ptr_to_ref(refresh_future).with_waited_result(|_| ());
`cass_session_get_schema_meta` shouldn't block. Long-running async operations should be returned in futures. The original implementation doesn't seem to block, either.

Please investigate why refreshing metadata in original implementation's `cass_session_get_schema_meta` isn't necessary. I suspect that the cpp driver refreshes metadata (either partially or fully) after receiving a Schema_change response to a query and then performs the refresh. If so, then it should be implemented in the rust driver, too - please create an issue there and work on it.

2022-09-07 07:50 UTC, Gor027 commented on scylla-rust-wrapper/src/session.rs
> +    ptr_to_ref(refresh_future).with_waited_result(|_| ());
The C++ driver partially updates schema metadata on each schema change response. Currently, the Rust driver does not update the metadata on schema change responses, so I added support in [this PR](https://github.com/scylladb/scylla-rust-driver/pull/545) to fully refresh metadata if there is a schema change.

2022-09-12 08:38 UTC, piodul requested changes

2022-09-12 08:38 UTC, piodul commented on scylla-rust-wrapper/src/cass_types.rs
> +                            udt_fields,
Why are you passing `udt_fields` here? Shouldn't the `udt_fields` be only used to create the main `UDTDataType`? I don't see why they are needed to create the field types.

2022-09-12 08:38 UTC, piodul commented on scylla-rust-wrapper/src/cass_types.rs
> +            udt_fields,
This is wrong. You can have nested UDTs (a UDT can have a field which is also a UDT but of different type). Currently, in `get_column_type_from_cql_type`, you are always passing the same `udt_fields` around, so if you have a nested UDT then it will have wrong fields. Moreover, you will probably cause infinite recursion (`UDTDataType::create_with_params` calls `get_column_type_from_cql_type` and vice versa).

2022-09-12 08:38 UTC, piodul commented on .github/workflows/build.yml
> +:*19.Integration_Cassandra_*"
Typo in the "Add user defined type iterator" commit: `Enableed` -> `Enabled`

2022-09-12 08:38 UTC, piodul commented on scylla-rust-wrapper/src/session.rs
> +    pub user_defined_type_data_type: HashMap<String, CassDataType>,
Why do we need two hashmaps? Isn't information about fields kept in `user_defined_type_data_type`?

2022-09-12 08:38 UTC, piodul commented on scylla-rust-wrapper/src/session.rs
> +            keyspace
Please change `for_each` into regular `for` loops. The usage of `for_each` introduces more indentation than necessary (2 tabs instead of 1)

2022-09-20 16:11 UTC, piodul commented on scylla-rust-wrapper/src/cass_types.rs
> +            frozen: _frozen,
Nit: if you are matching on a variant with named fields, you can skip them with dots:

```rust
match cql_type {
    CqlType::Collection { type_, .. } => {
        // ...
    }
}

2022-09-20 16:11 UTC, piodul commented on scylla-rust-wrapper/src/session.rs
> +    ptr_to_ref(refresh_future).with_waited_result(|_| ());
Is this still necessary? I think that your PR to the rust driver was merged. The refresh here probably can be removed.

2022-09-20 16:11 UTC, piodul commented on scylla-rust-wrapper/src/session.rs
> +    return match keyspace_meta
`return` at the end of the function - not necessary.

2022-09-20 16:11 UTC, piodul commented on tests/src/integration/tests/test_cassandra_types.cpp
> +  this->msleep(1000);
What is this sleep for? We shouldn't depend on timing in tests.

2022-09-20 16:11 UTC, piodul commented on scylla-rust-wrapper/src/query_result.rs
There is a lot of repeated code in the `cass_iterator_next` function. It looks like it could use some refactoring (in a different PR, though).

2022-09-20 16:11 UTC, piodul commented on tests/src/integration/tests/test_cassandra_types.cpp
> +    cass_iterator_free(collection_iterator);
What is the reason for this change? Is it just to test the UDT iterator by reusing an old test? This removes some previous assertions, I'd rather not have them removed without a good reason.

If this is only to test the UDT iterator, then aren't there existing tests for it?

2022-09-20 16:11 UTC, piodul commented on scylla-rust-wrapper/src/session.rs
> +                });
Tip: you can collect into a hashmap from an iterator of pairs:

```rust
let columns_metadata: HashMap<_, _> = table_metadata.columns
    .iter()
    .map(|(column_name, column_metadata)| {
        // ...
        (column_name.clone(), cass_column_meta)
    })
    .collect();
```

2022-09-21 09:37 UTC, Gor027 commented on tests/src/integration/tests/test_cassandra_types.cpp
> +    cass_iterator_free(collection_iterator);
Unfortunately, this is the only test for UDT iterator, earlier we also modified tests [here](https://github.com/scylladb/cpp-rust-driver/pull/69) for other collection types(map, set, list, tuple) as those tests did not use API functions to check the size or the elements of the collections, instead, the `CassValue` was cast to a C++ object.

2022-09-22 09:48 UTC, piodul reviewed
I can't see any existing tests for the iterators added in this PR. Please make sure that all newly added functionality is covered either by the existing, or by new tests.

2022-09-22 09:48 UTC, piodul commented on scylla-rust-wrapper/src/query_result.rs
> +    if let CassIterator::CassKeyspaceMetaIterator(keyspace_meta_iterator) = iter {
It looks like `CassKeyspaceMetaIterator` is used for two purposes: to iterate over tables and user types. I think those should be two separate variants so that it's harder to misuse the iterator.

2022-09-26 13:37 UTC, piodul commented on tests/src/integration/tests/test_schema_metadata.cpp
> +CASSANDRA_INTEGRATION_TEST_F(SchemaMetadataTest, MetadataIterator) {
It would be nice if the test also checked that the iterators do not return more items than expected.

2022-09-26 13:37 UTC, piodul commented on tests/src/integration/tests/test_schema_metadata.cpp
> +//    schema_meta_ = session_.schema();
Why doesn't it break the existing test cases in the file? It looks like other tests here require `schema_meta_` to be initialized after they start, they don't use the `schema_meta()` method.

2022-09-26 13:37 UTC, piodul commented on tests/src/integration/tests/test_schema_metadata.cpp
> +  session_.execute(format_string("CREATE TYPE IF NOT EXISTS %s.%s (street text, city text)", ks_name.c_str(), user_type.c_str()));
How about using the keyspace/table/UDT already defined in `populateSchema()`? You won't have to introduce the `schema_metadata()` method.

2022-09-26 15:12 UTC, Gor027 commented on tests/src/integration/tests/test_schema_metadata.cpp
> +//    schema_meta_ = session_.schema();
The existing tests are disabled for the C++ driver, and the implementation of the tests is not based on the driver's API functions, so I thought it is better to write new tests with separate keyspace/table, in case the existing tests may be fixed in the future.

2022-09-26 15:16 UTC, Gor027 commented on tests/src/integration/tests/test_schema_metadata.cpp
> +  session_.execute(format_string("CREATE TYPE IF NOT EXISTS %s.%s (street text, city text)", ks_name.c_str(), user_type.c_str()));
The `schema_meta()` method is introduced to get a raw pointer `const CassSchemaMeta*` and pass it as an argument to functions that return fields of schema metadata.

2022-09-26 15:22 UTC, piodul commented on tests/src/integration/tests/test_schema_metadata.cpp
> +//    schema_meta_ = session_.schema();
I don't understand. The other tests in the `test_schema_metadata.cpp` file do seem to use the driver API - mostly related to materialized views. Why would the other tests need "fixing"? I know that we don't support materialized views yet (you have sent another PR to fix it), but I don't see why they wouldn't work after the appropriate functions are implemented.

2022-09-26 15:24 UTC, piodul commented on tests/src/integration/tests/test_schema_metadata.cpp
> +  session_.execute(format_string("CREATE TYPE IF NOT EXISTS %s.%s (street text, city text)", ks_name.c_str(), user_type.c_str()));
The `(SchemaMetadataTest, DropView)` test drops a materialized view and then calls `session_.schema()` to verify that the view disappeared from the metadata. Can we do the same here?

2022-09-26 15:44 UTC, Gor027 commented
The build failed because of `cargo clippy` warnings, perhaps because of some updates in cargo clippy. [This](https://github.com/scylladb/cpp-rust-driver/pull/82) PR should fix the issue.

2022-09-27 09:26 UTC, Gor027 commented on tests/src/integration/tests/test_schema_metadata.cpp
> +//    schema_meta_ = session_.schema();
The problem was that the `populateSchema()` creates UDF, aggregate and index. Support for UDF should be manually enabled and `scylla-ccm` does not provide a way to do it. So, for now, I just commented out the creation of the user-defined function, aggregate and index and used the existing keyspace name, table name and user defined type in newly added tests for metadata.

2022-09-27 11:28 UTC, avelanarius commented on scylla-rust-wrapper/src/user_type.rs
> +                data_type: Arc::new(CassDataType::UDT(udt_data_type.clone())),
This change isn't described in the commit message.

2022-09-27 11:41 UTC, Gor027 commented on scylla-rust-wrapper/src/user_type.rs
> +                data_type: Arc::new(CassDataType::UDT(udt_data_type.clone())),
This was not an intentional change, thanks for noticing it.

2022-09-27 12:04 UTC, avelanarius commented on tests/src/integration/tests/test_schema_metadata.cpp
> + * Support for UDF should be manually enabled and currently, ccm does not provide any way to do it.
I don't think that's true - you can configure ccm to start Scylla/Cassandra with UDFs enabled. With Cassandra you can do it with `ccm updateconf enable_user_defined_functions:true` and with Scylla I belive you can do it with `ccm updateconf experimental_features:udf`.

2022-09-27 14:01 UTC, Gor027 commented on scylla-rust-wrapper/src/user_type.rs
> +                data_type: Arc::new(CassDataType::UDT(udt_data_type.clone())),
Actually, this was a necessary change, however, it was in a wrong commit. The function should create and return a new `CassUserType` object which must be freed separately without freeing/modifying the passed `data_type` argument of type `CassDataType`. So, instead of just passing `data_type`, we should create a new `CassDataTypeArc` object with cloning the value of `data_type`.

2022-10-07 11:52 UTC, Lorak-mmk commented on scylla-rust-wrapper/src/user_type.rs
> +                data_type: Arc::new(CassDataType::UDT(udt_data_type.clone())),
I don't follow your reasoning, could you explain a bit more? I think the whole point of reference counting here was to achieve what you said.
Also, the original driver doesn't perform a copy - it seems to only increase refcount, as were we before this change.

2022-10-07 17:37 UTC, Lorak-mmk commented on tests/src/integration/tests/test_schema_metadata.cpp
> +//        format_string("CREATE INDEX schema_meta_index ON %s (value)", table_name_.c_str()));
Why is this commented out? If there is a reason, it needs a comment in the code.

2022-10-09 22:38 UTC, Gor027 commented on tests/src/integration/tests/test_schema_metadata.cpp
> +//        format_string("CREATE INDEX schema_meta_index ON %s (value)", table_name_.c_str()));
It is commented out as the created index is not being checked in these tests.

2022-10-11 18:41 UTC, Gor027 commented on scylla-rust-wrapper/src/user_type.rs
> +                data_type: Arc::new(CassDataType::UDT(udt_data_type.clone())),
I guess the C++ driver creates another `SharedRefPtr` with the `CassDataType` pointer, too, instead of just incrementing the ref count.

2022-10-14 09:09 UTC, Lorak-mmk commented on tests/src/integration/tests/test_schema_metadata.cpp
> +//        format_string("CREATE INDEX schema_meta_index ON %s (value)", table_name_.c_str()));
Please comment it in the code

2022-10-14 09:10 UTC, Lorak-mmk commented on scylla-rust-wrapper/src/user_type.rs
> +                data_type: Arc::new(CassDataType::UDT(udt_data_type.clone())),
Can we do the same?

2022-10-19 11:04 UTC, Gor027 commented on scylla-rust-wrapper/src/user_type.rs
> +                data_type: Arc::new(CassDataType::UDT(udt_data_type.clone())),
I think the current implementation does that. It clones the `udt_data_type` and creates a new Arc'ed `CassDataType` object.

2022-11-10 15:12 UTC, Lorak-mmk approved these changes

2022-11-10 15:13 UTC, merged