Materialized view
scylladb/cpp-rs-driver pull request #76
Opened 2022-09-09 13:37 UTC by Gor027

## Pre-review checklist

- [x] I have split my patch into logically separate commits.
- [x] All commit messages clearly explain what they change and why.
- [x] PR description sums up the changes and reasons why they should be introduced.
- [ ] I have enabled appropriate tests in `.github/workflows/build.yaml` in `gtest_filter`.

This PR is dependent upon #72 

Adds support to fetch materialized views from cluster metadata and implementation for functions to return fields of a certain view in the metadata. Additionally, it adds support to iterate over materialized views.

2022-10-06 13:46 UTC, Lorak-mmk commented
Please rebase on current version of #72

2022-11-14 16:01 UTC, Lorak-mmk commented
Please rebase on current master - it's a bit difficult to review with those unrelated changes from #72

2022-11-24 15:50 UTC, Lorak-mmk requested changes
I don't like that all the metadata methods are in session.rs - they should have their own file, as they are not methods on the CassSesson object.

2022-11-24 15:50 UTC, Lorak-mmk commented on scylla-rust-wrapper/src/user_type.rs
> +                data_type: Arc::new(CassDataType::UDT(udt_data_type.clone())),
I think in UDT PR this change was reverted after we debugged the problem?

2022-11-24 15:50 UTC, Lorak-mmk commented on scylla-rust-wrapper/src/user_type.rs
>          }
This commit does not do what the message says.

2022-11-24 15:50 UTC, Lorak-mmk commented on scylla-rust-wrapper/src/session.rs
> +    pub base_table: Arc<RefCell<CassTableMeta>>,
CassTableMeta and CassMatarializedViewMeta have Arc's of each other  - isn't there going to be a memory leak? Should one of those Arcs be a Weak?

You probably want to use https://doc.rust-lang.org/std/sync/struct.Arc.html#method.new_cyclic to initialize those structs (after breaking ownership cycle using Weak) - that way the RefCell may become redundant.

2022-11-24 15:50 UTC, Lorak-mmk commented on scylla-rust-wrapper/src/session.rs
> +        Some(view_meta) => Arc::as_ptr(view_meta) as *const CassMaterializedViewMeta,
Why is this pointer cast necessary? What's the type returned by `Arc::as_ptr` here?

2022-11-24 15:50 UTC, Lorak-mmk commented on scylla-rust-wrapper/src/session.rs
> +            Some(view_meta) => Arc::as_ptr(view_meta) as *const CassMaterializedViewMeta,
Again, why is this cast needed?

2022-12-15 12:07 UTC, Gor027 commented on scylla-rust-wrapper/src/user_type.rs
> +                data_type: Arc::new(CassDataType::UDT(udt_data_type.clone())),
Yes, this is an unnecessary change, the commit should be dropped.

2022-12-15 12:10 UTC, Gor027 commented on scylla-rust-wrapper/src/user_type.rs
>          }
These changes survived after a rebase as there were memory corruption issues with this part of the code. As we have debugged and solved the problem, the changes will be reverted.

2022-12-15 12:19 UTC, Gor027 commented on scylla-rust-wrapper/src/session.rs
> +        Some(view_meta) => Arc::as_ptr(view_meta) as *const CassMaterializedViewMeta,
The type returned by `Arc::as_ptr` should be `*const CassMaterializedVIewMeta`, I added the cast here to explicitly mark in the code what is returned from the function. I guess anyway the compiler does some optimization and removes the cast here.

2022-12-15 12:19 UTC, Gor027 commented on scylla-rust-wrapper/src/session.rs
> +            Some(view_meta) => Arc::as_ptr(view_meta) as *const CassMaterializedViewMeta,
It is not necessary and can be safely removed.

2022-12-17 12:23 UTC, Gor027 commented on scylla-rust-wrapper/src/session.rs
> +    pub base_table: Arc<RefCell<CassTableMeta>>,
Reference to the base table of a materialized view should be Weak, you are right. I will add some tests to ensure we avoid memory leaks.

2022-12-19 13:21 UTC, Lorak-mmk commented on scylla-rust-wrapper/src/session.rs
> +        Some(view_meta) => Arc::as_ptr(view_meta) as *const CassMaterializedViewMeta,
I think the cast makes it less readable, can you remove it?

2022-12-19 15:26 UTC, Lorak-mmk requested changes
I don't quite like how are the structs / functions places between `session.rs` and `metadata.rs`. Before this PR we had no `metadata.rs` file, so everything was put into `session.rs.` Now that we have it, we can fix this situation.

I'd propose the following:
- Leave `query_results.rs` as it is - meaning that functions accepting or returning `CassIterator` go there.
- Move metadata structs to `metadata.rs` - `CassKeyspaceMeta_`, `CassKeyspaceMeta`, `CassTableMeta_`, `CassTableMeta`, `CassMaterializedViewMeta_`, `CassMaterializedViewMeta`, `CassColumnMeta`, `CassSchemaMeta_`, `CassSchemaMeta`.
- Move metadata functions that don't touch session into `metadata.rs` - everything from `cass_schema_meta_free` downward.
- `create_table_metadata` should probably also go into `metadata.rs`, but I'm not 100% sure about it.

2022-12-19 15:26 UTC, Lorak-mmk commented on scylla-rust-wrapper/src/session.rs
> +                cass_view_meta.base_table = Arc::downgrade(&cass_table_meta);
Why not init to `Arc::downgrade(&cass_table_meta);` in the first place? Then you could get rid of `mut`.

2022-12-19 15:26 UTC, Lorak-mmk commented on scylla-rust-wrapper/src/session.rs
> +    pub views: std::sync::RwLock<Option<HashMap<String, Arc<CassMaterializedViewMeta>>>>,
Why `Option`? I don't see any place where `None` is treated differently than `Some` with hashmap not containing relevant key.

2022-12-19 15:26 UTC, Lorak-mmk commented on scylla-rust-wrapper/src/session.rs
> +    pub views: std::sync::RwLock<Option<HashMap<String, Arc<CassMaterializedViewMeta>>>>,
Is this RwLock only used as `write()` to initialize the structure? If so, the I think this is the wrong tool here. RefCell could be used without other changes. But this also should not be necessary - can we initialize the structure using https://doc.rust-lang.org/std/sync/struct.Arc.html#method.new_cyclic ? That would allow getting rid of a lot of `.read().unwrap()` from other places in this PR, making the code more readable. While applied along with previous code, the type of this field would be just `HashMap<String, Arc<CassMaterializedViewMeta>>`.

2022-12-19 15:26 UTC, Lorak-mmk commented on scylla-rust-wrapper/src/session.rs
> +    pub views: HashMap<String, Arc<CassMaterializedViewMeta>>,
This is not that important, but why metadata-related structures use `Arc` and not just `Rc`? cppdriver only requires `CassSession` and `CassFuture` to be thread safe. Do we do something similar (stronger thread-safety than cppdriver requires) in other places?
Here, using `Arc` instead of `Rc` allows to call `cass_schema_meta_free` on a different thread than `cass_session_get_schema_meta` was called from (those are the only places where the counters are modified) - that doesn't seem like a big benefit.

2022-12-20 11:52 UTC, Gor027 commented on scylla-rust-wrapper/src/session.rs
> +                cass_view_meta.base_table = Arc::downgrade(&cass_table_meta);
The initialization of `cass_table_meta` with `Arc::new_cyclic` allowed to avoid `Arc::downgrade` and to make `cass_view_meta` immutable.

2022-12-20 11:55 UTC, Gor027 commented on scylla-rust-wrapper/src/session.rs
> +    pub views: std::sync::RwLock<Option<HashMap<String, Arc<CassMaterializedViewMeta>>>>,
The purpose of `Option` was to differentiate uninitialized `views` from empty `views` for better error handling, however, it seemed to be useless, so I removed `Option`.

2022-12-20 11:58 UTC, Gor027 commented on scylla-rust-wrapper/src/session.rs
> +    pub views: std::sync::RwLock<Option<HashMap<String, Arc<CassMaterializedViewMeta>>>>,
Initialization with `Arc::new_cyclic` allowed to get rid of `RwLock` and keep the `views` type as simple as `HashMap<String, Arc<CassMaterializedViewMeta>>`.

2022-12-20 12:07 UTC, Gor027 commented
> I don't quite like how are the structs / functions places between `session.rs` and `metadata.rs`. Before this PR we had no `metadata.rs` file, so everything was put into `session.rs.` Now that we have it, we can fix this situation.
> 
> I'd propose the following:
> 
> * Leave `query_results.rs` as it is - meaning that functions accepting or returning `CassIterator` go there.
> * Move metadata structs to `metadata.rs` - `CassKeyspaceMeta_`, `CassKeyspaceMeta`, `CassTableMeta_`, `CassTableMeta`, `CassMaterializedViewMeta_`, `CassMaterializedViewMeta`, `CassColumnMeta`, `CassSchemaMeta_`, `CassSchemaMeta`.
> * Move metadata functions that don't touch session into `metadata.rs` - everything from `cass_schema_meta_free` downward.
> * `create_table_metadata` should probably also go into `metadata.rs`, but I'm not 100% sure about it.
> 
> What do you think?

As you suggested above, I moved all metadata-related structures and functions to `metadata.rs`. Importing the `CassColumnType` enum is also moved to `metadata.rs`, so I think it is better to have `create_table_metadata` also in that file rather than in `session.rs`.

2022-12-21 13:22 UTC, Lorak-mmk commented on scylla-rust-wrapper/src/metadata.rs
> +}
Nit / subjective: Move them above `CassKeyspaceMeta_`

2022-12-21 14:51 UTC, Lorak-mmk requested changes
I like the overall changes now (apart from few comments I left).
Few issues I have with the commits:
- "Add materialized view metadata ": message is incorrect, there is not RefCell anymore
- "Add impl for functions returning view metadata fields " - this commit should not include moving existing functions between files, that should be a seperate one.

2022-12-21 14:51 UTC, Lorak-mmk commented on scylla-rust-wrapper/src/metadata.rs
> +        Some(udt) => Arc::into_raw(udt.clone()) as *const CassDataType,
Why is there a clone? I see that cpp-driver doesn't clone this, so we'd be incompatible (in this version user would have to explicitly free this udt, in contrary to cpp-driver).

2022-12-21 14:51 UTC, Lorak-mmk commented on scylla-rust-wrapper/src/metadata.rs
> +        Some(meta) => meta,
`meta` is a reference, so maybe add an explicit cast here?

2022-12-21 14:51 UTC, Lorak-mmk commented on scylla-rust-wrapper/src/metadata.rs
> +        Some(view_meta) => Arc::as_ptr(view_meta) as *const CassMaterializedViewMeta,
Remove the cast (as_ptr already returns correct type)

2022-12-21 14:51 UTC, Lorak-mmk commented on scylla-rust-wrapper/src/metadata.rs
> +        Some(view_meta) => Arc::as_ptr(view_meta.1) as *const CassMaterializedViewMeta,
Remove the cast (as_ptr already returns correct type)

2022-12-21 14:51 UTC, Lorak-mmk commented on scylla-rust-wrapper/src/metadata.rs
> +    view_meta.base_table.as_ptr() as *const CassTableMeta
Is the type returned by `as_ptr()` different than `*const CassTableMeta`? If not, remove the cast

2022-12-22 14:10 UTC, Gor027 commented on scylla-rust-wrapper/src/metadata.rs
> +}
Done.

2022-12-22 14:13 UTC, Gor027 commented on scylla-rust-wrapper/src/metadata.rs
> +        Some(udt) => Arc::into_raw(udt.clone()) as *const CassDataType,
The `udt` object is of type `&Arc<CassDataType>` and `Arc::into_raw` expects argument by value rather than by reference, so I think a clone is necessary here.

2022-12-22 14:13 UTC, Gor027 commented on scylla-rust-wrapper/src/metadata.rs
> +        Some(meta) => meta,
Done.

2022-12-22 14:13 UTC, Gor027 commented on scylla-rust-wrapper/src/metadata.rs
> +        Some(view_meta) => Arc::as_ptr(view_meta) as *const CassMaterializedViewMeta,
Done.

2022-12-22 14:13 UTC, Gor027 commented on scylla-rust-wrapper/src/metadata.rs
> +        Some(view_meta) => Arc::as_ptr(view_meta.1) as *const CassMaterializedViewMeta,
Done.

2022-12-22 14:14 UTC, Gor027 commented on scylla-rust-wrapper/src/metadata.rs
> +    view_meta.base_table.as_ptr() as *const CassTableMeta
The returned type is `*const CassTableMeta`, so the cast is removed.

2022-12-22 15:13 UTC, Gor027 commented on scylla-rust-wrapper/src/metadata.rs
> +        Some(udt) => Arc::into_raw(udt.clone()) as *const CassDataType,
Ok, there is the `Arc::as_ptr` function which helps to avoid the clone. Will fix it.

2022-12-22 20:31 UTC, Gor027 commented
Update:

Rebased on #95 and enabled materialized view metadata tests on GitHub Actions (`SchemaMetadataTest.*View*`).
This PR should be merged only after #95 is merged.

2022-12-23 13:33 UTC, Lorak-mmk commented on scylla-rust-wrapper/src/metadata.rs
> +        Some(view_meta) => Arc::as_ptr(view_meta.1) as *const CassMaterializedViewMeta,
No it's not

2022-12-23 17:34 UTC, Gor027 commented on scylla-rust-wrapper/src/metadata.rs
> +        Some(view_meta) => Arc::as_ptr(view_meta.1) as *const CassMaterializedViewMeta,
The cast perhaps appeared after the rebase on #95. Hope it is fixed now.

2023-01-02 14:35 UTC, Lorak-mmk approved these changes

2023-01-02 14:37 UTC, Lorak-mmk commented
Actually, one more changed is needed - adjustment of the limitations table in README to take into account changes made by this PR

2023-01-03 14:00 UTC, Gor027 commented
@Lorak-mmk Guess it is good now to be merged.

2023-01-03 14:03 UTC, Gor027 commented
Also, as you mentioned earlier, a nice optimization maybe not copy the metadata information, but have a pointer to a `ClusterData` object and on each metadata-related function call calculate and return the necessary information. I will open an issue to be discussed in the future.

2023-01-04 10:13 UTC, merged