Add tracing subscriber to enable logging
scylladb/cpp-rs-driver pull request #78
Opened 2022-09-16 13:31 UTC by Gor027

Motivation:

Added `tracing-subscriber` crate to have one common way of logging with the Rust driver, as the Rust driver uses `tracing` crate for logging and cpp-rust driver should allow clients to configure logging by specifying the max log level and providing callback that should be called on each event.

Solution:

As logging should be configured globally, the current implementation creates a custom tracing subscriber with default configuration, which later can be changed by the user. The global and mutable state of the logging configuration is initialized in the `lazy_static!` block, however, it will be evaluated only after the first access in the code. As, the `cass_session_new()` function most probably is the first function that the user will call (almost all tests do that, too), the initialization of logging is chosen to be done in this function.

The C++ driver does not ban the user to call `cass_log_*` functions after a function call that might log, so the implementation keeps the same behavior. But it warns the user after the logging initialization that `cass_log_*` functions should not be called, as the documentation of the C++ driver suggests.

The CassLogMessage has a field `function` that should always be empty, as it cannot be properly set, because event metadata does not include information about it.

Enabled `LoggingTests` tests in github actions.

## Pre-review checklist

- [x] I have split my patch into logically separate commits.
- [x] All commit messages clearly explain what they change and why.
- [x] PR description sums up the changes and reasons why they should be introduced.
- [x] I have enabled appropriate tests in `.github/workflows/build.yaml` in `gtest_filter`.

2022-09-26 14:33 UTC, piodul commented on scylla-rust-wrapper/src/argconv.rs
> +}
There are a couple of issues with this code:

- It takes an array of `N` characters by value as an argument, where `N` can be quite large (1024 in our case). You can change the type of the array either to a reference to an array, or just a slice (the function doesn't have to be generic IMO).
- It creates a 1024 byte buffer pre-populated with zero bytes, copies bytes from `arr` until it encounters `'\0` and then collects the whole 1024 byte buffer into a `String`. Please remember that in Rust, unlike in C, strings are _not_ null terminated, so this always creates a 1024 byte String. I can see that you are later trimming the zero bytes unnecessarily.
- It always allocates a string, however it could just borrow from the `arr` argument if it were passed by reference.

I think the implementation should be similar to:
- Find the first null terminator byte
- Use `ptr_to_cstr_n` to create the string, if there was no null terminator then use `N` as length.

We can consider using `String::from_utf8_lossy` instead of `std::str::from_utf8` so that if the string contains invalid characters, then the resulting string will still be printable.

2022-09-26 14:33 UTC, piodul commented on scylla-rust-wrapper/src/argconv.rs
> +pub fn str_to_arr<const N: usize>(s: &str) -> [c_char; N] {
It's better to take the output argument as `&mut [c_char]` rather than returning a big slice so that you don't have to initialize the whole 1024 bytes every single time.

2022-09-26 14:33 UTC, piodul commented on scylla-rust-wrapper/src/argconv.rs
> +    for (i, c) in s.chars().enumerate() {
`s.chars().enumerate().take(N)`

If you change it like this, then you won't have to put the `i < N` check inside the loop.

2022-09-26 14:33 UTC, piodul commented on scylla-rust-wrapper/src/lib.rs
> +        self.log_message = format!("{}{}: {:?}, ", self.log_message, field, value);
This is not a very efficient way to append strings. It forces you to allocate every time you add a field. Consider using the `+=` operator instead.

2022-09-26 14:33 UTC, piodul commented on scylla-rust-wrapper/src/lib.rs
> +            since_the_epoch.as_secs() * 1000 + since_the_epoch.subsec_nanos() as u64 / 1_000_000;
How about [`Duration::as_millis`](https://doc.rust-lang.org/std/time/struct.Duration.html#method.as_millis)?

2022-09-27 10:12 UTC, Gor027 commented on scylla-rust-wrapper/src/lib.rs
> +            since_the_epoch.as_secs() * 1000 + since_the_epoch.subsec_nanos() as u64 / 1_000_000;
`Duration::as_millis` returns `u128`, however, `CassLogMessage::time_ms` is of type `u64`.

2022-09-27 11:14 UTC, avelanarius commented on scylla-rust-wrapper/src/logging.rs
> +        _ => Level::INFO, // TODO gor: print warning that flag is not supported
Should this `TODO` be done before merging?

2022-09-27 11:14 UTC, avelanarius commented on scylla-rust-wrapper/src/logging.rs
> +        _ => "\0",
```suggestion
        _ => "\0",
```

2022-09-27 11:15 UTC, avelanarius commented on scylla-rust-wrapper/src/logging.rs
> +        _ => "\0",
`CASS_LOG_LAST_ENTRY` is a dummy enum entry, so it shouldn't be mentioned anywhere.

2022-09-27 12:15 UTC, piodul commented on scylla-rust-wrapper/src/lib.rs
> +        self.log_message += format!("{}: {:?}, ", field, value).as_str();
Hmm, it's not exactly what I meant. This still requires you to allocate a string - `format!` performs an allocation. On the other hand you have to convert the `value` to string, so I don't think that it's actually possible to avoid an allocation with `+=`

However, it looks like you can use the `write!` macro to do what I originally meant, see here: https://stackoverflow.com/questions/28333612/how-can-i-append-a-formatted-string-to-an-existing-string

2022-09-27 12:17 UTC, piodul commented on scylla-rust-wrapper/src/argconv.rs
> +    for (i, c) in s.chars().enumerate() {
What about this?

2022-09-27 12:20 UTC, piodul commented on scylla-rust-wrapper/src/argconv.rs
> +            result[i] = c as c_char;
This won't work if you have a non-ascii string. Perhaps it would be good to just take the bytes of the string and copy it to the `result`. In the meantime, please be careful not to accidentally slice a character - UTF-8 can use multiple bytes to encode a single character, and we either want a whole character or none of them. See here for an implementation of a function which returns a slice that has max N bytes: https://github.com/rust-lang/rfcs/issues/2566

2022-09-28 11:23 UTC, piodul commented on scylla-rust-wrapper/src/lib.rs
> +            .with(CustomLayer)
Why are we only allowed to do this once per program? Does the `tracing` crate forbid to change the subscriber later?

2022-09-28 11:25 UTC, piodul commented on scylla-rust-wrapper/src/lib.rs
> +        write!(self.log_message, "{}: {:?}, ", field, value).unwrap();
It's a bit weird because it leaves a comma at the end. How about checking if the string is empty - if it is, then don't add a comma, if it isn't then put a comma before the appended fragment?

`, {}: {:?}`

2022-09-28 11:33 UTC, Gor027 commented on scylla-rust-wrapper/src/lib.rs
> +            .with(CustomLayer)
As the documentation of the C++ driver suggests, the logging properties such as the level or the callback should be set before calling any function that might log. I am not sure if the crate forbids changing the subscriber runtime. But I also do not see how it may be useful for the users, and from which API function the subscriber should be changed.

2022-09-28 11:39 UTC, piodul commented on scylla-rust-wrapper/src/lib.rs
> +            .with(CustomLayer)
OK.

2022-09-28 11:40 UTC, piodul commented on scylla-rust-wrapper/src/session.rs
> +    warn!(message = "Logging initialized, do not call log-related functions 'cass_log_*'!");
I users will find it annoying that a warning is printed when the driver is used as intended. How about printing a warning only when the user actually uses some `cass_log_` function after the log is initialized?

2022-09-28 11:55 UTC, Gor027 commented on scylla-rust-wrapper/src/session.rs
> +    warn!(message = "Logging initialized, do not call log-related functions 'cass_log_*'!");
Ok, will fix it.

2022-10-05 16:12 UTC, Lorak-mmk requested changes

2022-10-05 16:12 UTC, Lorak-mmk commented on scylla-rust-wrapper/src/argconv.rs
> +}
This code doesn't check for null at the beggining of the message - is this intended?
If not, then something like this should work:
```
let end_index = arr[..N].iter().position(|c| c == '\0').unwrap_or(N);
ptr_to_cstr_n(arr.as_ptr(), end_index as size_t)
```

2022-10-05 16:12 UTC, Lorak-mmk commented on scylla-rust-wrapper/src/argconv.rs
> +    let mut max_len = N - 1;
A commend saying this it must be `N-1` instead of `N` to have null-terminated string would be appreciated

2022-10-05 16:12 UTC, Lorak-mmk commented on scylla-rust-wrapper/src/logging.rs
> +unsafe impl Send for Logger {}
I think this warrants a comment.
- Why are those not auto implemented (which members of Logger are not Send/Sync)
- Why is this safe?

2022-10-05 16:12 UTC, Lorak-mmk commented on scylla-rust-wrapper/src/logging.rs
> +    };
Can you implement `TryFrom<CassLogLevel> for Level` and use it?
If it's not possible because of orphan rule, maybe implement `TryInto<Level> for CassLogLevel`?
What do you think @piodul ?

2022-10-05 16:12 UTC, Lorak-mmk commented on scylla-rust-wrapper/src/logging.rs
> +    *LOG.write().unwrap() = None;
Why is this necessary? Wouldn't the next line drop the subscriber anyway?

2022-10-05 16:12 UTC, Lorak-mmk commented on src/logger.cpp
> -
Is the rest of this file used by anything, or can the whole file be removed?

2022-10-05 16:12 UTC, Lorak-mmk commented on scylla-rust-wrapper/src/argconv.rs
> +    let mut max_len = N - 1;
Also, N will usually be 1024 - so this most likely won't be a performance problem, but maybe we could do something like `let mut max_len = std::min(N - 1, s.as_bytes().len());` just to be safe?

2022-10-09 21:52 UTC, Gor027 commented on scylla-rust-wrapper/src/logging.rs
> +unsafe impl Send for Logger {}
A `Logger` object contains `data: *mut libc::c_void` for which neither `Send` nor `Sync` is implemented. It should be safe to manually implement `Send` and `Sync` for `Logger` as `data` can be mutated only in `CassLogCallback` which is defined by the user.

2022-10-09 22:10 UTC, Gor027 commented on scylla-rust-wrapper/src/logging.rs
> +    *LOG.write().unwrap() = None;
Unfortunately, `lazy_static` is not freed that simply and I needed to force a free here. I did some research and the simplest way to do so was using `Option`.

2022-10-09 22:14 UTC, Gor027 commented on src/logger.cpp
> -
`logger.hpp` is used in the integration tests, so perharps, it cannot be removed safely.

2022-10-10 11:53 UTC, Lorak-mmk commented on scylla-rust-wrapper/src/argconv.rs
> +            result[i] = c as c_char;
This seems done - marking as resolved

2022-10-10 11:53 UTC, Lorak-mmk commented on scylla-rust-wrapper/src/argconv.rs
> +    for (i, c) in s.chars().enumerate() {
Looks done, marking as resolved

2022-10-10 11:54 UTC, Lorak-mmk commented on scylla-rust-wrapper/src/lib.rs
> +        self.log_message = format!("{}{}: {:?}, ", self.log_message, field, value);
Looks done, marking as resolved

2022-10-10 11:54 UTC, Lorak-mmk commented on scylla-rust-wrapper/src/lib.rs
> +        self.log_message += format!("{}: {:?}, ", field, value).as_str();
Looks done, marking as resolved

2022-10-10 11:54 UTC, Lorak-mmk commented on scylla-rust-wrapper/src/lib.rs
> +        write!(self.log_message, "{}: {:?}, ", field, value).unwrap();
Looks done, marking as resolved

2022-10-10 11:55 UTC, Lorak-mmk commented on scylla-rust-wrapper/src/session.rs
> +    warn!(message = "Logging initialized, do not call log-related functions 'cass_log_*'!");
Looks done, marking as resolved

2022-10-10 12:05 UTC, Lorak-mmk commented on scylla-rust-wrapper/src/logging.rs
> +unsafe impl Send for Logger {}
Please put this explanation in the comment in code

2022-10-10 12:06 UTC, Lorak-mmk commented on scylla-rust-wrapper/src/logging.rs
> +    *LOG.write().unwrap() = None;
So what would happen if you simply did
`*LOG.write().unwrap() = Some(set_tracing_subscriber_with_level(level));`
without doing
`*LOG.write().unwrap() = None;`
?
Would the memory be leaked? This seems a bit counterintuitive

2022-10-10 13:00 UTC, Gor027 commented on scylla-rust-wrapper/src/logging.rs
> +    *LOG.write().unwrap() = None;
The `set_tracing_subscriber_with_level` sets the tracing subscriber as default for the duration of the lifetime of the returned `DefaultGuard`. If the `LOG` is not set to `None` then, I guess, the `DefaultGuard` still lives and the new tracing subscriber is not set as default. You can test the behavior with this test case `LoggingTests.Integration_Cassandra_Callback`.

2022-10-14 10:15 UTC, Lorak-mmk requested changes

2022-10-14 10:15 UTC, Lorak-mmk commented on scylla-rust-wrapper/src/logging.rs
> +}
`Level` is `Copy`, so this can most likely be changed to `From<Level>` without any problems

2022-10-14 10:15 UTC, Lorak-mmk commented on scylla-rust-wrapper/src/logging.rs
> +    *LOG.write().unwrap() = None;
Ok, I get it. If you just did `*LOG.write().unwrap() = Some(set_tracing_subscriber_with_level(level));`, then the RHS would be evaluated first (and `set_tracing_subscriber_with_level`) would do nothing, because previous guard still lives, and only then the previous guard would be dropped. This would result in no messages being printed afterwards according to my test. Is that correct?

I don't like this, but I don't see a better solution off the top of my head. Please comment it a bit more because it's hard to understand.

2022-10-18 21:26 UTC, Gor027 commented on scylla-rust-wrapper/src/logging.rs
> +    *LOG.write().unwrap() = None;
> Ok, I get it. If you just did `*LOG.write().unwrap() = Some(set_tracing_subscriber_with_level(level));`, then the RHS would be evaluated first (and `set_tracing_subscriber_with_level` would do nothing, because previous guard still lives), and only then the previous guard would be dropped. This would result in no messages being printed afterwards according to my test. Is that correct?

I think that is the proper explanation. I will leave more descriptions of the solution.

2022-11-14 10:12 UTC, Lorak-mmk commented on scylla-rust-wrapper/src/logging.rs
> +            _ => Level::INFO,
Why the default option is `Level::Info` instead of returning an error?
If there is a reason, then why is this `TryFrom` and not simply `From`? There are currently no paths returning and error

2022-11-22 10:38 UTC, Gor027 commented on scylla-rust-wrapper/src/logging.rs
> +            _ => Level::INFO,
There are unmatched `CassLogLevel` types such as `CASS_LOG_CRITICAL` which I thought is better to match as `CASS_LOG_INFO` or `CASS_LOG_WARN`.

2022-11-23 13:58 UTC, Lorak-mmk requested changes

2022-11-23 13:58 UTC, Lorak-mmk commented on scylla-rust-wrapper/src/cass_log.rs
> +include!(concat!(env!("OUT_DIR"), "/cppdriver_log.rs"));
Why is there a separate file for this instead of putting it in logging.rs?

2022-11-23 13:58 UTC, Lorak-mmk commented on scylla-rust-wrapper/src/logging.rs
> +            _ => Level::INFO,
Such levels should be listed explicitly - CassLogLevel is not a Rust enum, it's an int and can have invalid value, so right now there is no difference between `CASS_LOG_CRITICAL` and arbitrary int value.
I think this should by TryFrom with unknown values returning error - you can then handle the error in `cass_log_set_level` using e.g. `unwrap_or` if we don't want to validate the value.

Also, `CASS_LOG_CRITICAL` should probably map to `Level::ERROR`, not `Level::INFO`

2022-11-23 13:58 UTC, Lorak-mmk commented on scylla-rust-wrapper/src/lib.rs
> +    ));
All of this new code is related to logging - wouldn't it fit better in logging.rs?

2022-11-23 13:58 UTC, Lorak-mmk commented on scylla-rust-wrapper/src/logging.rs
> +    let level = Level::try_from(log_level).ok().unwrap();
Why .ok().unwrap() instead of only .unwrap()?
Also, after changing `From<CassLogLevel> for Level` to `TryFrom<CassLogLevel> for Level` this will need to be changed to `.unwrap_or`

2022-11-23 13:58 UTC, Lorak-mmk commented on scylla-rust-wrapper/src/logging.rs
> +    };
Maybe something like this?
```suggestion
    let logger = Logger {
            cb: Some(callback.unwrap_or(noop_log_callback)),
            data,
        };
```

2022-12-07 14:15 UTC, Gor027 commented on scylla-rust-wrapper/src/cass_log.rs
> +include!(concat!(env!("OUT_DIR"), "/cppdriver_log.rs"));
There was a need to manually disable `non_camel_case_types` warnings to pass cargo clippy checks, so this was a NIT suggestion by @piodul to separate the logic into a new file.

2022-12-07 14:57 UTC, Gor027 commented on scylla-rust-wrapper/src/lib.rs
> +    ));
Yes, for some reason I left it here, but it is possible to move it to `logging.rs`. Will do it, thanks.

2022-12-08 15:33 UTC, Lorak-mmk commented on scylla-rust-wrapper/src/cass_log.rs
> +include!(concat!(env!("OUT_DIR"), "/cppdriver_log.rs"));
That's a good point. I have 2 other ideas on how to solve it - not sure any of them will work, but could you try?
1. Put the include in module and disable warnings for module.
```
#[allow(non_camel_case_types)]
mod cass_log {
    include!(concat!(env!("OUT_DIR"), "/cppdriver_log.rs"));
}
use cass_log::*;
```
2. Use https://docs.rs/bindgen/latest/bindgen/struct.Builder.html#method.module_raw_line to add this `allow` to the module itself - but that will probably affect also the file it is `!include`'d in, so the option 1 seems better.

2022-12-14 17:20 UTC, Lorak-mmk requested changes

2022-12-14 17:20 UTC, Lorak-mmk commented on scylla-rust-wrapper/src/logging.rs
> +    }
Why is logging disabled when set to CRITICAL?

2022-12-14 17:20 UTC, Lorak-mmk commented on scylla-rust-wrapper/src/logging.rs
> +            Level::TRACE => CassLogLevel::CASS_LOG_TRACE,
Can we put that in order (trace, debug, info, warn, error)?

2022-12-14 17:20 UTC, Lorak-mmk commented on scylla-rust-wrapper/src/logging.rs
> +            CassLogLevel::CASS_LOG_CRITICAL => Level::ERROR,
Same here - either put critical on top or reverse the order of other fields.

2022-12-14 17:20 UTC, Lorak-mmk commented on scylla-rust-wrapper/src/logging.rs
> +            .expect("Time went backwards");
This error message can be improved - `Time wen backwards` can mean that the system clock was not monotonic - which can often happen. I'd go with `Current time is before UNIX_EPOCH`.

2022-12-14 17:20 UTC, Lorak-mmk commented on scylla-rust-wrapper/src/logging.rs
> +    };
This comment still stands.

2022-12-15 11:25 UTC, Gor027 commented on scylla-rust-wrapper/src/logging.rs
> +    }
It was a copy-paste issue, thanks for noticing.

2022-12-15 11:32 UTC, Gor027 commented on scylla-rust-wrapper/src/logging.rs
> +    };
I have applied the suggestion in the same commit.

2022-12-15 11:32 UTC, Gor027 commented on scylla-rust-wrapper/src/logging.rs
> +    }
Done.

2022-12-15 11:32 UTC, Gor027 commented on scylla-rust-wrapper/src/logging.rs
> +            Level::TRACE => CassLogLevel::CASS_LOG_TRACE,
Done.

2022-12-15 11:32 UTC, Gor027 commented on scylla-rust-wrapper/src/logging.rs
> +            CassLogLevel::CASS_LOG_CRITICAL => Level::ERROR,
Done.

2022-12-15 11:32 UTC, Gor027 commented on scylla-rust-wrapper/src/logging.rs
> +            .expect("Time went backwards");
Done.

2022-12-15 11:52 UTC, Lorak-mmk approved these changes

2022-12-19 14:28 UTC, merged