Add extensive information about the driver in README
scylladb/cpp-rs-driver pull request #81
Opened 2022-09-21 14:27 UTC by Gor027

## Pre-review checklist

- [x] I have split my patch into logically separate commits.
- [x] All commit messages clearly explain what they change and why.
- [x] PR description sums up the changes and reasons why they should be introduced.
- [ ] I have enabled appropriate tests in `.github/workflows/build.yml` in `gtest_filter`.
- [ ] I have enabled appropriate tests in `.github/workflows/cassandra.yml` in `gtest_filter`.

2022-09-27 11:03 UTC, avelanarius commented on README.md
> +As opposed to C/C++ driver, it works with the Cassandra Query Language v4 (CQL4).
What do you mean by Cassandra Query Language v4? It looks like C/C++ driver works with `CASS_PROTOCOL_VERSION_V4`.

2022-09-27 11:04 UTC, constantfold commented on README.md
> +# Features
This should be moved before "Testing" section.

2022-09-27 11:06 UTC, avelanarius commented
Please also add a section about limitations. Additionally, we should clean up the GitHub Issues that were opened - closing the ones that are now implemented.

2022-09-27 11:25 UTC, Gor027 commented on README.md
> +As opposed to C/C++ driver, it works with the Cassandra Query Language v4 (CQL4).
This was mentioned in the [C++ driver description](https://github.com/scylladb/cpp-driver#compatibility):
#### This driver works exclusively with the Cassandra Query Language v3 (CQL3) and Cassandra's native protocol.

Perhaps, it is outdated information.

2022-09-27 11:28 UTC, Gor027 commented on README.md
> +# Features
Do you mean at the beginning of the `Testing` section, or in the description at the very beginning of the document?

2022-09-27 11:31 UTC, avelanarius commented on README.md
> +# Features
I mean that the entire "Features" section should be swapped with the entire "Testing" section, changing the order.

2022-10-05 10:13 UTC, Lorak-mmk requested changes

2022-10-05 10:13 UTC, Lorak-mmk commented on README.md
> +There are some examples in the [examples](https://github.com/scylladb/cpp-driver/tree/master/examples) directory.
We have those examples in cpp-rust-driver repo, why point to the old repository?

2022-10-05 10:13 UTC, Lorak-mmk commented on README.md
> +cmake -DCASS_BUILD_INTEGRATION_TESTS=ON  .. & make
`&` -> `&&`

2022-10-10 10:15 UTC, Lorak-mmk approved these changes

2022-10-10 13:35 UTC, Lorak-mmk reviewed
Actually, the limitations section mentiond by @avelanarius is important - please write it before merging.

2022-10-10 13:52 UTC, Gor027 commented
Sure, I am working on it. I have updated the issues marking functions that are implemented and functions that are still in progress. I will base the limitations section on those issues unless you have another opinion.

2022-10-11 12:59 UTC, Gor027 commented
V2:

Added a separate section about the limitations of some features.
More information will be added to this section. For now, it covers the main limitations that the current implementation of the driver's features has.

2022-10-13 10:47 UTC, Lorak-mmk commented
I'd like for the limitations section to include a note that the section itself may be incomplete - unless you are sure that the list is fairly complete?

One thing I'm not sure about:
In bindings.rs, the function that checks types is unimplemented: https://github.com/scylladb/cpp-rust-driver/blob/5c009e88c6e3d0021d4318855053b0ef514da42c/scylla-rust-wrapper/src/binding.rs#L53-L56
This I think is used for all binding - and you only noted that we are not checking types for `cass_collection_append_*` - is that correct?

2022-10-13 11:39 UTC, Gor027 commented
> I'd like for the limitations section to include a note that the section itself may be incomplete - unless you are sure that the list is fairly complete?
Sure, I will add a note that the list is incomplete. For now, I have included the main functions which are not implemented or are implemented with some limitations. Functions that are relatively easy to implement (that do not require some implementation in the Rust driver, or maybe even in ScyllaDB) are just noted as `unimplemented`.

> This I think is used for all binding - and you only noted that we are not checking types for `cass_collection_append_*` - is that correct?
What do you mean by `all binding`? The compatibility of types is being checked while appending or setting values in collections, tuples and UDTs. For binding a value to a prepared statement, the type is not being checked and in case of binding with incompatible type, the execution of the prepared statement should not be successful.

2022-10-14 11:37 UTC, Lorak-mmk commented
Are you sure that prepared statements are not checked? I did a quick experiment: https://gist.github.com/Lorak-mmk/dbce7e0484b69000f8523df4ad963531

And for me it prints: 
```
===== Using optimized driver!!! =====
bind 1 id: 0
bind 1 somestring: 0
execute 1: 0
bind 2 id: 0
bind 2 somestring: 16777229
execute 2: 0
DONE!
```
Which would mean that they are checked. After reading abstract_data.hh it also seems that the types should be checked for prepared statement.

2022-10-19 12:31 UTC, Gor027 commented
> Which would mean that they are checked. After reading abstract_data.hh it also seems that the types should be checked for prepared statement.

Yeah, I guess you are right. The `UserTypeValue` and `Statement` classes extend from `AbstractData` class, so setting value by index or name should also check the type compatibility. Will fix the description.

2022-10-20 13:31 UTC, Lorak-mmk commented
There is already a placeholder function for that, it's just not implemented yet - always returns true.
See bindings.rs:53-56

2022-10-20 13:31 UTC, Lorak-mmk approved these changes

2022-11-10 15:18 UTC, merged