Fix binding by name
scylladb/cpp-rs-driver pull request #84
Opened 2022-10-12 19:04 UTC by Gor027

Fixes case sensitive binding by name:
 * binding by name inside double quotes is case sensitive
 * binding by name without quotes should bind the value to multiple columns

Enabled `ByNameTests` tests for both ScyllaDB and Cassandra

## Pre-review checklist

- [x] I have split my patch into logically separate commits.
- [x] All commit messages clearly explain what they change and why.
- [x] PR description sums up the changes and reasons why they should be introduced.
- [x] I have enabled appropriate tests in `.github/workflows/build.yml` in `gtest_filter`.
- [x] I have enabled appropriate tests in `.github/workflows/cassandra.yml` in `gtest_filter`.

2022-10-17 12:07 UTC, Lorak-mmk requested changes

2022-10-17 12:07 UTC, Lorak-mmk commented on scylla-rust-wrapper/src/statement.rs
> +                                && col.name.to_lowercase() == name_str.to_lowercase()
Instead of using `to_lowercase()` which needs to allocate new string, please write a new function that compares strings case-insensitive without allocating

2022-10-17 12:07 UTC, Lorak-mmk commented on scylla-rust-wrapper/src/query_result.rs
> +    }
Why is this logic different than the one in `bind_cql_value_by_name`? The other one looks correct (from the cppdriver compatibility POV), this one doesn't.

2022-10-17 12:07 UTC, Lorak-mmk commented on scylla-rust-wrapper/src/query_result.rs
> +    }
Also, can you prepare some abstraction for this (finding and stripping quotes, comparing case sensitive / case-insensitive) to avoid code repetition?

2022-10-17 12:07 UTC, Lorak-mmk commented on scylla-rust-wrapper/src/statement.rs
> +            name_str = name_str.strip_suffix('\"').unwrap().to_string();
Why `to_string()`? It would be better to only use `&str` to avoid allocations

2022-10-17 13:40 UTC, Lorak-mmk commented on scylla-rust-wrapper/src/statement.rs
> +                                && col.name.to_lowercase() == name_str.to_lowercase()
[eq_ignore_ascii_case](https://doc.rust-lang.org/std/primitive.str.html#method.eq_ignore_ascii_case) could maybe be enough - original cpp driver doesn't handle utf8 at all.

2022-10-19 19:30 UTC, Gor027 commented on scylla-rust-wrapper/src/query_result.rs
> +    }
In `bind_cql_value_by_name`, if the `name` is inside quotes then it looks for a case-sensitive match, otherwise, if quotes are not present, it looks for case-insensitive matches and binds the value to all of the matched columns. In `cass_row_get_column_by_name_n`, it always returns the first match.

2022-11-14 10:40 UTC, Lorak-mmk commented on scylla-rust-wrapper/src/query_result.rs
> +    }
I'm looking at the cppdriver code, and it looks like here the comparision should also be case-insensitive if the name is quoted - just like in `bind_cql_value_by_name`

2022-11-23 15:33 UTC, Lorak-mmk approved these changes

2022-11-23 15:34 UTC, merged