Fix `ConfigTests` tests
scylladb/cpp-rs-driver pull request #85
Opened 2022-10-13 15:06 UTC by Gor027

Added implementation for functions in `testing.cpp` used in `ConfigTests` tests:
 * get_connect_timeout_from_cluster
 * get_port_from_cluster
 * get_contact_points_from_cluster

To avoid generating bindings for functions that are directly under namespaces and may return objects of custom types, the `testing_utils` header is added as a median between the Rust implementation of those functions and the `testing.hpp` header.

Added `ConfigTests` tests to GitHub Actions for Cassandra and ScyllaDB.

## Pre-review checklist

- [x] I have split my patch into logically separate commits.
- [x] All commit messages clearly explain what they change and why.
- [x] PR description sums up the changes and reasons why they should be introduced.
- [x] I have enabled appropriate tests in `.github/workflows/build.yml` in `gtest_filter`.
- [x] I have enabled appropriate tests in `.github/workflows/cassandra.yml` in `gtest_filter`.

2022-10-17 12:26 UTC, Lorak-mmk requested changes

2022-10-17 12:26 UTC, Lorak-mmk commented on scylla-rust-wrapper/src/testing.rs
> +    contact_points_boxed: *mut *const String,
It probably doesn't matter, but  maybe this should be `*mut *mut`? We use it as `*mut String` when freeing.

2022-10-17 12:26 UTC, Lorak-mmk commented on scylla-rust-wrapper/build.rs
> +
Why are you generating those bindings? It doesn't look like your'e using them anywhere

2022-10-17 12:26 UTC, Lorak-mmk commented on src/testing_utils.cpp
> +}
Why are those implementations required? Can't you just remove them from testing_utils.h?

2022-10-17 12:26 UTC, Lorak-mmk commented on src/testing_utils.h
> +#endif //CPPDRIVERV2_TESTING_UTILS_H
This file is present twice for some reason, with a slight modification. Do we need it twice in our repository?

Also, if I'm understanding this correctly, those are signatures for Rust functions that are used in implementation of `testing.hpp`. If that's the case then:
1. Name should be different than `testing_utils.h` - something like `testing_rust_impls.h` maybe?
2. This file should not be written by hand, but rather generated - cbindgen is a tool to do that

2022-10-24 10:08 UTC, Gor027 commented on src/testing_utils.cpp
> +}
We can safely remove them, but I guess this way it will be much easier to find which testing functions are yet to be implemented.

2022-10-24 10:42 UTC, Gor027 commented on scylla-rust-wrapper/src/testing.rs
> +    contact_points_boxed: *mut *const String,
I guess that does not have an effect on the generated code and rather is a question of documenting intent.

2024-09-09 14:25 UTC, muzarski commented
Closing in favor of https://github.com/scylladb/cpp-rust-driver/pull/163

2024-09-09 14:25 UTC, closed without merging