Add fetching tracing ID associated with a request
scylladb/cpp-rs-driver pull request #86
Opened 2022-10-13 22:23 UTC by Gor027

Added implementation for `cass_future_tracing_id`

Enabled `TracingTests` in GitHub actions for ScyllaDB and Cassandra

## Pre-review checklist

- [x] I have split my patch into logically separate commits.
- [x] All commit messages clearly explain what they change and why.
- [x] PR description sums up the changes and reasons why they should be introduced.
- [x] I have enabled appropriate tests in `.github/workflows/build.yml` in `gtest_filter`.
- [x] I have enabled appropriate tests in `.github/workflows/cassandra.yml` in `gtest_filter`.

2022-10-17 10:42 UTC, Lorak-mmk requested changes

2022-10-17 10:42 UTC, Lorak-mmk commented on scylla-rust-wrapper/src/future.rs
> +        _ => CassError::CASS_OK,
Why is `CASS_OK` returned instead of `CASS_ERROR_LIB_INVALID_FUTURE_TYPE`?

2022-10-17 10:42 UTC, Lorak-mmk commented on scylla-rust-wrapper/src/future.rs
> +        Ok(CassResultValue::QueryError(err)) => CassError::from(err.as_ref()),
CPP version always returns `CASS_ERROR_LIB_INVALID_FUTURE_TYPE`, `CASS_ERROR_LIB_NO_TRACING_ID` or `CASS_OK`, but your version can return other codes. Please fix this.

2022-10-26 10:48 UTC, Lorak-mmk approved these changes

2022-11-14 10:14 UTC, Lorak-mmk approved these changes

2022-11-14 10:14 UTC, merged

2023-01-02 14:45 UTC, Lorak-mmk commented
@Gor027 This PR implemented `cass_future_tracing_id`, but it didn't remove it from limitations table in README. Please fix this

2023-01-03 13:42 UTC, Gor027 commented
> @Gor027 This PR implemented `cass_future_tracing_id`, but it didn't remove it from limitations table in README. Please fix this

Sure. I will send the update in a new PR.