Resolve minor fixme and todo comments
scylladb/cpp-rs-driver pull request #87
Opened 2022-10-26 23:57 UTC by Gor027

Replaced `CASS_ERROR_LAST_ENTRY` with more descriptive error codes while converting `QueryError` to `CassError`.

Set fetching schema metadata flag in `SessionBuilder` config.

Added port validation in cluster configuration.

Imported Rust driver by commit hash 358eabbbb71c.
This enabled to use the `allow_remote_dcs_for_local_cl` flag while creating a `DcAwareRoundRobinPolicy`.

## Pre-review checklist

- [x] I have split my patch into logically separate commits.
- [x] All commit messages clearly explain what they change and why.
- [x] PR description sums up the changes and reasons why they should be introduced.
- [ ] I have enabled appropriate tests in `.github/workflows/build.yml` in `gtest_filter`.
- [ ] I have enabled appropriate tests in `.github/workflows/cassandra.yml` in `gtest_filter`.

2022-11-14 10:32 UTC, Lorak-mmk requested changes

2022-11-14 10:32 UTC, Lorak-mmk commented on scylla-rust-wrapper/src/cass_error.rs
> +            DbError::RateLimitReached { .. } => CassError::CASS_ERROR_SERVER_UNAVAILABLE,
Add a TODO to change this to appropriate error in the future

2022-11-14 10:32 UTC, Lorak-mmk commented on scylla-rust-wrapper/src/cluster.rs
> +    }
Is this parameter deprecated because Rust driver doesn't support it? It looks like it's still working in cpp driver.

2022-11-22 11:46 UTC, Gor027 commented on scylla-rust-wrapper/src/cluster.rs
> +    }
Yep, the Rust driver does not support it, but the parameter Is also deprecated in the C++ driver.

```Rust
/*
* @deprecated The remote DC settings for DC-aware are not suitable for most
* scenarios that require DC failover. There is also unhandled gap between
* replication factor number of nodes failing and the full cluster failing. Only
* the remote DC settings are being deprecated.
* ...
* @param[in] used_hosts_per_remote_dc The number of hosts used in each remote
* DC if no hosts are available in the local dc (<b>deprecated</b>)
* ...
*/
```

2022-11-23 15:29 UTC, Lorak-mmk approved these changes

2022-11-23 15:34 UTC, merged